### ISSUE TITLE
When you open a file with code，the software interface display bug？

### ISSUE THREAD

**Issue by Ti5mmyt** [fralx/LimeReport#101]
the ReportDesignWidget is blank,but the file is opened successful.
how to fix it?

report.loadFromFile("D:\\456.lrxml");
 report.designReport();

like this is ok

but 
 report.designReport();
report.loadFromFile("D:\\456.lrxml");
this will display bug

**Comment by fralx** [comment]
Hi. 
I can not reproduce the error. 
What kind of the error message do you got?

**Comment by Ti5mmyt** [comment]
The Interface: ReportEngine->LoadFromFile(QString& filename);
when it was called after ReportEngine->designReport();

it will cause a display error in software, the view change into blank.
I think there is a bug in function LoadFromFile(QString& filename).

**Comment by fralx** [comment]
This is a normal course of events.
Before edit something you have to load it.
ReportEngine->designReport(); opens the designer window in the modal mode end if you call loadFromFile after this method, it will be run after the designer will be closed
