### ISSUE TITLE
Clearer code

### ISSUE THREAD

**Issue by pasnox** [fralx/LimeReport#102]
Please try to provide library code bulding with such enabled:

DEFINES *=
  QT_NO_CAST_FROM_BYTEARRAY \\
  QT_NO_CAST_FROM_ASCII \\
  QT_NO_CAST_TO_ASCII \\
  QT_NO_URL_CAST_FROM_STRING \\
  QT_STRICT_ITERATORS

**Comment by fralx** [comment]
It seems to be building with these definitions without any problems.

**Comment by fralx** [comment]
I added these definitions to common.pri
and built it with Qt 5.8 clang 64

**Comment by pasnox** [comment]
Ok, it is QtZint that does not build, will report issue on this project then.
Can closethis issue then ;)
