### ISSUE TITLE
stretching the last line

### ISSUE THREAD

**Issue by yanis60** [fralx/LimeReport#103]
Hi,
i created an invoice using your project and it work but i want to stretch the last line of the invoice to fit all the page verticaly, i did it but manually.

can you please help me how to do that?
here is the example.
[Documents.zip](https://github.com/fralx/LimeReport/files/1901850/Documents.zip)

**Comment by fralx** [comment]
Hi, i will think about it :)

**Comment by yanis60** [comment]
thank you very much ;)

**Comment by yanis60** [comment]
ok thank you that what i'm looking for.
you can close this now.
