### ISSUE TITLE
[Feature Request] QtScript QObject injection

### ISSUE THREAD

**Issue by pasnox** [fralx/LimeReport#104]
We currently have QtScript as a way to tweak our data in the report, still sometimes we need code from c++ objects.
Please provide a way to register QObject's in the QtScript engine so we can use Qt properties/slots/invokable in the QtScript environment, like:

$S{the_injected_object_name.function(...)}

**Comment by fralx** [comment]
Hi! 
You can get access to script engine via: report->scriptManager()->scriptEngine() and register QObject there.
