### ISSUE TITLE
ReportDesigner does not refresh after ReportEngine->loadFrom*()

### ISSUE THREAD

**Issue by sg-james** [fralx/LimeReport#106]
What I'm trying to do is load different lrxml from QByteArray into an already open ReportDesignWindow.

```cpp
// Design report
LimeReport::ReportEngine engine;
auto window = engine.getDesignerWindow();
window.showNonModal();

// save it somewhere
QByteArray lrxml = engine.saveToByteArray();

// later on, ..
QByteArray lrxml = ... // from saved xml

engine.loadFromByteArray(&lrxml);
```

If the designer window is already created, various reportEngine.loadFrom*() functions do not refresh the page.

This different from ReportDesignWindow::loadFromFile, which first clears ReportDesignWidget, then loads from file, then createsTabs().

Is there some kind of signal to indicate the reportEngine::loadFrom*() functions have 'reset'.
It could connect to some kind of ReportDesignWidget::reloadReport().

Maybe I could just write the byte array to a temporary file to get around this

**Comment by fralx** [comment]
I'll think about it

**Comment by fralx** [comment]
I've added loaded() signal to ReportEngine and report designer window refreshing  after load report

**Comment by sg-james** [comment]
This is working great! Thanks!
