### ISSUE TITLE
QQmlEngine vs QJSEngine in Qt 5.5

### ISSUE THREAD

**Issue by sg-james** [fralx/LimeReport#107]
Continuing from #105, I can produce a minimal example as to why Qt 5.5.1 does not work with QJSEngine and Qt 5.6 does.

The issue lies in using QQmlEngine instead of QJSEngine.

```cpp
    bool useQml = (ui->comboBox->currentText() == "QQmlEngine"); // true fails, false OK
    QScopedPointer<QJSEngine> engine( useQml ? new QQmlEngine() : new QJSEngine() );

    QString initScript = R"(function testString(){ return "test"; } )";
    QString call = "testString()";

    engine->evaluate(initScript);
    QJSValue res = engine->evaluate(call);

    if (res.isError())
    {
       qCritical() << "Error in line " << res.property("lineNumber").toString() << ": " << res.toString();
    }
    else
    {
        qDebug() << "Res: " << res.toString();
    }
```

Edit:
Changing this "works", in my limited testing
```typedef QQmlEngine ScriptEngineType;``` to
```typedef QJSEngine ScriptEngineType```,

**Comment by fralx** [comment]
It's looks strange becouse QQmlEngine inherited from QJSEngine,  but it's a fact :) I've changed QQmlEngine to QJSEngine as you suggested.
