### ISSUE TITLE
Cannot print any report

### ISSUE THREAD

**Issue by yanis60** [fralx/LimeReport#115]
Hi,
I can't print any report with the latest version of develop branch.
could you please check it??

**Comment by fralx** [comment]
Hi,
I have checked. It works normal for me. 
Could you explain more detail what happens in your case?

**Comment by yanis60** [comment]
when i use printreport() function my software crashes and a message like microsoft visual c++ something like this appear or maybe the erreor is due to the update of Qt to 5.11

**Comment by yanis60** [comment]
Finally i fixed my problem.
it' due to when i update Qt to 5.11 i ddn't replace the old library windowsprintsupport.dll, when i did it now it work :)

Sorry for this.

**Comment by fralx** [comment]
Ok !  :)
