### ISSUE TITLE
embedding report into qt application

### ISSUE THREAD

**Issue by yanis60** [fralx/LimeReport#119]
Hi,

Is it possible to embed a report directly in a QWidget without opening a report preview?

if possible, can you please show me how?

**Comment by newsages** [comment]
Read:
https://github.com/fralx/LimeReport/issues/21

**Comment by yanis60** [comment]
This line??
report->createPreviewWidget(QWidget *parent = 0)

**Comment by newsages** [comment]
Yeaaaaa. 2 years old  ;)
Try it.

**Comment by yanis60** [comment]
ok sorry i didn't see it.
it works now
