### ISSUE TITLE
Missing border near pagefooter

### ISSUE THREAD

**Issue by xdien** [fralx/LimeReport#121]
After I pull the latest version from the master. Old reports do not show borders near the pagefooter.
-If I drag it deflected with another textbox then it re-display, if correct adjustment is not displayed.
![missing border](https://user-images.githubusercontent.com/3887577/43775987-bce1e11e-9a78-11e8-8c16-61a3ee1ca781.PNG)
-Show again if I skew the textbox with one line.
![missing](https://user-images.githubusercontent.com/3887577/43776100-066317c2-9a79-11e8-9821-cc3cc3367fd0.PNG)

**Comment by fralx** [comment]
If you set up the page zoom to 100%, will the line is shown?

**Comment by xdien** [comment]
I'm sorry for the slow response. 
-It does not show up again unless I go to the design tool to drag the textbox skew. It does not happen with the data band far from the page footer.

**Comment by xdien** [comment]
This has been fix 5ffca40

**Comment by fralx** [comment]
This is because scale calculations unfortunately are not accurate to a pixel 
In new versions  the preview by default shows the page in the "Fit With" mode,
but in versions before it was "Percents"(50%) mode.   
You can try to lock scale percent via report->setPreviewScaleType(LimeReport::Percents,50);
Does it suit you?

**Comment by xdien** [comment]
Thanks for the help, maybe I will temporarily restore the previous version. wait for updates for this issue.

**Comment by fralx** [comment]
Just for experiment, replace lrbanddesign.cpp with attached, will it fix the problem ?  
[lrbanddesignintf.cpp.zip](https://github.com/fralx/LimeReport/files/2273247/lrbanddesignintf.cpp.zip)
