### ISSUE TITLE
SUM function for all pages

### ISSUE THREAD

**Issue by yanis60** [fralx/LimeReport#126]
Hi,
I have invoices and orders created by Limereport, when an invoice or order has many pages the sum function accumulates a different amount for each page, what i want is the last page will accumulate all the lines of each pages to not have different amount.

Can you please fix this?

**Comment by yanis60** [comment]
hi,
i used datafooter and report footer works perfectly but the footer is not at the bottom of the page like page footer did that's why i use page footer if there is any thing to make data footer staying at the bottom like page footer it will be amazing

**Comment by fralx** [comment]
You can use Sum function in the page footer if you will call it with third parameter **currentPage**

**Comment by yanis60** [comment]
and it will accumulates all the lines in the pages to one amount ?

**Comment by fralx** [comment]
Yes, it will :)

**Comment by yanis60** [comment]
I can't add currentpage parameter to this $S{SUM($D{stock.pt},"det")}

**Comment by yanis60** [comment]
not working :'( the sum function creates a different amount for each page

**Comment by fralx** [comment]
Oh, i am sorry. I have wrong read your message. The SUM function in page footer calculate all lines at page not pages.

**Comment by fralx** [comment]
Ok, i will check it and fix

**Comment by yanis60** [comment]
thank you :D

**Comment by fralx** [comment]
I have fixed tearoff band. Check it please

**Comment by yanis60** [comment]
thank you, it's works now as i want :) thank you again

**Comment by fralx** [comment]
You are welcome ;)
