### ISSUE TITLE
Death loops and printers

### ISSUE THREAD

**Issue by xdien** [fralx/LimeReport#131]
I use with Qt 5.12, Windows 7 64bit. mingw 5.3. When I try to upgrade from the stable version to develop. There are two problems.
Death loops: I click on the print icon in the review form.
The program immediately crashes but does not exit. in the window i see the loop.

>
>QPainter::setFont: Painter not active
>QPainter::setPen: Painter not active
>QPainter::save: Painter not active
>QPainter::restore: Unbalanced save/restore
QPainter::restore: Unbalanced save/restore
QPainter::save: Painter not active
QPainter::setClipPath: Painter not active
QPainter::setWorldTransform: Painter not active
QPainter::save: Painter not active
QPainter::setOpacity: Painter not active
QPainter::save: Painter not active
QPainter::setFont: Painter not active
QPainter::setPen: Painter not active
QPainter::save: Painter not active
QPainter::worldTransform: Painter not active
QPainter::setOpacity: Painter not active
QPainter::restore: Unbalanced save/restore
QPainter::clipRegion: Painter not active
QPainter::setClipRect: Painter not active
QPainter::translate: Painter not active
QPainter::fontMetrics: Painter not active
QPainter::setOpacity: Painter not active
QPainter::pen: Painter not active
QPainter::setPen: Painter not active
QPainter::pen: Painter not active
QPainter::setPen: Painter not active
QPainter::pen: Painter not active
QPainter::setPen: Painter not active
QPainter::setPen: Painter not active
QPainter::setPen: Painter not active
QPainter::restore: Unbalanced save/restore
QPainter::setFont: Painter not active
QPainter::setPen: Painter not active
QPainter::save: Painter not active
QPainter::restore: Unbalanced save/restore
QPainter::restore: Unbalanced save/restore
QPainter::restore: Unbalanced save/restore
QPainter::restore: Unbalanced save/restore
QPainter::setWorldTransform: Painter not active
QPainter::setOpacity: Painter not active

The second problem is when I print on A4 paper.
The paper is left outside it like this:
[https://imgur.com/a/ueyoQH1](url)
I identify the cause not by the printer. because if you save to pdf then print it does not happen. At the same time, I used 2 different versions for test printing, so the develop version was like that.

**Comment by fralx** [comment]
Hi!
The first one: I cant reproduce this behavior. I have tested the develop version on Win10 64, Qt 5.12, mingw730_64  and not found the problem with "Death loops". 
The second one: It's not bug it's a feature :) Unlike master, new version can print multipage reports and if  the "master" version scale report content in order to fit entirely on the page, the "develop" just print the content as is.

**Comment by xdien** [comment]
I apologize for the slow response.
The first problem is difficult to reproduce. When you select a printer in the dialog with a "print to file" checkmark, this will happen. I have returned to the version stable everything is very good. Also no longer state that loop.
Thank you for creating an extremely good reporting library for Qt!

**Comment by fralx** [comment]
What kind of printer to print to file do you use?
Could you send me the report template that you show me before?

**Comment by xdien** [comment]
It happens like this. I try to understand the reason that the second case has a page deviation problem (feature). I want to find out how the difference between the export pdf function from the platform is different from the data that the printer actually received. so I followed in the picture.
A small note is that the printer is offline.
[https://imgur.com/a/R56ZGhG](https://imgur.com/a/R56ZGhG)
Here is the link to my report file.
[https://www.mediafire.com](https://www.mediafire.com/file/cbbrwrx9ilk4rhn/dv_bang_du_toan_sua_chua.lrxml/file)

**Comment by fralx** [comment]
Thanks! I will investigate the problem :)

**Comment by fralx** [comment]
Hi. Could you check [feature/ignore_priner_rect](https://github.com/fralx/LimeReport/tree/feature/ignore_priner_rect).
Will it fix deviation problem ?

**Comment by xdien** [comment]
I have just tried your new branch. It happened less, but still hung up for the foxit reader, but the problem was probably solved because there was no loop in the normal printer. I have a video describing the problem happening [https://youtu.be/gfv2yC-251g](https://youtu.be/gfv2yC-251g)

**Comment by fralx** [comment]
Hi. I have made some changes after watching your video. Could you check  "feature/ignore_priner_rect"
branch again ?

**Comment by xdien** [comment]
I just checked it again with the change it worked well. The problem has been solved.
