### ISSUE TITLE
Define default printer when printing

### ISSUE THREAD

**Issue by yanis60** [fralx/LimeReport#132]
Hi,
I need to define a default printer when printing using limereport, could you please give me an example?
Thanks

**Comment by yanis60** [comment]
I found a way lol thank you .

**Comment by liufeijin** [comment]
> I found a way lol thank you .

hi
Could you share your experience?
My report has many pages,  i want some page print to A printer and some page print to B printer .

**Comment by yanis60** [comment]
Hi,
You have to use a qprinter object to do this.

**Comment by liufeijin** [comment]
> Hi,
> You have to use a qprinter object to do this.

Many thanks for your experience.
Cloud you give a instruction how to control Lime print out a special page in a PDF(made by Lime)?
Script in Lime or ?  I have no ideal.
best regards,
jeff
