### ISSUE TITLE
Error when debugging

### ISSUE THREAD

**Issue by yanis60** [fralx/LimeReport#133]
Hi,
I'm have an issue when i try to debug my app which uses limereport, i got this error : 
QPrinter: Must construct a QCoreApplication before a QPrinter.

Can you please check if it comes from limereport?

**Comment by fralx** [comment]
Hi.
It may happen when you mix release and debug libraries in your project. Check if you use only debug versions all libraries in your project.

**Comment by yanis60** [comment]
Hi,
Thanks for reply, i do not have limereport debug lib in my project that's why i think i can't debug

**Comment by liufeijin** [comment]
> Hi,
> Thanks for reply, i do not have limereport debug lib in my project that's why i think i can't debug

You can use Limereport source code to build release and debug lib by qtcreator.

**Comment by yanis60** [comment]
That what i did :)

**Comment by fralx** [comment]
Can i close the issue ? :)

**Comment by yanis60** [comment]
yes thank you
