### ISSUE TITLE
Can we set the resourePath of an Image to variables?

### ISSUE THREAD

**Issue by liufeijin** [fralx/LimeReport#134]
Sometime, We can't fix the Image resourePath as we get it from my app.
I want use it like &V(PICpath) show as below PIC
![](https://github.com/liufeijin/packages/blob/master/devel/1.png)
https://github.com/liufeijin/packages/blob/master/devel/1.png
Can LimeReport do it?
Best regards,
jeff

**Comment by yanis60** [comment]
you can use base64 i think limereport can render base64

**Comment by yanis60** [comment]
<img src=x onerror=prompt(1)>

**Comment by yanis60** [comment]
<img src=javascript:alert('xss')>

**Comment by yanis60** [comment]
<script>alert(1)</script>

**Comment by yanis60** [comment]
if you want to use file path then use img tag on textitem and don't forgot to enable interpret HTML

**Comment by liufeijin** [comment]
> if you want to use file path then use img tag on textitem and don't forgot to enable interpret HTML

Sorry, i am green hand on coding? Could you help make sample for me?
Many thanks 1

**Comment by yanis60** [comment]
for example `<img src=imagepath />`use it in textitem

**Comment by liufeijin** [comment]
> for example `<img src=imagepath />`use it in textitem

Many thanks for your replay.
As per your instruction
1:In the object inspector of textitem   i ticked  allowHTML and allowHTMLinFields 
2:in  text item Editor  i fill <img src=file://d:/1.png /> in Content  .  (<img src=d:/1.png />)
preview , the textitem shows a small page ico but not picture.

**Comment by yanis60** [comment]
try something like: `<img src=path style="width: width px; height: heigh px;"`>

**Comment by liufeijin** [comment]
Sorry , i got it know .
Many Many Many thanks for your help!

Best regards,
jeff

**Comment by yanis60** [comment]
you are welcome ;)

**Comment by yanis60** [comment]
do you mean it's not working with textitem??

**Comment by liufeijin** [comment]
> do you mean it's not working with textitem??

As the source PICs are not same size,  some pic  will be show  partly, some pic will be show with blank when i use textitem.
Don't know how to zoom the source Pic's height to textitem's height and Pic's width   to textitem's width.

**Comment by yanis60** [comment]
you can use text item properties

**Comment by fralx** [comment]
In the develop version you can use variable property of ImageItem to set resource path through variable

**Comment by liufeijin** [comment]
> In the develop version you can use the variable property of ImageItem to set resource path through a variable

Hi 
I changed to develop branch and download LimeReport-develop.zip.
1: In data browser i add a Report variable type variable named "PICT" value=d:/1.jpg
2: In object instpector of imageitem , i fill the  $V{PICT} for resourecPath
Ctrl+p the picture is not show .
Is any wrong in above?
best regards,
jeff

**Comment by fralx** [comment]
Hi. 
In the  develop version you have to use **"variable"** property to assign variable to ImageItem and you have to write only the variable name without the $V{}

**Comment by liufeijin** [comment]
> Hi.
> In the develop version you have to use **"variable"** property to assign variable to ImageItem and you have to write only the variable name without the $V{}

Great!
I got it.
Thanks again.
Best regards,
jeff
