### ISSUE TITLE
Does LimeReport show 5 datas with blank?

### ISSUE THREAD

**Issue by liufeijin** [fralx/LimeReport#135]
I want show a blank row after each 5 data rows as below PIC
https://github.com/liufeijin/packages/blob/master/devel/2.png

Best regards,
Jeff

**Comment by fralx** [comment]
Unfortunately, there is no easy way to do it.  
But in the develop version you can do the next trick:
1. create empty SubdetailBand connected to DataBand
2. set SubdetailBand.printIfEmpty property to true
3. in the init script write something like this:
``` javascript
ReportPage1_DataBand1.beforeRender.connect(BFRender)

function BFRender(){
   if ( (line("DataBand1") % 5) == 0 ){
      ReportPage1_SubDetailBand1.autoHeight = false;
   }
}
```

**Comment by liufeijin** [comment]
fralx
Many thanks , i will have a try on it
jeff

**Comment by liufeijin** [comment]
> Unfortunately, there is no easy way to do it.
> But in the develop version you can do the next trick:
> 
> 1. create empty SubdetailBand connected to DataBand
> 2. set SubdetailBand.printIfEmpty property to true
> 3. in the init script write something like this:
> 
> ```js
> ReportPage1_DataBand1.beforeRender.connect(BFRender)
> 
> function BFRender(){
>    if ( (line("DataBand1") % 5) == 0 ){
>       ReportPage1_SubDetailBand1.autoHeight = false;
>    }
> }
> ```

Is the currently develop version1.4.114?

**Comment by liufeijin** [comment]
> Unfortunately i have not the Script user manual yet. I can say that limereport uses javascript as script language.
> 
> > Copy your code inside ,and got the error that Line 1: ReferenceError: ReportPage1_DataBand1 is not defined.
> 
> I wrote the sample it is not direct instruction how to you should do :) You have to write your own script based on your report objects names
hi
Could you give me some *.lrxml with script code?
I want to know how to use in the script like you say init script , what is the whole layout., I will to learn javascript also.
Best regards,
Jeff

**Comment by fralx** [comment]
Here is an example:
[print_gap_after_each_second_row.lrxml.zip](https://github.com/fralx/LimeReport/files/2747043/print_gap_after_each_second_row.lrxml.zip)

**Comment by liufeijin** [comment]
> Here is an example:
> [print_gap_after_each_second_row.lrxml.zip](https://github.com/fralx/LimeReport/files/2747043/print_gap_after_each_second_row.lrxml.zip)

Dear fralx
Many thanks for your example .
Finally i use below script to get 

ReportPage1_DataBand1.beforeRender.connect(aa)
ReportPage1_SubDetailBand10.beforeRender.connect(bb)
function aa(){
      ReportPage1_TextItem15.isVisible=false;
}
function bb(){
   var gapp=line("SubDetailBand10")%5==0;
   ReportPage1_TextItem16.isVisible=gapp;
}
But the report has a little imperfect as the rows of data,PLS refer 
https://raw.githubusercontent.com/liufeijin/QtXlsxWriter/master/examples/1.jpg

Does Lime have anther count  flag from the top for each page?
I want to keep the gap rows are some row when report in col model.
Best regards,
jeff

**Comment by fralx** [comment]
Unfortunately, limereport haven't another line counter.

**Comment by liufeijin** [comment]
Many thanks for your reply.
I will try to find other way .
Thanks again.
jeff
