### ISSUE TITLE
Does LimeReport support 2(or 3) cols for all data in a page

### ISSUE THREAD

**Issue by liufeijin** [fralx/LimeReport#136]
My data row is very short, so i want show it 2 cols in a page as below Pic
https://github.com/liufeijin/packages/blob/master/devel/3.png

Could you give me a instruction ?

Best regards,
jeff

**Comment by fralx** [comment]
Hi.
You can use the columnsCount property of BandItems to create report with multi columns

**Comment by liufeijin** [comment]
fralx
Many thanks for your instruction.
jeff
