### ISSUE TITLE
How to get the pages rang to make the index

### ISSUE THREAD

**Issue by liufeijin** [fralx/LimeReport#138]
For example 
Use Lime Report Designer make a 3 page template .
The first page is cover include a index.
The template of page 2 will generate pages from a datasource (maybe 23 pages)
The template of page 3 will generate pages from anther data source (maybe get 48 pages) 

So the index in cover i need make as below
cover                                              1
dataA                                              2-24
dataB                                              25-72

How to get  2-24 and 25-72 automatic?
Best regards,
jeff

**Comment by liufeijin** [comment]
hi
Many thanks for your help.
As per the video , i got it basically.
Have a anther problem that the TOC will be first page or the last page, can't be on 2nd or 3rd page.
example the report requirements is as below : 

Page 1                        COVER
Page 2                        Preface
Page 3                         INDEX ( TOC)
Page 4   to Page 20     table A 
Page 21 to Page 26     table B.

If i add new pages before  TOC tab at below , TOC will be present on the last page.

Could you give me more instruction?
Best regards,
jeff

**Comment by fralx** [comment]
Hi, I'll think about it :) I do not remember why I decided that the table of contents should be the first or last page.

**Comment by liufeijin** [comment]
> Hi, I'll think about it :) I do not remember why I decided that the table of contents should be the first or last page.

Many thanks for your hard work!

**Comment by liufeijin** [comment]
> Hi, I'll think about it :) I do not remember why I decided that the table of contents should be the first or last page.

I tried to read your source code 2 days and want to find a way, but unfortunately it is exceed my c++ ability .
I give up , so to be waited  you update it when you have time.
Many thanks.
