### ISSUE TITLE
Print specially pages to printer 

### ISSUE THREAD

**Issue by liufeijin** [fralx/LimeReport#139]
hi
I want print specially pages to a color printer (slow) and some pages to a mono printer (faster).
I open  the lrreportengine.h and found some as below

class PrintRange{
public:
    int fromPage() const { return m_fromPage;}
    int toPage() const { return m_toPage;}
    QPrintDialog::PrintRange rangeType() const { return m_rangeType;}
    PrintRange(QAbstractPrintDialog::PrintRange rangeType=QPrintDialog::AllPages, int fromPage=0, int toPage=0);
    void setRangeType(QAbstractPrintDialog::PrintRange rangeType){ m_rangeType=rangeType;}
    void setFromPage(int fromPage){ m_fromPage = fromPage;}
    void setToPage(int toPage){ m_toPage = toPage;}
and 
 bool    printPages(ReportPages pages, QPrinter *printer);

Seems the printPages can do it . but confused how to define the "ReportPages " IN printPages();
  my app is like this 
      QString txt="D:/t.PNG";
      m_report.dataManager()->setReportVariable("PICd", txt); //to add datasource to report engine
       m_report.loadFromFile("d:/TEST.lrxml"); //to load report template file
      m_report.previewReport();// to generate report and preview
      m_report.printToPDF("d:/1.pdf");
   then how to make and pass the "ReportPages" to printPages()

Best regards,
jeff

**Comment by fralx** [comment]
Hi.
If you are using a preview, you cannot select a range of pages in the code this can only be done manually in the print dialog box.

**Comment by liufeijin** [comment]
> Hi.
> If you are using a preview, you cannot select a range of pages in the code this can only be done manually in the print dialog box.

Do we have any other chance in app code  to print specially page to print? 
Or can print only some pages by script ?

**Comment by fralx** [comment]
You can create two different report and print it as you wish :)

**Comment by liufeijin** [comment]
> You can create two different report and print it as you wish :)
I considered this way ,but   the page number will be confused if i specially create a report for printing some pages.

**Comment by fralx** [comment]
I see, i will think about it :)

**Comment by liufeijin** [comment]
Add a attribute of each page to control print?

**Comment by liufeijin** [comment]
> I see, i will think about it :)

This just is a reminder,hope you can consider to resolve it when you have time.

**Comment by liufeijin** [comment]
> > I see, i will think about it :)
> 
> if i set the printable to false the page will be not printed but the page number is not counted .
> If have anther flag like printable but will be not printed and page number is counted ,it is better?

Dear fralx
Could you help to improve this function ?
I stuck in this.
Many thanks if you have time to consider it!

**Comment by fralx** [comment]
Hi, I will start next week

**Comment by fralx** [comment]
Hi, I have finished the multi-printer feature. You can test it.
How to use it:
From now the report's pages have a printerName property, You can fill the property with the printer name,  then you can run the printReport(QMap<QString, QPrinter*> printers) method with QMap that contains the key which is a printer name and value is a pointer to the printer.

**Comment by liufeijin** [comment]
Dear fralx
Many thanks for your help.I will test and report to you the result.

**Comment by liufeijin** [comment]
Dear fralx
I just tested it. use below codes:
       QPrinter* printer = new QPrinter;
        QPrinter* printer2 = new QPrinter;

        QPrinterInfo prints;
        QStringList sd;
        sd=prints.availablePrinterNames();
        printer->setPrinterName("pdfFactory");
        printer2->setPrinterName("HP LaserJet P1007");
        
       // QPrintDialog dialog(printer);
       // if (dialog.exec()){
            QMap<QString, QPrinter*> printers;
            printers.insert("P1",printer);
            printers.insert("P2",printer2);
            report->printReport(printers);
       // }
        report->previewReport();
my computer has printers that "pdfFactory", "Microsoft XPS Document Writer", "Microsoft Print to PDF", "HP LaserJet P4515 UPD PCL 6", "Fax" 
It is ok if i set P2（ printer2->setPrinterName("HP LaserJet P1007")).
The P2 printer can't generate PDF file(P1 generates file ok) if i set P2( printer2->setPrinterName("Microsoft Print to PDF"); or printer2->setPrinterName("Microsoft XPS Document Writer");)
and got error  : 
win_musl::production::ZipInterleaver::Rundown, m_activeParts != 0 is true, There are still parts open, package is invalid on close.
win_musl::production::ZipInterleaver::Rundown, m_activeParts != 0 is true, There are still parts open, package is invalid on close.
win_musl::production::ZipInterleaver::Rundown, m_activeParts != 0 is true, There are still parts open, package is invalid on close.
win_musl::production::ZipInterleaver::Rundown, m_activeParts != 0 is true, There are still parts open, package is invalid on close.
win_musl::production::ZipInterleaver::Rundown, m_activeParts != 0 is true, There are still parts open, package is invalid on close.
win_musl::production::ZipInterleaver::Rundown, m_activeParts != 0 is true, There are still parts open, package is invalid on close.
QWin32PrintEngine::newPage: EndPage failed  
QWin32PrintEngine::end: EndPage failed (0x61212945) .
The file  *.pdf or *xps will be present by P2 but empty (size is 0)

I don't if the problem is caused by "Microsoft Print to PDF" or "Microsoft XPS Document Writer"driver.

Anyway ,  it is ok and works fine if set : 
        printer->setPrinterName("pdfFactory");
        printer2->setPrinterName("HP LaserJet P1007");

Many thanks  for your help!

**Comment by liufeijin** [comment]
Dear fralx
I checked my os the problem caused by xps driver!(Microsoft Print to PDF" or "Microsoft XPS Document Writer" , the state is can't used.
So this function is perfect！I printed out same pages to HP LaserJet P1007 , other pages to pdf. All pages are ok.
So i close this.
Many thanks for your perfect work!
