### ISSUE TITLE
Printing a tree from database

### ISSUE THREAD

**Issue by yanis60** [fralx/LimeReport#140]
Hi,
I need to print the following tree, for example ...

litem1
l--item2
l----item3
i see that i can use  subqueries but i don't know how to do it, can you please give me an example?

Thanks

**Comment by fralx** [comment]
Here is the  example
[TreeDemo.zip](https://github.com/fralx/LimeReport/files/2774240/TreeDemo.zip)

**Comment by yanis60** [comment]
thank you so much, you can close this now.
