### ISSUE TITLE
image item doesn't support wmf format

### ISSUE THREAD

**Issue by liufeijin** [fralx/LimeReport#145]
WMF can display  the image export from autocad very plain.

**Comment by liufeijin** [comment]
seems it is not considered . so close it.

**Comment by liufeijin** [comment]
Hi fralx
Do you have plan on image item supports WMF format in future?

**Comment by fralx** [comment]
Hi!
Unfortunately, Qt does not support the WMF format, and I do not have the time and resources to implement WFM support. If there is exists an opensource library that adds support for WMF to Qt and you will find it,  i can try to use it.

**Comment by liufeijin** [comment]
I google wmf and qt5. Didn't find good lib.
Seems the WMF is not support directly from windows2000 . 
Somebody suggests to use SVG.
So we can give up the wmf and no need wast time on it.
Many thanks for your help!

**Comment by liufeijin** [comment]
> Hi!
> Unfortunately, Qt does not support the WMF format, and I do not have the time and resources to implement WFM support. If there is exists an opensource library that adds support for WMF to Qt and you will find it, i can try to use it.

fralx
 i found 2  projects on github about WMF  for your reference .  Just for your information if you have time can have a look.
https://github.com/rel-eng/QWmfPlugin
https://github.com/reporter123/libkowmf
