### ISSUE TITLE
Limereport library

### ISSUE THREAD

**Issue by yanis60** [fralx/LimeReport#146]
Hi,
I recently compiled a qt project using msvc 2015, from qt it works perfect with limereport but when i deploy the program and run it, it says the entry point setPreviewWindowsTitle..... is not found on the dynamic link library program.exe.

Can you please show me how to add the library limereport on project file for msvc2015?

PS : it work perfectly when deploying after compiling with mingw 5.3

**Comment by fralx** [comment]
As for me there is no special manipulation with limereport is needed to build with MSVC2015 :).
Here is the sample where limereport is built with MSVC2015,
may be it can help you.
http://limereport.ru/resources/LimeReport_1.5.zip

**Comment by fralx** [comment]
It may be different dll sets when program run under qt creator enviroment  or as standalone

**Comment by yanis60** [comment]
i used in both side the same dll (limereport) file

**Comment by fralx** [comment]
Just dll

**Comment by fralx** [comment]
Look, if limereport.dll works under qtcreator that is all right with it, isn't it?

**Comment by yanis60** [comment]
it works perfectly under qt creator but not on standalone
ok now without qtzint.dll?

**Comment by fralx** [comment]
What different when program run under qtcreator? It is enviroment.

**Comment by yanis60** [comment]
yes of course it's environement

**Comment by fralx** [comment]
Is my sample working for you?

**Comment by yanis60** [comment]
it says eror 404 page not found when i try to download it

**Comment by fralx** [comment]
One moment, i will check it

**Comment by fralx** [comment]
I am sorry, i have mistaken
This is right link http://limereport.ru/resources/LimeReport1_5.zip

**Comment by yanis60** [comment]
there is a problem with paint function and his parameters, when i run my program it say this : 

The procedure entry point ?paint@QGraphicsRectItem@@UAEXPAVQPainter@@QStyleOptionGraphicItem..... could not be located in the dynamic link library limereport.dll

Not that i'm using QGraphicsItem in my program

**Comment by fralx** [comment]
Do you run my sample?

**Comment by fralx** [comment]
It is important, if it runs for you, we can do some checks

**Comment by fralx** [comment]
Ok. Try to build limereport.dll with MSVC2015 and put it instead of my library. Will it still work?

**Comment by fralx** [comment]
MSVC2015 should be a 32 bit

**Comment by yanis60** [comment]
unfortunatly not working too with your sample

**Comment by fralx** [comment]
What error ?

**Comment by yanis60** [comment]
all the errors are related to qgraphicsitem class

**Comment by yanis60** [comment]
When i compile using mingw 53 32 bits, it works perfectly even on standalone

**Comment by fralx** [comment]
Did you install qt by installer or built it from source code?

**Comment by yanis60** [comment]
yes by installer of course

**Comment by fralx** [comment]
It's very strange. My build process is all the same for MSVC and MinGW and as you can see it is works :)

**Comment by yanis60** [comment]
yes so it should be my program?

**Comment by fralx** [comment]
I don't think so. If your library would have run on my sample it will be the sign that something wrong with your program but it didn't work. But I am can't imagine where the problem.

**Comment by fralx** [comment]
Maybe you get the wrong limereport.dll this is just an assumption :) Check please the MCVS build path.

**Comment by yanis60** [comment]
ohhh tanks god it worked now i solve it :), the problem was with others libraries, i used the wrong libraries (mingw53) not msvc now works perfectly.

Thsnk you very much for your effort ;)

**Comment by fralx** [comment]
You are welcome ;)
