### ISSUE TITLE
suggestion for barcodeitem

### ISSUE THREAD

**Issue by liufeijin** [fralx/LimeReport#147]
Now , the QRcode is more poplar and can include more information.
Below address is my QRcode demo that can generate QRcode with log picture in center.
https://github.com/liufeijin/qt-bqrencode/blob/master/MyQrcodeDos.rar
Just is a suggestion. Now i generate the PIC firs and then put it in the limeReport file.

Best regards,
jeff

**Comment by liufeijin** [comment]
Hi Fralx
Do you have consider on this function?
![2](https://user-images.githubusercontent.com/19425403/52558158-82d5d000-2e2c-11e9-986e-477f81a1a726.png)

**Comment by fralx** [comment]
Unfortunately, i didn't have much time for considering this suggestion. When i have time i will do it :) Limereport can support qrcode through qzint maybe it can't draw the image in center but qrcode can :)

**Comment by liufeijin** [comment]
OK. Noted.
Many thanks for your help！
