### ISSUE TITLE
Use static QT5.12 to build limereport fail.

### ISSUE THREAD

**Issue by liufeijin** [fralx/LimeReport#148]
I have build a static QT5.12 and want to build LimeReport , fail and got some error as below

Qt5Designer.lib(abstractformbuilder.obj):-1: error: LNK2005: "public: void __cdecl FormBuilderSaveLayoutEntry::setAlignment(class QFlags<enum Qt::AlignmentFlag>)" (?setAlignment@FormBuilderSaveLayoutEntry@@QEAAXV?$QFlags@W4AlignmentFlag@Qt@@@@@Z) 已经在 Qt5UiTools.lib(abstractformbuilder.obj) 中定义

lrdialogdesigner.obj:-1: error: LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: static void __cdecl QDesignerComponents::initializePlugins(class QDesignerFormEditorInterface *)" (__imp_?initializePlugins@QDesignerComponents@@SAXPEAVQDesignerFormEditorInterface@@@Z)，该符号在函数 "public: __cdecl LimeReport::DialogDesignerManager::DialogDesignerManager(class QObject *)" (??0DialogDesignerManager@LimeReport@@QEAA@PEAVQObject@@@Z) 中被引用

lrdialogdesigner.obj:-1: error: LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: static class QObject * __cdecl QDesignerComponents::createTaskMenu(class QDesignerFormEditorInterface *,class QObject *)" (__imp_?createTaskMenu@QDesignerComponents@@SAPEAVQObject@@PEAVQDesignerFormEditorInterface@@PEAV2@@Z)，该符号在函数 "public: __cdecl LimeReport::DialogDesignerManager::DialogDesignerManager(class QObject *)" (??0DialogDesignerManager@LimeReport@@QEAA@PEAVQObject@@@Z) 中被引用

Cloud you give some instruction ?

**Comment by fralx** [comment]
Hi. 
Try to build with CONFIG+=no_formdesigner

**Comment by liufeijin** [comment]
i added it in limereport.pro
TEMPLATE = subdirs
CONFIG +=no_formdesigner
!contains(CONFIG, no_zint){
    CONFIG += zint
}

but still got same errors

**Comment by fralx** [comment]
Try to use this flag for qmake.  And clear project before build.

**Comment by liufeijin** [comment]
yes add flag to qmake , it works fine . got the libs.
Many thanks for your help!
best regards,
jeff
