### ISSUE TITLE
Crash report preview on last update

### ISSUE THREAD

**Issue by yanis60** [fralx/LimeReport#150]
Hi,
I updated my limereport plugin to the latest version, but this version crashes when i preview any report from my application, even chart shows an empty data (the previous version works).

Can you please check it?

**Comment by fralx** [comment]
Hi!
I have checked and it works for me as expected.
Does demo_r1 could show preview from demo_reports for you?

**Comment by yanis60** [comment]
have you made modifications in include folder?

**Comment by fralx** [comment]
Yes

**Comment by yanis60** [comment]
I know where the error is.

I always forgot to update the include folder in my project lol :)

Sorry for disturb
