### ISSUE TITLE
Does it any way to fill below empty by special character

### ISSUE THREAD

**Issue by liufeijin** [fralx/LimeReport#151]
Sometimes the data is less and not enough for filling  a full  page when i use subdetailband connected to a sqlite3 database.
Could i have any way to fill  some --        ---            --                 ---  for reset rows instead of empty rows.
![1](https://user-images.githubusercontent.com/19425403/52520841-3ada7000-2ca9-11e9-8ab4-aaed28416a01.png)

![2](https://user-images.githubusercontent.com/19425403/52520851-61001000-2ca9-11e9-9929-1ca50c4c1c77.png)

**Comment by fralx** [comment]
Unfortunately, there is no way to do it as you want. But you can use columnsFillDirection = Horizontal it will decrease the empty space.

**Comment by liufeijin** [comment]
Hi
Many thanks for your reply.
I used 2 subdetailband to resolved it (not perfect  as it can't mark the skip row).
I think maybe add some empty data rows to database  is a good way.
