### ISSUE TITLE
watermark is not under the contain text

### ISSUE THREAD

**Issue by liufeijin** [fralx/LimeReport#152]
I have set it as " sent to back" ,but the watermark text is on the top still as below PIC
![tim1](https://user-images.githubusercontent.com/19425403/52532101-62d5dc00-2d5a-11e9-9023-8ab1c3fdcdaf.png)

**Comment by fralx** [comment]
The main feature of watermark is that it prints over all the text :) You can change opacity of it for better looking. But if you need to put some text under the contain text don't set watermark property just set transparency to background for the all items  that will printed over it.

**Comment by liufeijin** [comment]
Normally, i think the watermark is under normal text like as the  paper money.
Anyway , As per your instruction i reached my target.
Thanks again!
