### ISSUE TITLE
Can drag item to other node in Report structure window?

### ISSUE THREAD

**Issue by liufeijin** [fralx/LimeReport#153]
Sometime i need move item to other parent , EX move text item from databand to reportpage if the databand height is very big , can't drop the text item object to reportepage as databand coves all area.
I need change the height of databand to small size then drop down text item and resize databand.
If can move the item place in Report structure  windows , it will be fast and easy.
If select the item in Report structure windows and can open the pop menu like in drawing area , will be great.
![1](https://user-images.githubusercontent.com/19425403/52554214-0ee1fa80-2e21-11e9-817f-883365fdf6f5.png)
![2](https://user-images.githubusercontent.com/19425403/52554231-1903f900-2e21-11e9-97f8-bad483404e58.png)

**Comment by fralx** [comment]
Hi!
You can use itemLocation property for changing item location from band to page

**Comment by liufeijin** [comment]
O, You have done it :)
Many thanks!
