### ISSUE TITLE
TOC problem

### ISSUE THREAD

**Issue by liufeijin** [fralx/LimeReport#154]
1:If a page doesn't have databand, it's index page number will be same as last page number.
![1](https://user-images.githubusercontent.com/19425403/52643490-1b954a00-2f18-11e9-9611-7b90d3cd9674.png)
![2](https://user-images.githubusercontent.com/19425403/52643499-20f29480-2f18-11e9-9793-cca7797e8d20.png)
2:If add a empty( databand for the page, the index page number will be 0.
![4](https://user-images.githubusercontent.com/19425403/52643522-2e0f8380-2f18-11e9-897e-a5d6268c07f0.png)
![3](https://user-images.githubusercontent.com/19425403/52643531-31a30a80-2f18-11e9-8972-b73437cd403f.png)
3:if add a databand with a textitem(textitem must be has text) ,the index number will be ok.
But sometime i need a databand with a hide textitem (use script hide) for data group 
![6](https://user-images.githubusercontent.com/19425403/52643724-95c5ce80-2f18-11e9-89fd-07e7a0f1f970.png)
![5](https://user-images.githubusercontent.com/19425403/52643731-98c0bf00-2f18-11e9-96b7-fca115eb9c0c.png)
4:when use afterRender.connect of page, the index page number will be the last page and not the first page number. (this page with databand and will be many pages)
![8](https://user-images.githubusercontent.com/19425403/52643917-e2a9a500-2f18-11e9-8816-133f1e875d7d.png)
![7](https://user-images.githubusercontent.com/19425403/52643924-e6d5c280-2f18-11e9-99f2-759b2d11e74c.png)
Kindly PLS have a look.
Thanks

**Comment by fralx** [comment]
I have fixed it, you can check it.

**Comment by liufeijin** [comment]
Hi fralx
The problem 1-3 are solved prefectly.
The problem 4 is still , it presents the last page number. 
I used the script for index number as below:

$S{
var PageNo;
var ContentKeyName; // 
ContentKeyName=getFieldByKeyField(
   "tableofcontents",
   "Content Key", 
   "Content Key", 
   "$D{tableofcontents.Content Key}"
   );
PageNo=getFieldByKeyField(
   "tableofcontents",
   "Page number", 
   "Content Key", 
   "$D{tableofcontents.Content Key}"
   );
 if (ContentKeyName=="RLBT")
    { ""
    }else
    { PageNo}
}

If you have no time or better method to resolve it, i think maybe i can solve it in script.
Thanks a lot of!

Jeff

**Comment by fralx** [comment]
Hi, as I can see, you use beforeRender event for RLB, but it is a wrong way, you have to use only afterRender event.

**Comment by liufeijin** [comment]
Yes,i specially use beforeRender . if use afterRender the first item of secondlevel index will present before firstlevel index.
![1](https://user-images.githubusercontent.com/19425403/52754248-cd299d80-3034-11e9-9b1b-2e15677e4b14.png)
![2](https://user-images.githubusercontent.com/19425403/52754253-d155bb00-3034-11e9-8f21-ef40c032fe0a.png)
Above is a example include using  afterRender and BeforeRender .
Do you mean the beforeRender is useless?
