### ISSUE TITLE
TOC problem 2

### ISSUE THREAD

**Issue by liufeijin** [fralx/LimeReport#155]
I want get a two level index  for some page 
if i  add the contens by afterRender, the TOC will be wrong 
![1](https://user-images.githubusercontent.com/19425403/52701537-67e29780-2fb5-11e9-8fb7-a0d136e7ff3d.png)
![2](https://user-images.githubusercontent.com/19425403/52701544-6b761e80-2fb5-11e9-84bc-12a6b8fd7d59.png)
I don't know if this is a bug or afterRender has special function.
if i add the contens by beforeRender, the TOC will be correct.
![3](https://user-images.githubusercontent.com/19425403/52701586-86e12980-2fb5-11e9-8c96-023c9b0b127f.png)
![4](https://user-images.githubusercontent.com/19425403/52701591-89dc1a00-2fb5-11e9-9537-2ef905c275b9.png)

but anyway , the blanks i want for second level can be present , still display &nbsp;

jeff

**Comment by fralx** [comment]
You have to allow HTML in the TextItem that showing TOC items

**Comment by liufeijin** [comment]
Yes， i have set to allow HTML in the TexItem that showing page .
![2](https://user-images.githubusercontent.com/19425403/52703847-3b7d4a00-2fba-11e9-9032-cd3961dc82ad.png)

**Comment by liufeijin** [comment]
&nbsp; For other TextItem is OK, I have tested.
I am using the newest dev branch.

**Comment by liufeijin** [comment]
O.  I am Sorry!
I selected the wrong TextItem!
It is ok!
