### ISSUE TITLE
TOC problem 3

### ISSUE THREAD

**Issue by liufeijin** [fralx/LimeReport#156]
Hi fralx
i use below script  for add index content  , but the TOC page itself can't be displayed 
var contenUK1="P1"
var contenUK2="P2"
var contenUK3="CertPage1"
var contenUK4="UserM1"
Reportpage1.afterRender.connect(P1F)
function P1F(){
    addTableOfContentsItem(contenUK1,"1.船舶名称和图片  Ship's Name & Picture")
}
TOC.afterRender.connect(P2F)
function P2F(){
    addTableOfContentsItem(contenUK2,"2.目录    Index")
}
CertPage.afterRender.connect(CertPF)
function CertPF(){
   addTableOfContentsItem(contenUK3,"3.检定证书  Verification  Certificate ")
}

![1](https://user-images.githubusercontent.com/19425403/52703433-4c798b80-2fb9-11e9-98d3-150d5093720b.png)
![2](https://user-images.githubusercontent.com/19425403/52703702-ed684680-2fb9-11e9-9440-664d55654bcc.png)

Kindly PLS have a look!
Best regards,
jeff

**Comment by fralx** [comment]
Hi!
Look, in the your script, you call the addTableOfContens after the index page is rendered. Considering this fact, the index page can't contain that item. You can do the next trick, call addTableOfContens twice in the P1F function, one of that calls may be addTableOfContentsItem("index","Index");. After that in the TextItem which is showing page numbers write something like next script
``` javascript
$S{ 
var pageNumber = getFieldByKeyField(
   "tableofcontents",
   "Page number", 
   "Content Key", 
   "$D{tableofcontents.Content Key}"
);
if ("$D{tableofcontents.Content Key}" == "index") pageNumber = parseInt(pageNumber)+1;
pageNumber;
} 
```

**Comment by liufeijin** [comment]
Hi fralx
Use your method , i got it.
But have a question that before TOC page are fixed so we can add a number for index page, once the TOC is place the last page , before pages include databand  we will don't know which number to be added.
if can get the last databand end page number , shall be easy to add 1. but now i know how to get the end page number of last page(or last databand)

**Comment by fralx** [comment]
I think, I have understand what you need :) I have to emit event when the report engine get the page for render and when it finished render they will be emitted only once per page. I think this also will help you to solve the previous problem with TOC

**Comment by liufeijin** [comment]
> I think, I have understand what you need :) I have to emit event when the report engine get the page for render and when it finished render they will be emitted only once per page. I think this also will help you to solve the previous problem with TOC

:) sorry for my poor English. 
I think  if it is better that  emit a signal for  page start , page finish , databand start and databand finish?

**Comment by fralx** [comment]
Sorry, I haven't cleary understood what do you mean. Do you want to say that bands also should emit signals when the band is rendered in first time and last time?

**Comment by liufeijin** [comment]
yes

**Comment by fralx** [comment]
For bands it is not easy to do,  sometime I don't know if band is rendered in the last time.

**Comment by liufeijin** [comment]
OK. Noted with thanks!
:)

**Comment by fralx** [comment]
I have remembered that the page already has the signals beforeFirstPageRendered and afterLastPageRendered you can try to use them

**Comment by liufeijin** [comment]
Many thanks!
I don't know you have added it as i didn't see the description of it.
Thanks again1
