### ISSUE TITLE
numberFormat question

### ISSUE THREAD

**Issue by liufeijin** [fralx/LimeReport#157]
Hi fralx
Cloud you help to explain how to use the numberFormat ? 
I want  data to  some format Exa:

123.23      ------>   123.230
23.123    -------->    23.123
345.1256 -------->  345.126

anther format requirement      34.5  ----> 0034.500
best regards,
jeff

**Comment by fralx** [comment]
numberFormat is just a wrapper around QString :: number (). For the first task, you can use numberFormat (value, 'f', 3), another task cannot be solved with the help of numberFormat ()

**Comment by liufeijin** [comment]
Many thanks!
