### ISSUE TITLE
Can we get any row data of tableofcontents ?

### ISSUE THREAD

**Issue by liufeijin** [fralx/LimeReport#158]
Now we can get the row data which by below script  
var PageNo=getFieldByKeyField(
   "tableofcontents",
   "Page number", 
   "Content Key", 
   "$D{tableofcontents.Content Key}"
   );
Can we get any row in tableofcontents as don't know the  Content Key of the row?
Exa the third or 15th row  .
best regards,
jeff

**Comment by fralx** [comment]
I will think about it :)

**Comment by liufeijin** [comment]
if we can get the data information of any row then   we can get page range of any index easy in script.
Exa:
A                                                          1  --- 44(B start page number-1)
B                                                           45----68(C Start page number -1)
C                                                          69------
.
.
.
:)

**Comment by fralx** [comment]
I have added getFieldByRowIndex() in the new feature branch "field_by_rowIndex"

**Comment by fralx** [comment]
I have merged it to develop :)

**Comment by liufeijin** [comment]
hi
i try to build it and found a error
![tim 20190219085307](https://user-images.githubusercontent.com/19425403/52982974-da270200-3423-11e9-8658-1aaa54b9b09d.png)

**Comment by fralx** [comment]
Sorry, I have forgotten to push changes :)

**Comment by liufeijin** [comment]
Hi Fralx
The build problem is gone . But i use it in script as below:
PageNo=getFieldByRowIndex("$D{tableofcontents.Page number}","3")

i got the result is "undefined" 
i want to get the Page number of 3 row in tableofcontens.

**Comment by fralx** [comment]
Hi!
You have to use PageNo=getFieldByRowIndex("tableofcontents.Page number","3")

**Comment by liufeijin** [comment]
：） yes , now i got it as per your explanation.
Many thanks for your work!
 this to be closed.

**Comment by fralx** [comment]
Look $D{tableofcontents.Page number} is the same getField("tableofcontents.Page number") it reruns the value

**Comment by liufeijin** [comment]
> Look $D{tableofcontents.Page number} is the same getField("tableofcontents.Page number") it return the value

ok。 Noted。
Thank you！
