### ISSUE TITLE
Find the page number of a value in databrand or subdetailbrand?

### ISSUE THREAD

**Issue by liufeijin** [fralx/LimeReport#160]
Normally , we put some values from a database fields  in a databrand or a subdetailbrand 
 
when i take a value for   example , normally i will put "*"  mark for this value and give the reference page number of the value in report.

I think it is will be crazed function requirement and will be not easy. 
I just raise this as a   wish.
Best regards,
jeff

**Comment by fralx** [comment]
I think I can add a function that will put a bookmark to band or subdetailband and it will be possible to search page number by this bookmark.

**Comment by liufeijin** [comment]
your means that when pass the specially value to databand or subdetailband for Rendering will put a bookmark together ?
Seems it is a way, but i have question that how does user to tell Lime which TextItem and what value will be put the bookmark?
Normally , in a databand or subdetailband has many TextItems and the TextItem will be for a datasource field.

**Comment by liufeijin** [comment]
hi fralx
If you complete the bookmark function kindly please make a notice.
( add a field of bookmark in  "tableofcontens" datatable for search it?)

**Comment by fralx** [comment]
I will let you know when finish

**Comment by fralx** [comment]
I have finished you check it :)
I have added two functions addBookmarks(uniqKey, content) and findPageIndexByBookmark(uniqKey);
Here is the sample 
[findPageByBookmark.lrxml.zip](https://github.com/fralx/LimeReport/files/2937930/findPageByBookmark.lrxml.zip)

**Comment by liufeijin** [comment]
Hi fralx
I can't get the correction page by 
addBookmark(   getField("Trim.Sounding")    ,""   );
it is show -1 always . 
So  I have a tried that just add a bookmark
TrimTable_DataBand40.afterRender.connect(kk)
function kk()
{
   addBookmark("1","");
}

set a textitem as :
ALFKI = $S{findPageIndexByBookmark("1")}

but just got ALFKI=-1

Cloud you have a look on it?
Thanks.

**Comment by fralx** [comment]
Hi.
Do you use findPageIndexByBookmark() at the TOC page?
You have to set fillInSecondPass=true in the TextItem where you use findPageIndexByBookmark()
Also when you use addBookmark you have to set the unique key as the parameter that will be found by 
findPageIndexByBookmark.

**Comment by liufeijin** [comment]
Hi fralx
Many thanks for your explanation.
I didn't use it in TOC page.
After selected  the fillInSecondPass , I got the right result.
But there is an other problem , seems it just for databand but not working for SubDetailBand.
I have tried as below script.



![1](https://user-images.githubusercontent.com/19425403/54071720-c399fb00-42ab-11e9-99d2-976f0a87021e.png)
Cloud you add it for subdetailBand also?
Thank again!
jeff

**Comment by fralx** [comment]
I have checked and for me, everything works as expected.
[Here is the example it works in the demo_r1](https://github.com/fralx/LimeReport/files/2948514/findPageByBookmark.lrxml.zip)

**Comment by fralx** [comment]
Does the function return wrong result or -1?

**Comment by liufeijin** [comment]
> Does the function return wrong result or -1?

Hi fralx
I got the problem that the fiield in database is real type. I use wrong == formula .
After changing the formula.  I got the correct result.
Many thanks for your great work!
jeff
