### ISSUE TITLE
Ability to create a table inside a band

### ISSUE THREAD

**Issue by yanis60** [fralx/LimeReport#162]
Hi,
is it possible to make a table inside a band?

**Comment by fralx** [comment]
Hi!
There is exist a special way to do it using scripts.
Here is an example:
[tableBuilder_demo1.lrxml.zip](https://github.com/fralx/LimeReport/files/2920794/tableBuilder_demo1.lrxml.zip)

**Comment by fralx** [comment]
It is working in the last develop versions

**Comment by liufeijin** [comment]
Hi
How to input data  for  "detail.CustomerID" , i am confused about for field of detail .

**Comment by fralx** [comment]
"detail" is a datasource provided by datasource manager.

**Comment by liufeijin** [comment]
Seems it is same as using datasource directly ,  what it is the difference between tableBuilder.buildTable and directly using by datasource manager.

**Comment by fralx** [comment]
TableBuilder can create a table without a data band. The usual way is using a data band to build a table, but in this case, you can create a table right on a page or on a data band connected to another data source
