### ISSUE TITLE
Wrong font attributes used when exported to PDF

### ISSUE THREAD

**Issue by fabrice-martinez** [fralx/LimeReport#163]
I think I have found a small bug when testing the develop branch of LimeReport.
(I have not tested that the same problem happens in the master branch)

Here's what happens:

I have a report which prints a table.
The table has a header (column names) made of TextItems linked in a horizontal layout, using the font "Liberations Sans" in bold letters.
Follows rows of data, made of TextItems linked in a horizontal layout, using the font "Liberation Sans Narrow", in normal letters (not bold).
![image](https://user-images.githubusercontent.com/503579/53740790-462e4f00-3e95-11e9-9b16-9f98d5870677.png)

In the print preview, the table looks fine.
Also when printed, the table looks fine.
![image](https://user-images.githubusercontent.com/503579/53740949-a02f1480-3e95-11e9-9e1f-ed3b7e22f6aa.png)

However when exported to PDF, all items become bold:
![image](https://user-images.githubusercontent.com/503579/53741035-cb196880-3e95-11e9-96b7-aaeaedb463b9.png)

I have done further checks and the attributes "bold", "italics" & "underline" are completely ignored in all TextItems and the attributes of the very first TextItem (N°) are used instead.

**Comment by fralx** [comment]
Hi, I can not reproduce the problem.  
Does this happen in all reports? 
What Qt version do you use?

**Comment by fabrice-martinez** [comment]
I have 3 reports so far and it happens with all 3.
Qt is version 5.12.1 (compiled for x86)
Compiler is MSVC 2017 15.9.7

**Comment by fralx** [comment]
Will it happen if you change the font for example to  "arial"?

**Comment by fabrice-martinez** [comment]
If I change the font to Arial the PDF output is correct.
The problem lies specifically with the font "Liberation Sans Narrow" and it not a problem with LimeReport.
I didn't think fonts could be buggy too!
Basically I've changed all fields to "Noto Sans Cond" and all is fine now.

Thanks!
