### ISSUE TITLE
Question: Report as QPixmap / QImage?

### ISSUE THREAD

**Issue by Athesis** [fralx/LimeReport#164]
Hello,

Is there any possibility to get the report as QImage or QPixmap? I tried rendering the PreviewWidget on QPixmap, this worked, but I didn't archive an satisfying result this way with next to no control about the position.

I would appreciate your help, Thank you :)!

**Comment by fralx** [comment]
Hi!
I have made some changes and now you can do something like this:
```
QGraphicsScene* preview = report->createPreviewScene();
QImage img(preview->width(), preview->height(), QImage::Format_RGB32);
QPainter painter(&img);
preview->render(&painter);
```

**Comment by Athesis** [comment]
Works great, Thanks!

**Comment by liufeijin** [comment]
Hi
This  remind me that it is possible to make report as TIFF format?
TIFF picture format can contain many page in a TIFF file.
TIFF can be viewed on any computer and mobiles.
Best regards,
jeff

**Comment by Athesis** [comment]
In this case QImageWriter should do the trick for you ;)

**Comment by liufeijin** [comment]
> In this case QImageWriter should do the trick for you ;)

Hi Athesis
Many thanks for your tips.
I seeked the QImageWriter in QT forum and didn't  get the details of TIFF multi-page write description.
I can't make progress on TIFF still.
best regards,
jeff

**Comment by Athesis** [comment]
Qt isn't capable of writing Multipage-TIFF so far I know

**Comment by liufeijin** [comment]
> Qt isn't capable of writing Multipage-TIFF so far I know

hi  
i found some links about tiff lib for your reference.
https://github.com/jkriege2/TinyTIFF
https://github.com/hunter-packages/tiff/tree/hunter-4.0.2/libtiff
https://github.com/kornholi/sptw
https://github.com/libvips/libvips

but i don't to check if it has multipage-tiff.

**Comment by liufeijin** [comment]
https://github.com/jkriege2/TinyTIFF   this one seem can write multipage-tiff
