### ISSUE TITLE
\n in textEdit not working

### ISSUE THREAD

**Issue by yanis60** [fralx/LimeReport#167]
Hi,

Can you please make a textEdit to be able to render the LF and CR characters, it would be nice to create for example a form ;)

Thank you

**Comment by fralx** [comment]
Hi!
Maybe i, not clearly understood what do you mean, but you needn't type '\n' in the text just press enter it will create a new string and it will be rendered as is.

**Comment by yanis60** [comment]
Hi,
Yes it works with Enter Button, but when rendering the report, the text shows in one line and not as i expect.

**Comment by fralx** [comment]
Do you use allowHtml in the TextItem?

**Comment by yanis60** [comment]
Ok i got it now, i use html code that why it doesn't jump to a new line so i should add `<br>` to do it.

And without html code, it also work ;)
