### ISSUE TITLE
Subtotal for  row data

### ISSUE THREAD

**Issue by liufeijin** [fralx/LimeReport#168]
Hi Fralx
Get subtotal for col data we can use $S{SUM($D{pipecapacity.P1},"DataBand1")}
How to get the subtotal for each row data as below?
![1](https://user-images.githubusercontent.com/19425403/55071854-a72bfa00-50c4-11e9-80ba-81e09472b1ea.png)

**Comment by fralx** [comment]
Hi!
Just calculate it in the subtotals $S{$D{DS.Field1}+$D{DS.Field2}+$D{DS.Field3} }

**Comment by liufeijin** [comment]
Fralx
Many thanks for your instruction.
The data type in my database is string . 
I use $S{Double.parseDouble($D{pipecapacity.P1})+Double.parseDouble($D{pipecapacity.P2})+Double.parseDouble($D{pipecapacity.P3}) }
but can't transfer string to double .

**Comment by fralx** [comment]
You can use parceFloat()
$S{parceFloat($D{pipecapacity.P1})+parceFloat($D{pipecapacity.P2})+parceFloat($D{pipecapacity.P3})}

**Comment by liufeijin** [comment]
Hi Fralx
As per your instruction , i get it.
Many thanks!!!
