### ISSUE TITLE
How to change the Datasources connection and variables in my app

### ISSUE THREAD

**Issue by liufeijin** [fralx/LimeReport#169]
Hi fralx
I use Lime Report Designer to make report file   "test.lrxml"  with datasources define and variables as below:
![1](https://user-images.githubusercontent.com/19425403/55097047-03f3d880-50f6-11e9-8b03-6900bdae7892.png)
![2](https://user-images.githubusercontent.com/19425403/55097055-08b88c80-50f6-11e9-92b6-43b237f4ab03.png)

I checked your demo_r2 and found the code sample 👍 ::
m_report.loadFromFile to load  the "test.lrxml" file.

But i don't know how to change the datasources connecting and variables  define in "test.lrxml" file  in my app by code .
Cloud you give me some instruction or code sample?
Best regards,

**Comment by fralx** [comment]
For changing variables you can use report->datamanager().setVariable(QString name, QVariant value);
If the variable found in the report that it will be changed else it will be added. The connection's settings are not accessible from code but you can use variables in the connection settings

**Comment by liufeijin** [comment]
Hi Fralx
 I got it as per your instruction.
BTY, I note there are  report.dataManager()->dataSource();
                         report.dataManager()->setDefaultDatabasePath()
What are it's function?

**Comment by fralx** [comment]
This function set a path where limereport will search database files by default (works only for SQLite)

**Comment by liufeijin** [comment]
Many thanks!!!
