### ISSUE TITLE
Does it possible make a static data table in lrxml file? 

### ISSUE THREAD

**Issue by liufeijin** [fralx/LimeReport#170]
Sometimes i want a table of 2 or 3 cols with 20 -40rows data store in lrxml for a report.
It is independent on external data source .
Seems it is can't get this function.
Now i use a lot of variable to store . If has a data embed table in lrxml will be best.

**Comment by liufeijin** [comment]
I try 
create table teet(w text,w2 text);
insert into teet(w,w2) values("s","sd") 
in the data source under a connection,the first row seems is ok . but there is no data.

**Comment by fralx** [comment]
Hi! I will think about it when i have enough free time ;)

**Comment by liufeijin** [comment]
Hi Fralx
It is a good news for me that you will add that function .
I think LimeReport will be a great tool for report, it is not only a report tool under app code control but also a alone report tool.
Just with a database file then can generate a good report.
Thanks again for your hard work!

**Comment by fralx** [comment]
Hi!
I have made new CSV data source you can use it to store table data in the report.

**Comment by liufeijin** [comment]
Hi, fralx
Many thanks!
I will try it!

**Comment by liufeijin** [comment]
Wow.
Great！ It works fine.
I think you can improve it that read a csv file, then the data source is not only database(sqlite, mysql.....) but also csv file . 
It just is a extend image not a function require when i test to creat csv data.
Many thanks again!

**Comment by liufeijin** [comment]
If use read csv or excel file directly as data source will be more better.
Now, i use other tool change csv.excel file to sqlite3 data file.
