### ISSUE TITLE
Image item variable problem

### ISSUE THREAD

**Issue by liufeijin** [fralx/LimeReport#171]
Hi Fralx
For showing a picture by a image item.
When use variable to set the picture source ,maybe there is a bug.
1: set a full picture path to a variable , can show picture normal.
2: when set a path to a variable "PhotoPath" , then join the "PhotoPath" and picture name to anther variable "Orignal2" . set image item picture source with "Orignal2",can't show the picture.
![9](https://user-images.githubusercontent.com/19425403/55313304-078eb300-549a-11e9-97e1-1d93f8bda42a.png)

Cloud you have a look?

**Comment by fralx** [comment]
Hi!
This is not a bug, the matter of fact is that variable can't contain the expression in all cases. Sometimes it is possible, for example in a TextItem it will work because it uses a more complicated method for getting variable value but in the ImageItem it won't work

**Comment by liufeijin** [comment]
o. get it.
For database connection is ok also.
Anyway , use the full path is ok. 
Many thanks !

**Comment by fralx** [comment]
Hi. I have changed the resourcePath processing, from now you can use variables and data fields in this property.

**Comment by liufeijin** [comment]
Hi,Fralx
It is good news for user, i think.
I will try it and report to you.
Many thanks !

**Comment by liufeijin** [comment]
Hi,Fralx
No effect , i use the newest dev branch. 
![TIM截图20190429174914](https://user-images.githubusercontent.com/19425403/56888767-62bac200-6aa7-11e9-906c-b0094d58cba0.png)

**Comment by fralx** [comment]
I have changed the resourcePath processing, not the variable processing  :)
You can use $V{PhotoPath}\V19015T2.jpg in the resourcePath

**Comment by liufeijin** [comment]
Hi,fralx
use resourcepath is no effect also.
![1](https://user-images.githubusercontent.com/19425403/56894996-2e043600-6aba-11e9-841b-a69d29d7906f.png)
![2](https://user-images.githubusercontent.com/19425403/56895000-32305380-6aba-11e9-99b5-cdbee5d7aa55.png)

**Comment by fralx** [comment]
It is very strange 
for me it is works as expected ![resourcePath](https://user-images.githubusercontent.com/14914730/56907040-2473d180-6aac-11e9-9662-18ccb8245fc1.png)

**Comment by liufeijin** [comment]
Hi fralx
I found the problem that if the path contains blank space. 
Maybe your code doesn't treat the path type .

**Comment by fralx** [comment]
I have tested it and got the next result
![resourcePath1](https://user-images.githubusercontent.com/14914730/56947822-f5ef0880-6b36-11e9-9f8a-94e5f1a89d87.png)

**Comment by liufeijin** [comment]
Yes， now, my file is ok also.
I don't know why it no effect first time.
