### ISSUE TITLE
error when use varialbles in script 

### ISSUE THREAD

**Issue by liufeijin** [fralx/LimeReport#172]
Hi Fralx
I want use a varialble in script but get error
Cloud you help to have a look?
![variables](https://user-images.githubusercontent.com/19425403/55489143-f09bbc80-5663-11e9-9533-e57ca5bb3c74.png)
if use "4210" it will be ok
![1](https://user-images.githubusercontent.com/19425403/55489173-fdb8ab80-5663-11e9-9e49-b8434855ff7c.png)

**Comment by fralx** [comment]
Hi!
If you want to get variable in the script you have to use getVariable(QString variableName) function instead $V{variableName}

**Comment by liufeijin** [comment]
Hi Fralx
It works fine now, so i close this.
Many thanks!
