### ISSUE TITLE
Report header ,page header 

### ISSUE THREAD

**Issue by liufeijin** [fralx/LimeReport#173]
Hi Fralx
Could you explain what is the difference between report header and page header?
Other one is the tear-off band and band.
Thanks.

**Comment by fralx** [comment]
Report header is printed only once at the beginning of the report. Page header is printed on the all report's pages. Tear-off band is printed only once at the end of a report in the bottom part of the page.

**Comment by liufeijin** [comment]
Hi fralx
Many thanks!!!!
