### ISSUE TITLE
report view random crash 

### ISSUE THREAD

**Issue by liufeijin** [fralx/LimeReport#175]
Hi fralx
I noted when ctr+p to get report view , sometims report view will crashed and the LRDesigner will colse also.
If the report has many pages,  when i click the slider and move it from bottom to top , it will crashed random. 
But move it from top to bottom never crashed.

![1](https://user-images.githubusercontent.com/19425403/55887788-c193c680-5be0-11e9-899c-a545c27c50ee.png)

**Comment by fralx** [comment]
Hi. I have fixed the scrolling crash. But Ctl+p i can't reproduce. Could you get me more information about how it happens, maybe there exist special conditions or something else that can help me to reproduce the problem?

**Comment by liufeijin** [comment]
Hi. Fralx
Maybe my description is not clearly.
Only scrolling crash. 
Ctr+p is for generation the report view in LRDesigner, it doesn't effect crash.
I will try your newest update.
Many thanks!

**Comment by liufeijin** [comment]
Hi fralx
The crash problem is fixed.
I have tried many times never crashed.
Many thanks!
