### ISSUE TITLE
PDF file size is very big

### ISSUE THREAD

**Issue by liufeijin** [fralx/LimeReport#176]
Hi fralx
I noted that the pdf file saved by lrreport is very big 94 pages around 4.5m.
I want to change to smaller size file  as sample  .
But i can't find the QPdfWriter::setResolution in LRreport project.
Maybe you use other way to setting the resolution of pdf .
Cloud you point it that the setting for control pdf file resolution ?

**Comment by fralx** [comment]
Hi!
You can just create PDF printer and print reports via it.
QPrinter printer;
printer.setOutputFileName(fileName);
printer.setOutputFormat(QPrinter::PdfFormat); 
printer.setResolution(WhatYouNeed);
report->printReport(printer)

**Comment by liufeijin** [comment]
Ok！
Many thanks for your help!

**Comment by liufeijin** [comment]
> Hi!
> You can just create PDF printer and print reports via it.
> 
> ```
> QPrinter printer;
> printer.setOutputFileName(fileName);
> printer.setOutputFormat(QPrinter::PdfFormat); 
> printer.setResolution(WhatYouNeed);
> report->printReport(printer)```
> ```

Hi Fralx
I have a try use below codes like your
 printer.setOutputFormat(QPrinter::PdfFormat);
    printer.setPageSize(QPagedPaintDevice::A4);
    printer.setResolution(300);
    printer.setOutputFileName(sd.fileName());
but the size of paf will be same 4.2M when setResolution(300) setResolution(100) setResolution(50)
seems the setResolution no effect。

**Comment by fralx** [comment]
Look, in my opinion,  as the pdf format is vector format in the case when it exported from limereport, the print resolution doesn't make sense :). Right me if i wrong.

**Comment by liufeijin** [comment]
Noted.
Many thanks!
