### ISSUE TITLE
The newest ver of master build error

### ISSUE THREAD

**Issue by liufeijin** [fralx/LimeReport#177]
Hi fralx
 I download the newest branch of master.
but got the error:
Project MESSAGE: TOP_BUILD_DIR:
Project MESSAGE: Release
Project MESSAGE: uitools
Project MESSAGE: TOP_BUILD_DIR:
Project MESSAGE: Release
Project MESSAGE: uitools
Project MESSAGE: TOP_BUILD_DIR:
Project MESSAGE: Release
Project MESSAGE: uitools
Project MESSAGE: TOP_BUILD_DIR:
Project MESSAGE: Release
Project MESSAGE: uitools
Project MESSAGE: TOP_BUILD_DIR:
Project MESSAGE: Release
Project MESSAGE: uitools
Project MESSAGE: TOP_BUILD_DIR:
Project MESSAGE: Release
Project MESSAGE: uitools
Project MESSAGE: zint
Project ERROR: Unknown module(s) in QT: script
Project ERROR: Unknown module(s) in QT: script
Project ERROR: Unknown module(s) in QT: script
Project ERROR: Unknown module(s) in QT: script
Project ERROR: Unknown module(s) in QT: script

Project MESSAGE: TOP_BUILD_DIR:
Project MESSAGE: Release
Project MESSAGE: uitools
18:01:14: 进程"C:\Qt\Qt5.12.2\5.12.2\msvc2017_64\bin\qmake.exe"正常退出。
18:01:14: 正在启动 "D:\LimeReport\msvc_make.bat" -f D:/build-limereport-Desktop_Qt_5_12_2_MSVC2017_64bit-Release/Makefile qmake_all

D:\build-limereport-Desktop_Qt_5_12_2_MSVC2017_64bit-Release>chcp 65001 
Active code page: 65001

D:\build-limereport-Desktop_Qt_5_12_2_MSVC2017_64bit-Release>C:/Qt/Qt5.12.2/Tools/QtCreator/bin/jom.exe -f D:/build-limereport-Desktop_Qt_5_12_2_MSVC2017_64bit-Release/Makefile qmake_all 

jom 1.1.2 - empower your cores

	cd 3rdparty\ && C:\Qt\Qt5.12.2\5.12.2\msvc2017_64\bin\qmake.exe -o Makefile D:\LimeReport\3rdparty\3rdparty.pro -spec win32-msvc "CONFIG+=qtquickcompiler"
Project MESSAGE: TOP_BUILD_DIR:
Project MESSAGE: Release
Project MESSAGE: uitools
Project ERROR: Unknown module(s) in QT: script
jom: D:\build-limereport-Desktop_Qt_5_12_2_MSVC2017_64bit-Release\Makefile [sub-3rdparty-qmake_all] Error 3
18:01:14: 进程"D:\LimeReport\msvc_make.bat"退出，退出代码 2 。
Error while building/deploying project limereport (kit: Desktop Qt 5.12.2 MSVC2017 64bit)
The kit Desktop Qt 5.12.2 MSVC2017 64bit has configuration issues which might be the root cause for this problem.
When executing step "qmake"
18:01:14: Elapsed time: 00:01.

**Comment by liufeijin** [comment]
Develop branch is ok

**Comment by fralx** [comment]
The master branch uses QtScript module that is deprecated in Qt 5.12. If you want to build the master branch check if the QtScript module is installed.

**Comment by liufeijin** [comment]
Noted.
Many thanks!
