### ISSUE TITLE
Wrong position of a tear-off band after edit

### ISSUE THREAD

**Issue by yanis60** [fralx/LimeReport#179]
Hi,
When i preview a report and try to edit it and after editing, the tear-off band is not positioned on his old position (in footer).
it works fine when previewing the report.
See this picture for more detail.

please fix it ;)
![Capture](https://user-images.githubusercontent.com/30592254/56081776-5d0b7e00-5e11-11e9-8811-42640b002823.PNG)

**Comment by fralx** [comment]
I have fixed the problem, check it please.

**Comment by yanis60** [comment]
I confirm you it fixed ;) thank you and keep going
