### ISSUE TITLE
Loading image from qrc file

### ISSUE THREAD

**Issue by yanis60** [fralx/LimeReport#181]
Hi,

Can i load an image from a qrc file that can be found on my project??

if yes, can i just paste the qrc path??

Thanks ;)

**Comment by fralx** [comment]
Hi, i have missed your question. Do you found solution ?

**Comment by yanis60** [comment]
yes, i realised that i can embed an image inside a report ;)

thanks

**Comment by fralx** [comment]
You also can use resourcePath property to get image from resources or from HDD

**Comment by yanis60** [comment]
how to get it from qrc file?? using qrc:/??

**Comment by fralx** [comment]
Yes
