### ISSUE TITLE
Adding ability to stretch a word

### ISSUE THREAD

**Issue by yanis60** [fralx/LimeReport#182]
Hi,

Can you please add a useful feature that stretch a word.

Example : text -> t   e   x   t

Thanks

**Comment by fralx** [comment]
Hi! I have added fontLetterSpacing property to TextItem.

**Comment by yanis60** [comment]
Thank you so muuuch <3.

Please one more think :)

I have a report that has two table placed horizontally in one line, here i can't do two databand in one line so can you please add a possibility to place two databand in one line ??

Thanks

**Comment by liufeijin** [comment]
> Hi,
> 
> Can you please add a useful feature that stretch a word.
> 
> Example : text -> t e x t
> 
> Thanks
I don't understand what is it for?

**Comment by yanis60** [comment]
This new feature allow us to make spaces between letters of a word.

**Comment by fralx** [comment]
@yanis60 
> I have a report that has two table placed horizontally in one line, here i can't do two databand in one line so can you please add a possibility to place two databand in one line ??

You can use approach described https://github.com/fralx/LimeReport/issues/162

**Comment by yanis60** [comment]
I did the approch you mentionned and it worked perfectly thank you ;)
