### ISSUE TITLE
Corrupted saved file from preview

### ISSUE THREAD

**Issue by yanis60** [fralx/LimeReport#186]
Hi,
When i save a report from a preview mode using floppy disk button it creates file but one i open it using designer software, he can't read it, it shows me a lot tabs at the buttom and empty report.

Can you please fix it :)?

**Comment by fralx** [comment]
Hi!
The file saved from preview doesn't intend 
for opening by report designer :) 
It should be a special viewer but i have no time ro write it

**Comment by yanis60** [comment]
ok i got it now.

So we'll wait for this new viewer

thanks

**Comment by fralx** [comment]
Hi!
I have added the ability to open saved preview pages.
I have added the IPreparedPages interface and  ReportEngine now has preparedPages() method that returns it. How to use it : 
For open saved pages you have to do next.
        report->preparedPages()->loadFromFile(file_name);
        report->showPreparedPages(); 
Also you can generate pages and save it
       report->prepareReportPages();
       report->preparedPages()->saveToFile(file_name);
After use prepared pages shold be cleared using 
      report->preparedPages()->clear(); 
becouse they take the memory

**Comment by yanis60** [comment]
hi,

ok thanks i'll try it ;)
