### ISSUE TITLE
Detail databand not visible with Zoom at: 10,20,30,50,90

### ISSUE THREAD

**Issue by alonsomm2000** [fralx/LimeReport#188]
Greeting every body. 

I like to report a bug in Develop version 1.4.128 of LimeReport when you change Zoom to: 10,20,30,50,90% the text in Detail Band disappears when Font is: "Arial [TMC ]" 10  , but that does not happen in Production version or when Font is changed to: "Arial" 10

Regards, 
             Luis Murillo.

**Comment by fralx** [comment]
Hi!
Could you send me the Arial [TMC] font? I will try to fix the problem. 
But i think it is the Arial [TMC] font problem because all fonts that i using in my reports works as expected :)

**Comment by alonsomm2000** [comment]
There you have them, I do not understand where is Limereport Designer grabbing that Font name, I do not have any font with that name, I just copy all my Windows fonts and install them in my Kubuntu 18.04 machine, Arial font works fine in LibreOffice and does not show any Arial [TMC ] in the font selector as you can see in the picture below:
![LibreOffice-Fonts](https://user-images.githubusercontent.com/15023328/57569935-8e984a80-73b9-11e9-928f-b67d480d7bf5.png)

This is what LimeReport Designer shows in Linux:
![Limereport-Designer-Fonts-Linux](https://user-images.githubusercontent.com/15023328/57570015-ade3a780-73ba-11e9-84b6-1a507b08381b.jpeg)

And this is what LimeReport Designer shows in Windows:
![Limereport designer fonts in Windows](https://user-images.githubusercontent.com/15023328/57570025-cc49a300-73ba-11e9-8a8b-6870a8fa5ac5.jpg)

So the question would be: why is LimeReport Designer adding [TMC ] at end of the Font name and what does it mean?

[Arial-Fonts.zip](https://github.com/fralx/LimeReport/files/3169031/Arial-Fonts.zip)

Regards,
           Luis Murillo
