### ISSUE TITLE
How can i change Limereport designer language

### ISSUE THREAD

**Issue by alonsomm2000** [fralx/LimeReport#189]
Hi, every body.

Can any body please tell me how can I change Limereport Designer language to Spanish when using Limereport.dll with other project?

Regards,
           Luis Murillo.

**Comment by fralx** [comment]
Hi! 
Something like this:
```C++
QApplication a(argc, argv);
....
QTranslator limeReportTranslator;
QString translationPath = QApplication::applicationDirPath();
    translationPath.append("/translations");
limeReportTranslator.load("limereport_es", translationPath);
a.installTranslator(&limeReportTranslator);
```

**Comment by alonsomm2000** [comment]
This is much simpler and can be applied to mainwindow.cpp to change language at runtime:

QTranslator Translator;

QString CurLang=QLocale::system().name().left(2); // Get current system language first 2 letters

// If sistema language is not English try to load translation from resources
if (CurLang!="en")
{
        QString LangFile=QString("://limereport_%1.qm").arg(CurLang);
        if (Translator.load(LangFile)) QApplication::installTranslator(&Translator); else qDebug()<<"Could not load language from resource.";
}

Note: You must include translation file for your language ej: limereport_es.qm in your Qt project resources for it to work correctly.

Regards,
              Luis Murillo.
