### ISSUE TITLE
Hangs on exit

### ISSUE THREAD

**Issue by deep125** [fralx/LimeReport#192]
ver 1.4.131
Windows 64 
After exit application. Hang up in 
limereport\base\lrsingleton.h:52

**Comment by fralx** [comment]
I can't reproduce the problem. 
Does it happen on demo_r1 or demo_r2 or designer? 
Could you send me a simple example?

**Comment by deep125** [comment]
Yes on demo_r1 and semo_r2
qt 5.12.3
vs 2017 15.9.12
limereport-Desktop_Qt_5_12_3_MSVC2017_64bit-Debug
![stek](https://user-images.githubusercontent.com/7235374/58570811-45614b00-8241-11e9-9faf-48bbdcb15640.png)

**Comment by deep125** [comment]
if comment  limereport\base\lrsingleton.h:52  
all ok

**Comment by fralx** [comment]
I have tested on Win7 64 MSVC 2017 64 Qt 5.12.2 and don't get the hangs.

**Comment by fralx** [comment]
Do you have hangs when you run the program not under the debugger?

**Comment by deep125** [comment]
The problem occurs when the QML debugger is enabled. This is not your mistake. This issue can be closed.
