### ISSUE TITLE
Translations not updating

### ISSUE THREAD

**Issue by alonsomm2000** [fralx/LimeReport#193]
Greetings every body, I would like to error a bug when updating translations using:
Qt Creator, Tools, External, Linguist, Update Translations ( lupdate )

You get errors on all translations:
Updating '"/home/alonso/QT-Projects/LimeReport-develop-29-May-19/translations/limereport_es_ES.ts"'...
    Found 693 source text(s) (693 new and 0 already existing)

Cannot create /home/alonso/QT-Projects/LimeReport-develop-29-May-19/limereport/"/home/alonso/QT-Projects/LimeReport-develop-29-May-19/translations/limereport_es_ES.ts": No such file or directory

Regards, 
         Luis Murlllo.

**Comment by fralx** [comment]
Can i close the issue i see that you found a solution?

**Comment by alonsomm2000** [comment]
Yes you may close it but please update git version of limereport.pro and spanish translation, I already fix the problem and update translation.

I changed in /limereport/limereport.pro
Line 115: 
LANGUAGES = ru es_ES ar fr zh pl
to
LANGUAGES = ru es ar fr zh pl

And line: 122 
 TRANSLATIONS = $$prependAll(LANGUAGES, \"$$TRANSLATIONS_PATH/limereport_,.ts\")
to
TRANSLATIONS = $$prependAll(LANGUAGES, $$PWD/../translations/limereport_,.ts)

That will fix the error reported, keep translations in one place and make languages suffix uniform!

Corrected file and translations attached.

Regards,
            Luis Murillo.

**Comment by fralx** [comment]
I have changed line 115, but line 122 i left without changes because it generates translation it the subdirectory "translations" in the project directory and it is convenient for me. :)  Why you want to move translations on level up?

**Comment by alonsomm2000** [comment]
Thanks, I also changed line 122 because was giving errors when you try to run Linguist update on the master project and you have already a folder for translations in the master project but you do not have such thing in limereport folder, I noticed in the Develop version from Git that you have copies of the .ts files in limereport folder so I did not know which file I should update when trying to update translations.

Regards, 
         Luis Murillo.

**Comment by alonsomm2000** [comment]
Why don't you create a translations folder inside limereport folder and move all your .ts files to the translations folder and change line 122 from:
TRANSLATIONS = $$prependAll(LANGUAGES, \"$$TRANSLATIONS_PATH/limereport_,.ts\")
To
TRANSLATIONS = $$prependAll(LANGUAGES, $$PWD/translations/limereport_,.ts )

So all the translations can update their translation files without errors in Qt Designer:

![Qt designer lupdate](https://user-images.githubusercontent.com/15023328/58751080-1fad8f00-8457-11e9-9df4-c3e201bd4f21.png)

Thanks.

**Comment by fralx** [comment]
When you run building the project all ts and qm are updated and you needn't run lupdate manually.  I can change line 122 to TRANSLATIONS = $$prependAll(LANGUAGES, $$TRANSLATIONS_PATH/limereport_,.ts) (i just remove \") and it will be the same to $$prependAll(LANGUAGES, $$PWD/translations/limereport_,.ts ) and lupdate will work but lrelease still won't.

**Comment by alonsomm2000** [comment]
When you open main project folder and run:
lupdate   **Runs fine with changes in line 122** 
lrelease   returns error:
**lrelease warning: Met no 'TRANSLATIONS' entry in project file '/home/luis/QT-Projects/LimeReport-develop-1_4_134/limereport.pro'**

It seems to be a bug in Qt look at: https://bugreports.qt.io/browse/QTBUG-48416

But if you open limereport.pro in limereport folder both lupdate and lrelease work fine with my suggested changes!

**Comment by fralx** [comment]
I have changed line 122,  from now you can use qtcreator for updating and creating translations.

**Comment by alonsomm2000** [comment]
Thank you very much Alex, I tested and lupdate from Qt Designer is working correctly now and when you compile the project, it generates the .qm files for every translation automatically, that is very cool, now we need some help from our friends desde:
Argentina (although their main language is Spanish which is already 100% translated, but if they want to update it would be great)
France, Switzerland and Poland

Updating 'translations/limereport_ar.ts'...
    Found 693 source text(s) (53 new and 640 already existing)
Updating 'translations/limereport_fr.ts'...
    Found 693 source text(s) (30 new and 663 already existing)
Updating 'translations/limereport_zh.ts'...
    Found 693 source text(s) (53 new and 640 already existing)
Updating 'translations/limereport_pl.ts'...
    Found 693 source text(s) (142 new and 551 already existing)

Regards
      Luis Murillo

**Comment by fralx** [comment]
The translations are created by users and as limereport constantly evolving the translations can be not fully completed. When i finish the new version (i hope so),  i will ask the peoples who created the translations to complete them.

**Comment by alonsomm2000** [comment]
I know is constantly evolving, that is great, I was just telling you because I notice when ran lupdate that only: Russian and Spanish translations are 100% translated, but you are right they must be updated before any production release.

Regards,
           Luis Murillo.
