### ISSUE TITLE
Spanish translation updated

### ISSUE THREAD

**Issue by alonsomm2000** [fralx/LimeReport#194]
Greetings every body, In thanks for your hard work on Limereport I took some time to translate 100% spanish locale for Limereport, I want to shared it with every body.

Regards,
           Luis Murillo.

[LimeReport-Spanish-Translation-Updated.zip](https://github.com/fralx/LimeReport/files/3233894/LimeReport-Spanish-Translation-Updated.zip)

**Comment by fralx** [comment]
Thanks :)

**Comment by alonsomm2000** [comment]
You welcome!
