### ISSUE TITLE
Unable to change page size on the fly

### ISSUE THREAD

**Issue by alonsomm2000** [fralx/LimeReport#197]
Greetings, I tried your script with some changes, I pass on a variable called HalfPage=1 in order to create half page report:

Reportpage1.beforeRender.connect(before_page1_render);
function before_page1_render(){
if(getVariable("HalfPage")==1) Reportpage1.setItemHeight(139);
}

**But paper seen to be reduced but page header does not show : (   Look:**

![Limereport-page-resize-not-working](https://user-images.githubusercontent.com/15023328/58661184-7a72a980-82e4-11e9-91e8-fefb5bead274.png)

Any Idea how to fix this, I just need to change paper size on the fly to half page (8.5 x 5.5 inches)

Regards,
            Luis Murillo.

_Originally posted by @alonsomm2000 in https://github.com/fralx/LimeReport/issues/166#issuecomment-497468314_

**Comment by fralx** [comment]
Hi. I have fixed the render process. Check it, please.

**Comment by alonsomm2000** [comment]
Thank you very much its, working perfectly now look.

![half-page invoice](https://user-images.githubusercontent.com/15023328/58741930-9ce7ee00-83dc-11e9-9a7d-dabebbed2ebe.png)
