### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Athesis** [fralx/LimeReport#199]
Hi,

I have problems with the license, there are some mismatches. The provided "LICENSE"-File contains just LGPL 2.1. The "COPYING" file Contains LGPL 3 or newer as well as GPL3 
... what is the current valid license model for LimeReport? 

Thankyou!

**Comment by fralx** [comment]
Hi,
I have changed the LICENSE file  :) 
LimeReport is under LGPL v3 license or (at your option) any later version.

**Comment by alonsomm2000** [comment]
> Hi,
> 
> I have problems with the license, there are some mismatches. The provided "LICENSE"-File contains just LGPL 2.1. The "COPYING" file Contains LGPL 3 or newer as well as GPL3
> ... what is the current valid license model for LimeReport?
> 
> Thankyou!

Athesis your request have been fulfilled, can you please close this issue, to reduce pending issues queue?
