### ISSUE TITLE
Adding ruler to designer

### ISSUE THREAD

**Issue by yanis60** [fralx/LimeReport#200]
Hi,
Can you please add ruler to the designer?

Thanks

**Comment by fralx** [comment]
Hi!
I will think about it :)

**Comment by fralx** [comment]
Hi! 
I have added ruler you can check it.

**Comment by yanis60** [comment]
Excellent, thank you so much <3

**Comment by alonsomm2000** [comment]
> Excellent, thank you so much <3

Great feature, look pretty cool, thanks Alex.

Yanis60 can you please close this issue, to reduce pending issues queue!
