### ISSUE TITLE
Databand and groupband overlapping Page footer problem

### ISSUE THREAD

**Issue by alonsomm2000** [fralx/LimeReport#201]
Greetings every body.

I would like to report a bug in Limereport:
When you add a Page footer to a report, data from Databand and Groupband are ignoring Page footer height, so data is writen in page footer area, missing information at the end.

Please take a look at the following image:
![Lime-report-ignoring-page-footer](https://user-images.githubusercontent.com/15023328/59794012-2f213a80-9295-11e9-89b1-1d265f653414.png)

I am using Limereport  1.4.135 Develop version from Github.

**Comment by fralx** [comment]
Thanks, I will check it.

**Comment by fralx** [comment]
If you a little bit increase the page footer will the group band footer be moved to the next page?

**Comment by alonsomm2000** [comment]
No, I increase footer 3 times its original height (1 line) and still is just ignoring Page footer height and overlapping page footer with databand or groupband, look:

![Lime-report-ignoring-page-footer2](https://user-images.githubusercontent.com/15023328/59854864-f20a8600-9330-11e9-9c8a-6e21aafbdd77.png)

I look horrible! : (

**Comment by alonsomm2000** [comment]
I run some more tests and find that the overlapping **only occurs when the report contains group-bands**, this is how it looks **without groupbands**:
![Lime-report-page-footer-ok-without-groupbands](https://user-images.githubusercontent.com/15023328/59856795-d99c6a80-9334-11e9-9391-ac4eb16c82e4.png)

Now with group bands in the report::
![Lime-report-ignoring-page-footer2](https://user-images.githubusercontent.com/15023328/59856914-06e91880-9335-11e9-96f0-003cec48a327.png)

That will help you locate the problem faster. ; )

**Comment by fralx** [comment]
Could you send me your report template? I have tried to reproduce the problem and in my case, all works as expected.

**Comment by alonsomm2000** [comment]
Sure, here it is: 

[Account-Payable.zip](https://github.com/fralx/LimeReport/files/3311689/Account-Payable.zip)

That is my accounts payable report, having troubles!

The data is passed throught QSQLQueryModel!

  QSqlQueryModel *myReportModel=new QSqlQueryModel(nullptr);
            if (LastFilterOQuery.indexOf("ORDER BY clientes.Nombre")==-1) LastFilterOQuery+=" ORDER BY clientes.Nombre, ordersin.Fecha";
            myReportModel->setQuery(LastFilterOQuery);
            report->dataManager()->addModel("datos",myReportModel,true);

**Comment by fralx** [comment]
If the data used in the report is not secret could you export it to SQLite and send to me? 
You can use my email:arin_a@bk.ru.

**Comment by alonsomm2000** [comment]
I just sent you a zip fie with SQLite database containing the data I am using to print in the report, where you should see the bug I am reporting.

Thanks!

**Comment by fralx** [comment]
Hi, I have made some changes. Check it please. I hope the problem is fixed.

**Comment by alonsomm2000** [comment]
Thank you so much, great job, it is working perfectly now on version 1.4.136.
:+1:
