### ISSUE TITLE
hideIfEmpty property request for barcodeItem

### ISSUE THREAD

**Issue by alonsomm2000** [fralx/LimeReport#203]
Greetings, I thing it would be very useful to add hideIfEmpty property to barcodeItems.

Can you please add that feature?

Regards,
         Luis Murillo

**Comment by fralx** [comment]
Hi. Ok

**Comment by fralx** [comment]
I have added hideIfEmpty property to BarcodeItem you can check it.

**Comment by alonsomm2000** [comment]
Hiding if empty works perfectly, thank you very much.

Just one more question, can I change barcodeitem width with using Script?
