### ISSUE TITLE
Changing paper size and ajust the size

### ISSUE THREAD

**Issue by yanis60** [fralx/LimeReport#205]
Hi,
I need to change the paper size when printing or exporting to PDF, the problem is when i change it using QPrinter, it changed it but Qprint cuts the result on 2 pages.

Can you please help me?

**Comment by fralx** [comment]
If I understand you correctly, do You want the page size to decreases as the size of the printed area decreases?

**Comment by yanis60** [comment]
yes for example: from A4 to A5 but not from the report designer, from software.

Qprinter did it but not ajusting the size to the paper size, if there is a solution please let me know.

**Comment by fralx** [comment]
Hi! Did you find a solution?

**Comment by yanis60** [comment]
unfortunatly not yet, i managed to change page size but the content is not ajusted to the newest size

**Comment by fralx** [comment]
It seems like I found a solution I will check it and push if it works

**Comment by fralx** [comment]
I have made changes and push it. From now using printBehavior property you can change printing mode from splitting to scaling

**Comment by yanis60** [comment]
Thank you,

How can i change page format? using Qprinter or other way?

**Comment by yanis60** [comment]
Thank you sooooooo much it works now as i want <3 customers will love it.

**Comment by yanis60** [comment]
Can you please help me in this case??
I would like to change paper size using combobox, i created the items and using qprinter when i print with a selected format from combobox i got this warning : `QPrinter::setPageLayout: Cannot be changed while printer is active` and the format doesn't change.

**Comment by yanis60** [comment]
I finally fixed it lol.
Thanks again and keep going ;)
