### ISSUE TITLE
Suggestion: Add Codacy static code analysis

### ISSUE THREAD

**Issue by escherstair** [fralx/LimeReport#206]
I'm sure the source code of LimeReport project has a great quality, but based on my experience the usage of some tools can help the development.
One of this tools for static ocde analysis is [Codacy](https://www.codacy.com/), which can be used free of charge for [open source projects](https://opensource.codacy.com/).

The integration in github project is quite easy and I did it on [my fork](https://app.codacy.com/project/escherstair/LimeReport/dashboard?bid=13226741).

If the developers think that can be useful they can setup Codacy for this github repo.

**Comment by fralx** [comment]
Hi! Thank you for your suggestion :) I will try it.

**Comment by escherstair** [comment]
If you decided to use Codacy, you can easily add a badge to github repo quite easily, following [these instructions](https://support.codacy.com/hc/en-us/articles/212799365-Badges).

**Comment by fralx** [comment]
Thanks :) I will use it
