### ISSUE TITLE
Shape item for rectangle is squarely corner

### ISSUE THREAD

**Issue by liufeijin** [fralx/LimeReport#207]
I use shape item to draw a rectangle shape, but 4 corners is not squarely
![TIM截图20190627180031](https://user-images.githubusercontent.com/19425403/60257405-f53fdc00-9905-11e9-8cb9-aa7d74b07902.png)
I want the one is as below
![13](https://user-images.githubusercontent.com/19425403/60257425-038df800-9906-11e9-9075-259362f65a4e.png)

Cloud you instruct me how to get it?

**Comment by fralx** [comment]
Hi!
I have fixed ShapeItem you can check it.

**Comment by liufeijin** [comment]
Hi fralx
It is correct now. Many thanks for your great job.
So i close this .
