### ISSUE TITLE
Date format problem 

### ISSUE THREAD

**Issue by liufeijin** [fralx/LimeReport#210]
Hi fralx
i want to get  the string " Jul 11,2019" via $S{dateFormat("2019-07-11","MMM dd,yyyy")} for a text item.
But i got 
![TIM截图20190701200621](https://user-images.githubusercontent.com/19425403/60435396-0ce7cf00-9c3c-11e9-85aa-9211caa867f2.png)  as the OS system locale .
Do we have a way to get Jul 11,2019 on a Chinese OS system?
Sometime we need made English report sometime maybe French report, so for different format type is very useful.
Cloud you give me some instruction?

**Comment by fralx** [comment]
Hi!
I have added "locale" parameter to the dateFormat and dateTimeFormat functions.

**Comment by liufeijin** [comment]
Hi fralx
I have tested , it is perfect！
Many thanks !
