### ISSUE TITLE
pagefooter position 

### ISSUE THREAD

**Issue by liufeijin** [fralx/LimeReport#215]
if there is no page header (even no databand) only put a pagefooter.
Now, the pagefooter will be presend on the top.
![TIM截图20190713223349](https://user-images.githubusercontent.com/19425403/61172952-a9a45800-a5be-11e9-96a3-6f27f85ff832.png)

Suggest the page footer display on the bottom of a page always. Also the page header shall be on the top of a page.
best regards,

**Comment by yanis60** [comment]
use tearoff band instead

**Comment by liufeijin** [comment]
> use tearoff band instead

hi yanis60
use teaoff band is still on the top.
I want the page footer display at bottom in design mode.
![TIM截图20190714081500](https://user-images.githubusercontent.com/19425403/61177796-bdc47580-a60f-11e9-9d29-c577eeaa34fd.png)

**Comment by fralx** [comment]
@liufeijin  Why do you want to use page footer band if you put all other items on the page directly?
In my opinion, it doesn't make sense. The pagefooter band is needed when you using other bands, but in your case, I think you can just put all items directly on the page.

**Comment by liufeijin** [comment]
hi
yes, i put all items on the page directly as it is simply . But page footer shall be needed as  i need mark the page number.
Seems your mean that to be add a data band for all items.  I will try to add a data band

**Comment by fralx** [comment]
Hi.
> Seems your mean that to be add a data band for all items. 

No, I mean that you needn't use the pagefooter band to mark the page by page number.
Just put all items on the page and don't use the bands :)

**Comment by liufeijin** [comment]
Hi fralx
I think the $V(#PAGE) must be put in the page footer   if want count in page number .
I will try put #PAGE in page directly.
Many thanks for your explain.
