### ISSUE TITLE
Minor bugs

### ISSUE THREAD

**Issue by compozitor** [fralx/LimeReport#216]
1. We create a translation, then change the objectName in report page, look at the translation again - in the list of pages there are old data and new ones, but without translation.

2. Only on the first page of the report there is a ruler.

3. Data browser -> Add new datasource -> Check stubdetail -> the CSV tab disappears -> uncheck subdetail -> the CSV tab does not appear, why?

**Comment by fralx** [comment]
I have fixed it. You can check it

**Comment by compozitor** [comment]
Super, thank you!
