### ISSUE TITLE
Set number of copies from code, not dialog

### ISSUE THREAD

**Issue by sanych1by** [fralx/LimeReport#219]
Hello. I using LimeReport for silent print reports, and now I need to print few copies. Even when I set setCopyCount property to QPrinter object (when supportsMultipleCopies() return true), after calling printReport(printer) I got only one copy. Now I using multiple calling of printReport, but this is slow and not correct. How can I set number of copies correct?

**Comment by fralx** [comment]
Hi. 
I have tested. 
As I don know how you creating the QPrinter instance I have used next code to reproduce the problem
``` C++
QPrinter* printer = new QPrinter;
QPrintDialog dialog(printer);
if (dialog.exec()){
    printer->setCopyCount(2);
    report->printReport(printer);
} 
```
I did not set the number of copies in the printer dialog box, but the report was printed in the number of copies that I set in the printer.setCopyCount method.

**Comment by fralx** [comment]
For me, even the next code works as expected
``` C++
QPrinter* printer = new QPrinter;
printer->setPrinterName("HP LaserJet 1018");
printer->setCopyCount(2);
report->printReport(printer);
```

**Comment by sanych1by** [comment]
Sorry, it's my fall. I use system PDF printer for test, and it not work correct with setCopyCount. When I used physical printer it's work perfect.
