### ISSUE TITLE
Add Design Document and a guide to contributing

### ISSUE THREAD

**Issue by HatisEm** [fralx/LimeReport#228]
Hello, fralx!

I've decided to purchase a course on Qt development in C++ and I have a basic understanding of most of the Qt Creator UI and I think I can start contributing to your project (From Arabic translation to little fixes here and there is what I can promise for now)

I hope you can help me help you by writing a well-formatted Design Document since that's the best way I can understand your vision for the project and what you are trying to achieve with it.

As I said, I've just started learning C++ in general but I hope that my Python knowledge would translate to C++ but I think they have a lot of differences starting with how to include libraries. I would appreciate it if you would guide me as I make pull requests and help me understand C++ concepts along the way.

Have a blessed day.

**Comment by fralx** [comment]
Hi. 
To create Pull Request you have to create a fork of limereport then made changes and create pull request :) you can read about it here https://help.github.com/en/articles/creating-a-pull-request-from-a-fork. 
About Design Document the limereport is a rather spontaneous project :)
