### ISSUE TITLE
Image item resourecPath problem 

### ISSUE THREAD

**Issue by liufeijin** [fralx/LimeReport#232]
Hi Fralx
When i use a variables (T2) for a image item resourecPath in Lime Report Designer , the PIC can be show as below:
![1](https://user-images.githubusercontent.com/19425403/67412478-ef2ae500-f5f1-11e9-8097-061e89e7c239.png)
![2](https://user-images.githubusercontent.com/19425403/67412484-f3ef9900-f5f1-11e9-8510-fede84b6ded9.png)

The problem is  when i change the variables T2 to new value in my code , the PIC can't be show.
![34](https://user-images.githubusercontent.com/19425403/67412568-1da8c000-f5f2-11e9-9ddc-a7b0d1d9c498.png)

Cloud you help to  have a look ?

**Comment by fralx** [comment]
Hi!
It's very strange. 
I have checked and for me, all work as expected.

**Comment by liufeijin** [comment]
Hi Fralx
I set T2 in Lime Report Designer and ctr+p the PIC shall show
![TIM截图20191028204134](https://user-images.githubusercontent.com/19425403/67679239-9c6f7580-f9c3-11e9-9d99-b371644297fb.png)
I change it in my programe , PIC shall not show.
![TIM截图20191028203459](https://user-images.githubusercontent.com/19425403/67679273-b0b37280-f9c3-11e9-9636-7bcf8224c3fa.png)


Formatfile=QString("C:/Users/liu/Desktop/limemv/VST2PCNEN.lrxml");
   report.loadFromFile(Formatfile);
   report.dataManager()->setReportVariable("DataConnection",fileinfo.absolutePath()+"/"+vesselInfor.CertNo+"_"+vesselInfor.ShipNameC+".db");
   report.dataManager()->setReportVariable("CertNo",vesselInfor.CertNo);
   report.dataManager()->setReportVariable("T10",fileinfo.absolutePath()+"/"+vesselInfor.CertNo.mid(0,3)+vesselInfor.CertNo.right(3)+"T10.jpg");
   report.dataManager()->setReportVariable("T12",fileinfo.absolutePath()+"/"+vesselInfor.CertNo.mid(0,3)+vesselInfor.CertNo.right(3)+"T12.jpg");
   report.dataManager()->setReportVariable("T2",fileinfo.absolutePath()+"/"+vesselInfor.CertNo.mid(0,3)+vesselInfor.CertNo.right(3)+"T2.jpg");
   qDebug()<<report.dataManager()->variable("T2");
   report.dataManager()->setReportVariable("T9",fileinfo.absolutePath()+"/"+vesselInfor.CertNo.mid(0,3)+vesselInfor.CertNo.right(3)+"T9.jpg");

  // report.printToPDF(sd.fileName());
 //  report.printReport(&printer);
  // report.setShowProgressDialog(true);
   report.previewReport();
   report.deleteLater();

QT5.12.2 WINDOWS10 64

**Comment by fralx** [comment]
I really have no idea why it may happen. I have made a video about how it works for me
[res_path_variable.zip](https://github.com/fralx/LimeReport/files/3780142/res_path_variable.zip)

**Comment by liufeijin** [comment]
Cloud you give me your codes ? i want to try test it  on my computer , if it can't give correct result so shall be my system problem.

**Comment by fralx** [comment]
I simply modified https://github.com/fralx/LimeReport/tree/master/demo_r1 
you also can make the changes as you can see in the video.

**Comment by liufeijin** [comment]
used your code still can't show the PIC , i will have a try on  develop branch.

**Comment by liufeijin** [comment]
wow   It is QT5.12.2 problem, i change to QT5.13.2 , anything is ok
