### ISSUE TITLE
Adding a QPixmap image to a report

### ISSUE THREAD

**Issue by yanis60** [fralx/LimeReport#233]
Hi,
I want to add a qpixmap from my project to a report, can you please show me how?

**Comment by fralx** [comment]
Hi!
Create a report variable for example "Image":
report->dataManager()->setReportVariable("Image",myPixmat.toImage())
then in  ImageItem set "variable" property to variable name"Image". 
I want to draw your attention to the fact that the variable property is initialized 
by the variable name without $V{}

**Comment by yanis60** [comment]
thank you ;)

**Comment by yanis60** [comment]
Thank you so much, it worked perfectly :)

**Comment by khaldoun-ops** [comment]
Hi, 
I can't find 'variable' in ImageItem proprities?
Can u help

**Comment by fralx** [comment]
Hi! If you use the latest master branch it should be there :)
![variable](https://user-images.githubusercontent.com/14914730/82736027-1f289b00-9d2f-11ea-95e9-e76bba8081bd.png)

**Comment by khaldoun-ops** [comment]
Thanks , a lot
