### ISSUE TITLE
Best branch

### ISSUE THREAD

**Issue by yanis60** [fralx/LimeReport#240]
Hi,
-Which is the best branch ?

**Comment by fralx** [comment]
At the moment i think the master branch is best :)

**Comment by yanis60** [comment]
does master branch has the same features like develop branch ?

**Comment by fralx** [comment]
There is only one difference in the develop branch: unfinished exporters :)

**Comment by yanis60** [comment]
that's why exporting in xlsx format makes errors :)

**Comment by fralx** [comment]
Yes :) This task has not been completed yet. 
Only very simple reports can be exported.

**Comment by yanis60** [comment]
ok thank you
