### ISSUE TITLE
Debugging LimeReport

### ISSUE THREAD

**Issue by yanis60** [fralx/LimeReport#245]
Hi,
Can you please help me how can o configure LimeReport lib to be able to debug it?

**Comment by fralx** [comment]
If you build Limereport by the QtCreator you can select release or debug version.

**Comment by yanis60** [comment]
I know that but when i debug my project i'm getting errors.
when i compile limereport in debug mode, where can i make the dll file so that i can debug my project?

**Comment by fralx** [comment]
The debug dll will be placed in the  limereport/build/"Qt version"/win"32|64"/debug/lib folder
