### ISSUE TITLE
image item support  to svg format

### ISSUE THREAD

**Issue by liufeijin** [fralx/LimeReport#246]
fralx
Could you add the svg format support for image item? QT  has the svg module  just add svg in pro file.

**Comment by fralx** [comment]
Hi, svg is not an image as png for example :) And yes, qt has svg support, but it is not enough just add svg to pro file :). But I will think about how to add svg support to ImageItem or maybe to SvgItem.

**Comment by liufeijin** [comment]
Hi fralx
Would you have free time for adding Svgitem?
best regards,

**Comment by fralx** [comment]
Hi @liufeijin! I have added it :) You can test it.

**Comment by liufeijin** [comment]
Hi fralx
Many thank for your great job!
It is great news  LimeReport supports SVG.
I have test it.  There is problem that it hasn't "edit" menu for setting svg file path 

![新建位图图像](https://user-images.githubusercontent.com/19425403/76964172-447ae080-695d-11ea-9608-1abcadd8e3ed.png)

**Comment by fralx** [comment]
Hi @liufeijin! Have done.

**Comment by liufeijin** [comment]
Hi fralx
It is ok now. 
Many thanks for your great job!
