### ISSUE TITLE
QT5.12.6 static build 

### ISSUE THREAD

**Issue by liufeijin** [fralx/LimeReport#247]
hi fralx
i use static QT5.12.6 to build limeReport by set config as below in qmake
![TIM截图20200118223729](https://user-images.githubusercontent.com/19425403/72665423-50245680-3a43-11ea-93ce-1f46bc357681.png)
i got this error 
![TIM截图20200118223713](https://user-images.githubusercontent.com/19425403/72665431-5f0b0900-3a43-11ea-8081-7a823a0d26b6.png)
How do i to set for building static limeReport (lib Lrdesigner demo_r1 console)?

**Comment by liufeijin** [comment]
I try add “include("D:/LimeReport-master/limereport.pri") “ to my app .pro file
after builded（qt5.12.6 static） i got  below errors

![TIM截图20200118223713](https://user-images.githubusercontent.com/19425403/72666032-3e45b200-3a49-11ea-93f8-525c17230143.png)
![11116](https://user-images.githubusercontent.com/19425403/72666034-41d93900-3a49-11ea-9a32-aee541e6f81e.png)
![33](https://user-images.githubusercontent.com/19425403/72666057-81a02080-3a49-11ea-8cd9-c6fe460e4946.png)

**Comment by fralx** [comment]
Hi!
Try to build without formdesigner. CONFIG += no_formdesigner

**Comment by liufeijin** [comment]
Wow ， put CONFIG += no_formdesigner in the limereport.pri all is ok
last time i put CONFIG += no_formdesigner in qmake . 

OK ,Many thanks.
