### ISSUE TITLE
Minimal QML Support

### ISSUE THREAD

**Issue by HatEmU** [fralx/LimeReport#250]
Hello, long time no see

I've completed a project in Qt Quick and I've used the wonderful LimeReport and I've made a C++ wrapper to be able to use LR from QML. It is currently just the bare-bones stuff (QSqlQueryModel, add variable, load from file, etc.)

Should I put it in the LimeReport repository (Maybe a new "Extensions" folder?) here or should I just make a new repository for it? Keep in mind that it needs a little tweaking to get it to work correctly and has some issues at the moment so I would like to write a tutorial or show some sample code for it.

Also do you have an e-mail or some way of contact? Thanks.

EDIT: This is the link for the [wrapper](https://github.com/HatEmU/QmlLimeReport) with a full tutorial on how to get it to work

**Comment by fralx** [comment]
Hi! 
I think it will be better to create a new repository.  
My e-mail: arin_a@bk.ru also you can visit limereport.ru/forum

**Comment by liufeijin** [comment]
Hi!
If you create a new repository,cloud you  post it on this.
