### ISSUE TITLE
Getting line number value

### ISSUE THREAD

**Issue by yanis60** [fralx/LimeReport#256]
Hi,
Is it possible to get the line number value for each line in a report?
If yes, can you please show me how?
Thanks

**Comment by yanis60** [comment]
Hi,
I found how to do it, i have to use in sql query.

Thanks

**Comment by fralx** [comment]
Hi!
You can do it in report :) 
And there are several ways to do it :)
1: using function line(BandName) ```$S{line("DataBand1")```
2: create a variable and increase it on after data band render  (this way can help you create  through numbering of all bands) 
```  
var linesCount = 1;
ReportPage1_DataBand1.afterRender.connect(DataBand1AfterRender)
function DataBand1AfterRender(){
  linesCount += 1;
} 
```

**Comment by liufeijin** [comment]
> Hi!
> You can do it in the report :)
> And there are several ways to do it :)
> 1: using function line(BandName) `$S{line("DataBand1")`
> 2: create a variable and increase it on after data band render (this way can help you create through numbering of all bands)
> 
> ```
> var linesCount = 1;
> ReportPage1_DataBand1.afterRender.connect(DataBand1AfterRender)
> function DataBand1AfterRender(){
>   linesCount += 1;
> } 
> ```
> 
> then in textitem `$S{linesCount}`

fralx this is for getting the lines count, but he seems want get each line number than use line number to do something.

**Comment by fralx** [comment]
Hi @liufeijin!
What difference between numbers and count if we speak about the serial numbers?

**Comment by liufeijin** [comment]
hi fralx
suppose there are 3 textitems in a line.
I think yanis60 want to get a textitem in a special line number ?  maybe it is my misunderstanding.
