### ISSUE TITLE
can't  add datasources  for a sqlite database  *.db file

### ISSUE THREAD

**Issue by liufeijin** [fralx/LimeReport#259]
hi fralx
Can't add connection for datasources in Lime report designer , i use QT5.14.1 and limepeprot master branch. 
![1111](https://user-images.githubusercontent.com/19425403/78424775-591be000-76a2-11ea-800b-895c5bc79af0.png)

Could you have check？ i used it long long ago,but now can't use.

**Comment by fralx** [comment]
Hi @liufeijin !
I have checked on Qt 5.14.2 and for me, all works as expected

**Comment by liufeijin** [comment]
Hi fralx
It is my wrong , i forget copy the "sqldrivers"  because LRDesigner.exe can build by DLL method only.
Thanks!

![TIM截图20200405165616](https://user-images.githubusercontent.com/19425403/78470895-7a8ed180-775f-11ea-9be2-aa05e012be95.png)
