### ISSUE TITLE
crash when delete translation languages button clicked

### ISSUE THREAD

**Issue by thetrashyNoob27** [fralx/LimeReport#261]
Designer window,Translations tab,when there is **no translation language exist**.then click delete translation language button(that red "-"symbol) crash.

**Comment by thetrashyNoob27** [comment]
sovle this problem.
in file _translationeditor.cpp:217_
void TranslationEditor::on_tbDeleteLanguage_clicked()
{
    m_translationChanging = true;
    m_translationContainer->removeTranslationLanguage(**m_currentReportTranslation**->language());
    updateUi();
    m_translationChanging = false;
}

**m_currentReportTranslation** is nullptr when crash happen,here is my solution:
void TranslationEditor::on_tbDeleteLanguage_clicked()
{
    **if(m_currentReportTranslation==nullptr){
        return;
    }**
    m_translationChanging = true;
    m_translationContainer->removeTranslationLanguage(m_currentReportTranslation->language());
    updateUi();
    m_translationChanging = false;
}

**Comment by fralx** [comment]
Done, thanks.
