### ISSUE TITLE
Databse connection field as variable

### ISSUE THREAD

**Issue by yanis60** [fralx/LimeReport#263]
Hi,
Is it possible to make database connection field as variable in connection dialog ?

**Comment by fralx** [comment]
Hi!
Yes, it's possible.

**Comment by yanis60** [comment]
can you please show me how?

**Comment by fralx** [comment]
As usual :) $V{VAR_NAME}. But I have checked the code and found out that not all fields can contain variables. Only user, password, and host. I will fix it soon.

**Comment by yanis60** [comment]
ohhhhh thank you so much.

Reaaly a great project
