### ISSUE TITLE
ts build error

### ISSUE THREAD

**Issue by elifyoldas** [fralx/LimeReport#264]
Hello 

ts error occured when i build the pro limereport,

**Comment by fralx** [comment]
Hi!
What kind of error do you have?

**Comment by elifyoldas** [comment]
![Capture](https://user-images.githubusercontent.com/11199310/81412745-fb6d2e80-914c-11ea-9d0d-62198df7a6bd.PNG)

i guess, this error is related to QtLinguist.

**Comment by fralx** [comment]
This happens because the path to the limereport project contains spaces.  Quick fix - remove spaces :)
I will fix the .pro file later

**Comment by elifyoldas** [comment]
thank you :)
 i fixed file name. project is succesfully built.

**Comment by fralx** [comment]
I have fixed the .pro file
