### ISSUE TITLE
Pdf file is being not include some objects

### ISSUE THREAD

**Issue by elifyoldas** [fralx/LimeReport#265]
Hello :)

I created lrxml file and previewed okey. After i call printToPDf, pdf is created. 
But Pdf is being not include some objects that are page number, text, some charts.

**Comment by fralx** [comment]
Hi!
It's very strange. Could you send me a sample?

**Comment by elifyoldas** [comment]
This my main code:

```
MainWindow::MainWindow(QWidget *parent)
    : QMainWindow(parent)
    , ui(new Ui::MainWindow)
{
    ui->setupUi(this);
    LimeReport::ReportEngine *report;
    report = new LimeReport::ReportEngine(this);

       report->loadFromFile( "ikincideneme.lrxml");
       report->designReport();
       report->previewReport();
       report->printToPDF("ikincideneme");
}
```

this is my .lrxml design:
![lrxmldosyası](https://user-images.githubusercontent.com/11199310/82198185-a1b2f400-9904-11ea-909d-f5f4f4efae86.PNG)



this is created pdf file:
![bozuk pdf](https://user-images.githubusercontent.com/11199310/82198211-aa0b2f00-9904-11ea-81aa-ba13ba89b4d3.PNG)

**Comment by thetrashyNoob27** [comment]
dose all the missing object NOT under databand1?
watch this:
![image](https://user-images.githubusercontent.com/62044271/82198901-8dd0b780-992f-11ea-96d0-9278e36041bd.png)
notice  that TextItem44 not under DataBand1. preview it
![image](https://user-images.githubusercontent.com/62044271/82199021-b8bb0b80-992f-11ea-8a07-00e8db63591e.png)
TextItem44 is missing. put it under DataBand1 will fix it.
![image](https://user-images.githubusercontent.com/62044271/82199142-e43df600-992f-11ea-8524-9782b315989f.png)
see :)

**Comment by fralx** [comment]
@elifyoldas Could you put here a zipped lrxml?

**Comment by elifyoldas** [comment]
[ikincideneme.lrxml.zip](https://github.com/fralx/LimeReport/files/4643500/ikincideneme.lrxml.zip)

**Comment by fralx** [comment]
@elifyoldas  Thanks. Fixed, you can check it.
