### ISSUE TITLE
Crashing when previewing a report that contains scripts

### ISSUE THREAD

**Issue by yanis60** [fralx/LimeReport#268]
Hi,
When i preview a report which containing script that loading datasource, Limereport Designer crashes .

Could you please fix it?

Here is an example of a report that makes Designer crashing when trying to preview it.

[invoice.zip](https://github.com/fralx/LimeReport/files/4676100/invoice.zip)

**Comment by fralx** [comment]
Hi!
I have fixed the TableBuilder you can check it

**Comment by yanis60** [comment]
Hi,
I checked and it's fixed.
Thank you

**Comment by liufeijin** [comment]
Hi
I noted the function in script , i see it first time, and don't know how to use
could you give any instruction for below function.  


var tableBuilder = DatasourceFunctions.createTableBuilder(ReportPage1_reglements);
	tableBuilder.buildTable("r");

**Comment by fralx** [comment]
Hi!
It has been discussed there #162
