### ISSUE TITLE
Not possible to set a file path when loading from bytearray

### ISSUE THREAD

**Issue by pasnox** [fralx/LimeReport#27]
Sometimes you do want to load/create a new report.
So you load it from byte array, but you can not give a pre defined file path for the future save of this report.
Please expose a ReportEngine::setReportFileName() as we already have a reportFileName().
This would allow to create a new report for a given file name already known in advance.

**Comment by fralx** [comment]
Fixed

**Comment by pasnox** [comment]
Thanks!
