### ISSUE TITLE
Data table name as a variable

### ISSUE THREAD

**Issue by tom947** [fralx/LimeReport#270]
Hi Fralx,

m_report.dataManager()->setReportVariable("table_name", "20200426151544_history");
Can i use data table name like select * from $V{table_name}? 

Thank you!

**Comment by fralx** [comment]
Hi!
Yes, it is possible.  You have to use "nobind"  in the variable  like this:
 select * from $V{table_name,nobind}

**Comment by tom947** [comment]
Hi!
Yes,it works!!
Thank you!
