### ISSUE TITLE
Limereport crashes

### ISSUE THREAD

**Issue by yanis60** [fralx/LimeReport#271]
Hi,
Can you please fix when we remove  custom databand and try to preview a report?

**Comment by fralx** [comment]
Hi!
I don't clearly understand how to reproduce this issue. What is a custom databand?

**Comment by yanis60** [comment]
Hi,
Try with this example :
https://github.com/fralx/LimeReport/files/4676100/invoice.zip

1-Open it with limereport designer and remove the custom databand located on pagefooter (with keeping the tableBuilder script).
2- preview the report, it will crash due to the script that can't find the custom databand.

And please make as a feature like Qt creator that saves an edited file automatically to not lose the edition of the report.

Thanks

**Comment by fralx** [comment]
Fixed :)

> And please make as a feature like Qt creator that saves an edited file automatically to not lose the edition of the report.

Good idea

**Comment by yanis60** [comment]
Thanks ;)

Other suggestion : Please when i write script, i want to change the height and width of an item if possible :)

**Comment by fralx** [comment]
You can use setItemWidth & setItemHeight for this purpose

**Comment by yanis60** [comment]
Doing this in Limereport Designer Script tab??

Can you please show me an example of code with a DataBand ?

**Comment by yanis60** [comment]
Thank you it worked ;)
