### ISSUE TITLE
Crash when printing a lot of barcodes

### ISSUE THREAD

**Issue by yanis60** [fralx/LimeReport#272]
Hi,

When i try to preview a lot of barcodes, limereport crashes (memory problem) can you please fix the issue?

Report i used

**Comment by fralx** [comment]
Hi! Could you send me an example?

**Comment by yanis60** [comment]
[barcode_40x20.zip](https://github.com/fralx/LimeReport/files/4766442/barcode_40x20.zip)

**Comment by fralx** [comment]
Could you send me data for this report if it is not a secret? 
You can use for this my email: arin_a@bk.ru

**Comment by yanis60** [comment]
I know where is the problem, when i try to print more than 2 000 barcode tickets, it crashes.
I tried it with a algorithm which duplicates a barcodes according to the number of copies to print.
if i set more than 2 000 copies for a product, it crashes :'(

**Comment by yanis60** [comment]
Hi,
Other think i discover, this crash only if we set a EndlessHeight of a reportPage to true.
Previewing without EndlessHeight never crash.
May be it limited by memory

**Comment by fralx** [comment]
Hi! I have tested and can't reproduce the issue. 
My test report produce 4312 barcodes without any problems except generation time 
[barcode_40x20_test.zip](https://github.com/fralx/LimeReport/files/4769461/barcode_40x20_test.zip)

**Comment by yanis60** [comment]
Have you tried from Designer or a new Qt project ?

**Comment by fralx** [comment]
I have tried it from demo_r1

**Comment by yanis60** [comment]
:( so maybe a model problem from my code ?
here is my code

`QTableWidget *t = new QTableWidget();
    t->setColumnCount(4);
    t->setHorizontalHeaderLabels(QStringList()<<"Désignation"<<"Code"<<"Prix"<<"Qté");
    QProgressDialog pr("Préparation en cours...","Annuler",0,0,this);
    pr.show();
    for(int j = 0 ; j < ui->tableWidget->rowCount() ; ++j)
    {
        if(pr.wasCanceled())break;
        qApp->processEvents();
            for(int i = 0 ; i < ui->tableWidget->item(j,4)->text().toInt() ; ++i)
            {

                t->insertRow(t->rowCount());
                t->setItem(t->rowCount() - 1,0,new QTableWidgetItem((ui->des->isChecked())?ui->tableWidget->item(j,0)->text():""));
                t->setItem(t->rowCount() - 1,1,new QTableWidgetItem(ui->tableWidget->item(j,1)->text()));
                t->setItem(t->rowCount() - 1,2,new QTableWidgetItem((ui->prix->isChecked())?ui->tableWidget->item(j,2)->text() + " DA":""));
                t->setItem(t->rowCount() - 1,3,new QTableWidgetItem(ui->tableWidget->item(j,4)->text()));

            }

    }
pr.close();
    LimeReport::ReportEngine *rp = new LimeReport::ReportEngine(this);
    rp->setPrintVisible(true);
    rp->setShowProgressDialog(true);
    qDebug()<<t->model()->rowCount();
    rp->dataManager()->addModel("b",t->model(), true);
    qDebug()<<rp->lastError();

    rp->setPreviewWindowTitle("Aperçu avant impression");
    if(ui->format->currentIndex() == 0)
        rp->loadFromFile(qApp->applicationDirPath() + "/reports/barcode.lrxml");
    else
        rp->loadFromFile(qApp->applicationDirPath() + "/reports/barcode_40x20.lrxml");

    rp->previewReport();
    delete t;
    delete rp;`

**Comment by fralx** [comment]
Could you test the report barcode_40x20_test.zip? 
Just run it from demo_r1

**Comment by yanis60** [comment]
The crash occur in previewReport function.

In my new report, i added a dialog to setup barcode ticket dimension, the dialog shows normally and after closing the dialog, it crashes when trying to preview the report.

**Comment by fralx** [comment]
What error message do you get?

**Comment by fralx** [comment]
How much free memory do you have at the time the program starts?

**Comment by yanis60** [comment]
I have 8GB of RAM, it's enough

**Comment by fralx** [comment]
More than :)

**Comment by yanis60** [comment]
Without EndlessHeight property, it works perfectly i can print 20 000 tickets but when i use EndlessHeight and try to print more than 2 000 it crashes

**Comment by yanis60** [comment]
I got no error message

**Comment by fralx** [comment]
Very interesting

**Comment by fralx** [comment]
Ok, I will think about what it could be. 
The difficulty is that I cannot reproduce the problem :(.

**Comment by yanis60** [comment]
I can make you a video if you want

**Comment by fralx** [comment]
Could you run demo_r1 in the debug mode with my report maybe in that case you can see the error?

**Comment by yanis60** [comment]
I've tried with LimeReport Designer, previewed 16 000 items using EndlessHeight and worked without crash :'(

**Comment by fralx** [comment]
As I understand it, the application only crashes in the release build, right?

**Comment by yanis60** [comment]
yes, on release build but if i print on A4 format, it not crashing

**Comment by fralx** [comment]
What OS, Qt version and compiler do you use? 
Could you get an early version of LimeReport  and test it for this issue?

**Comment by yanis60** [comment]
Windows 10, Qt 5.11 Mingw

i'll try with a latest version of limereport

**Comment by yanis60** [comment]
Tried with latest version, same think.

May be my itemModel causing the crash because of canFetchMore function that's return false but rowCount function returns all the number rows fetched

**Comment by fralx** [comment]
Hi! 
Could you check [endless_optimization](https://github.com/fralx/LimeReport/tree/feature/endless_optimization) branch?

**Comment by yanis60** [comment]
I've checked with endless_optimization and now it fixed, i was able to print 25 000 barcodes without any crash, thank you ;)
