### ISSUE TITLE
Fix for correct emit of onSave() when the report does not own a file name yet

### ISSUE THREAD

**Issue by pasnox** [fralx/LimeReport#28]
```
bool ReportDesignWidget::save()
{
    if (!m_report->reportFileName().isEmpty()){
        return m_report->saveToFile();
    }
    else {
        if (m_report->isSaved()) {
            m_report->emitSaveReport();
            return true;
        }
        if (m_report->saveToFile(QFileDialog::getSaveFileName(this,tr("Report file name"),"","Report files (*.lrxml);; All files (*)"))) {
            m_report->emitSaveReport();
            return true;
        }
        return false;
    }
}
```

**Comment by fralx** [comment]
m_report->emitSaveReport() emits ReportEngine::onSave signal. You can connect to the signal and save a report as you wish using : 
```C++
bool    saveToFile(const QString& fileName);
QByteArray  saveToByteArray();
QString saveToString(); 
```
All this methods switch the report to saved state and isSaved() will return true. 
If the report is in an unsaved state after signal processing then "save to file dialog" will appear. If the report has no changes the dialog won't appear

**Comment by pasnox** [comment]
That's the problem, if the report don't yet have a file name, then the dialog appear.
But there is no way to be informed when it's really saved (onSave being emitted before the dialog appear).
So in the onSave slot, the reportFileName is still empty.
We need a reliable way to be informed when the report is effectively saved.
What your onSave is, is just an 'aboutToSave' signal.

**Comment by fralx** [comment]
You can implement slot something like this :
``` C++
void slotOnSaveReport(){
     m_report.saveToFile("any_name_file");
}
``` 
it will save report and "save to file dialog" won't appear.
And I can add setFileName() to ReportEngine  will it suits you ?

**Comment by pasnox** [comment]
Indeed, I can create slot and save myself, but i'm lazy - LimeReport already handle that itself!
Let continue as is and just add a new signal - onSaved() emitted after a report have been **truely** saved being to file, bytearray or string.
Also a setReportFileName() would very be welcomed.

Thanks you.

**Comment by pasnox** [comment]
Thanks!
