### ISSUE TITLE
Script does't work in BarcodeItem

### ISSUE THREAD

**Issue by blueany** [fralx/LimeReport#282]
Hi Alex, thanks for your great work with LimeReports!

I have found a bug and fix it. when you use scipt in a barcode item. it does't work.

for explame:
        $S{dateTimeFormat(now(), “yyyyMMdd-hhmmss")}; 

I modify code  to fix it:

> BarcodeItem::updateItemSize() 
> {
>     //...
>             setContent(expandUserVariables(content(),pass,NoEscapeSymbols, dataManager));
>             **setContent(expandScripts(content(), dataManager));  // add this line of code to fixed it .**
>             setContent(expandDataFields(content(), NoEscapeSymbols, dataManager));
>     //...
> }

here is the code after modified:
![微信截图_20200808162449](https://user-images.githubusercontent.com/17285689/89706000-a97ab580-d994-11ea-8c3e-bc8ebc9e35fe.png)

**Comment by fralx** [comment]
Thanks, fixed
