### ISSUE TITLE
Typing password of a connection as a variable

### ISSUE THREAD

**Issue by yanis60** [fralx/LimeReport#283]
Hi,
I noticed that the password passed as a variable is hashed, i want to set a variable $V{psw} and replace it from my project.

Is it possible to do it?
![image](https://user-images.githubusercontent.com/30592254/89761465-b7444e00-daee-11ea-97ce-4c2024db716c.png)

**Comment by fralx** [comment]
Hi!
Yes it's possible you can use a variable in the password field

**Comment by yanis60** [comment]
Ok thank you
