### ISSUE TITLE
Asking for explanation

### ISSUE THREAD

**Issue by yanis60** [fralx/LimeReport#285]
Hi,
Could you please explain me the useful of this highlighted option ?
![image](https://user-images.githubusercontent.com/30592254/89910615-beec1b80-dbf0-11ea-9353-aef6056c9102.png)

**Comment by fralx** [comment]
If you check it the connection will be replaced with the default application connection at runtime.
I can say more, if a connection with the same name that already exists in your application was described in the report template, it will not be created, the report engine will use the existing one

**Comment by yanis60** [comment]
This means that i don't need to fill the connection fields?

**Comment by fralx** [comment]
No, this feature's purpose is to allow you to create a "default connection" stub in the time when you creating a report by the standalone limereport designer application. You have to fill all fields as usual but in runtime, limereport will use the "default connection" established by your application instead described in the report template. You also can check "Don't keep credentials in lrxml" ( I have to fix the typos :) )  and in that case, limereport will keep credentials in the separate file.

**Comment by yanis60** [comment]
ok thank you
