### ISSUE TITLE
useAlternateBackgroundColor doesn't work on for a first element in a list (e.g. on page break)

### ISSUE THREAD

**Issue by 7ymekk** [fralx/LimeReport#286]
UseCase:
- make a Data or SubDetail with a lot of rows that will cause page break
- set: useAlternateBackgroundColor=true, backgroundMode=Opaque, alternateBackgroundColor=#dfdfdf
- notice that if first row after page break should be marked as alternate, it's not and looks like not alternate

(I've put blue rectangles to hide sensitive data)

![image](https://user-images.githubusercontent.com/1269434/89996103-a92b3480-dc8a-11ea-972f-8b0f6778e467.png)

I noticed that following code fixes the issue but it seems to me like workaround and not the fix itself:

```
lrreportrender.cpp: ReportRender::renderBand

if (mode==StartNewPageAsNeeded){
    if (bandClone->columnsCount()>1 &&
        (bandClone->columnsFillDirection()==BandDesignIntf::Vertical ||
         bandClone->columnsFillDirection()==BandDesignIntf::VerticalUniform))
    {
        startNewColumn();
        if (patternBand->bandHeader() &&
            patternBand->bandHeader()->columnsCount()>1 &&
            !m_lostHeadersMoved &&
            patternBand->bandNestingLevel() == 0
        ){
            renderBand(patternBand->bandHeader(), 0, mode);
        }
    } else {
        savePage();
        startNewPage();
        if (!bandIsSliced){
            BandDesignIntf* t = renderData(patternBand);
            t->copyBookmarks(bandClone);
            t->setBackgroundColor(bandClone->backgroundColor()); //<----------------I ADDED THIS LINE
            patternBand->emitBandReRendered(bandClone, t);
            delete bandClone;
            bandClone = t;
        }
    }
```

**Comment by fralx** [comment]
The right solution, the new band have to take background color from bandClone. I have fixed it.

**Comment by 7ymekk** [comment]
again: thanks for a quick response and fix :)
