### ISSUE TITLE
Need explanation

### ISSUE THREAD

**Issue by yanis60** [fralx/LimeReport#287]
Hi,
I noticed a property 'format' for textitem, could you please explain me what formats to use?
![image](https://user-images.githubusercontent.com/30592254/90111156-85312700-dd4e-11ea-98fc-cf86aa6f5508.png)

**Comment by fralx** [comment]
Hi!
The "format" property is used to format the field if the "valueType" is different than Default. 
For example format = dd.mm.yyyy and valueType = DateTime

**Comment by yanis60** [comment]
Can i format numbers?

**Comment by fralx** [comment]
Yes

**Comment by yanis60** [comment]
can you please show me how with an example?

**Comment by fralx** [comment]
valueType = Double, format = $ %.2f 
QString::sprintf is used under the hood

**Comment by yanis60** [comment]
ok thank you
