### ISSUE TITLE
Question: how to access item other than Page inside Script in Designer

### ISSUE THREAD

**Issue by 7ymekk** [fralx/LimeReport#288]
Hi Alex,

I'm using designer with following function in Scripts:

```
function uptimeEventsString(eventsBitmap) {
	var eventsStringsArray = []
	if (eventsBitmap == 0)
		return "-"
	if (eventsBitmap & 0x1)
		eventsStringsArray.push("Error Count Changed")
	if (eventsBitmap & 0x2)
		eventsStringsArray.push("Link Dropped")
	(...)
	return eventsStringsArray.join("\n")
}
```

Problem: how to make these strings translatable?

I was thinking about 'trick' with creating 'Additional Translations' page with printable=false. Then I would create fields like: UptimeEventStringErrorCountChanged, UptimeEventStringLinkDropped, (...) and put above strings as contents.

thanks to this "Translations" module would have these strings detected and translated. 

Then my script could look like:

```
function uptimeEventsString(eventsBitmap) {
	var eventsStringsArray = []
	if (eventsBitmap == 0)
		return "-"
	if (eventsBitmap & 0x1)
		eventsStringsArray.push(UptimeEventStringErrorCountChanged.content)
	if (eventsBitmap & 0x2)
		eventsStringsArray.push(UptimeEventStringLinkDropped.content)
	(...)
	return eventsStringsArray.join("\n")
}
```

but I'm getting "ReferenceError: UptimeEventStringErrorCountChanged is not defined"

I tried to:
- use camelCase and PascalCase names for UptimeEventStringErrorCountChanged
- accessing via ReportPage.UptimeEventStringErrorCountChanged
- putting in the same page and same band and use $S{UptimeEventStringErrorCountChanged.content} directly on another page
- also usage mentioned above, so in script
- access ReportPage.objectName in my script - that worked

Could you please tell me if there's some way to access items in scripts and on different page than it's stored? Translations is just one example of such a usage.

I know that for more custom approach I can use limeReport.so and add my own code to execute before generating report, but I'm wondering if there's some Designer way to do so ;)

Maybe it's worth considering to add qsTr("") usage in Script, so Translations could detect it?

**Comment by fralx** [comment]
Hi!
If you want to get access to for example to Reportpage1.TextItem1 you have to use the next name
Reportpage1_TextItem1 (this is weird, but JSEngine have or had some limitation and I was forced to use this trick)

**Comment by 7ymekk** [comment]
Thanks! this is exactly what I was looking for
