### ISSUE TITLE
Bug when editing datasource

### ISSUE THREAD

**Issue by yanis60** [fralx/LimeReport#289]
Hi,
When i edit a datasource and save the changes, it creates a new one instead of editing the old one

**Comment by fralx** [comment]
Hi
Do you use the latest version? 
I can't reproduce the issue

**Comment by yanis60** [comment]
Yes i'm using the latest version.
Try to create a new datasource then edit it and change it name you'll see that he creates a new one instead of editing the old

**Comment by fralx** [comment]
Fixed :)

**Comment by yanis60** [comment]
Ok thank you
