### ISSUE TITLE
Warning Qt5.7

### ISSUE THREAD

**Issue by newsages** [fralx/LimeReport#29]
https://wiki.qt.io/New_Features_in_Qt_5.7

Deprecated Modules

The following modules are part of Qt 5.6 release, but deprecated and considered for removal in subsequent releases of Qt:

```
Qt Script
```

**Comment by davidovv** [comment]
I just compiled LimeReport from source on Qt 5.7
There are 131 issues like unused variable, and comparison between signed and unsigned integer...
When you have so many warnings, you start to ignore them, so something serious might be overlooked.

**Comment by fralx** [comment]
most of the errors are in the thridparty library zint

**Comment by fralx** [comment]
I have created new branch 1.4_QJSEngine. In this branch you can use QJSEngine instead QScriptEngine
