### ISSUE TITLE
ReportEngine крашится, если попытаться его удалить на открытом preview

### ISSUE THREAD

**Issue by DrGluck** [fralx/LimeReport#3]
Создаём ReportEngine, передаём в него модель, вызываем previewReport. Если попытаться удалить ReportEngine, то приложение крашится. Проявляется в 1.2.1 и 1.3.9 (1.3.1 не пробовал), Qt 4.8.6.
На designReport не проявляется.

Возможно предполагается, что ReportEngine должен использоваться исключительно как синглтон. Но тогда нужен какой-либо признак, что сейчас есть открытый отчёт и функция "закрыть отчёт".

**Comment by DrGluck** [comment]
А вот не починилось же.

**Comment by fralx** [comment]
Странно. Я не наблюдаю падения.
Проверяю следующим образом:

void MainWindow::runPreview(){
            QTimer* timer = new QTimer(this);
            connect(timer,SIGNAL(timeout()), this, SLOT(slotOnTimer()));
            timer->start(5000);
            report()->loadFromFile(fileName);
            report()->previewReport();
}
void MainWindow::slotOnTimer()
{
    dynamic_cast<QTimer*>(sender())->stop();
    delete m_report;
    m_report = 0;

}

Окно предпросмотра закрывается, исключения не летят.
