### ISSUE TITLE
how to read the data from json

### ISSUE THREAD

**Issue by turbin** [fralx/LimeReport#300]
Dear fralx,
Thanks for your effort to this project.
I want to read data from a json file into a text item object. would u mind give me some guidences for it?

Thanks a lot, and waiting for your reply.

**Comment by fralx** [comment]
Hi!
Limereport doesn' support reading data from json directly. You can read read json on side of your application and send it to limereport via model, callbackdataset or variables

**Comment by turbin** [comment]
> Hi!
> Limereport doesn' support reading data from json directly. You can read read json on side of your application and send it to limereport via model, callbackdataset or variables

Thanks for your reply. It is very helpful for me.
