### ISSUE TITLE
desiger crash issue

### ISSUE THREAD

**Issue by turbin** [fralx/LimeReport#306]
Hi All,
I found a crash issue in designer, when I displayed the template then it crashed.

I traced this issue then make a path. but I don't know how to submit this patch. Does any one give me a guidence?

**Comment by fralx** [comment]
Hi.
To create Pull Request you have to create a fork of limereport then made changes and create a pull request :) you can read about it here https://help.github.com/en/articles/creating-a-pull-request-from-a-fork.

**Comment by turbin** [comment]
thx, I will read this article then submit my patch.
