### ISSUE TITLE
build error by QT5.15.2

### ISSUE THREAD

**Issue by liufeijin** [fralx/LimeReport#310]
hi 
There is a error when build by QT5.15.2  in file lrsimplecrype.cpp
![QQ截图20201221164318](https://user-images.githubusercontent.com/19425403/102757096-bf20d280-43ab-11eb-9a02-39a7f8ded2b8.jpg)

Found the WORD was defined in minwindef.h file  as  "type unsigned short WORD"
How to correct it?
![QQ截图20201221181807](https://user-images.githubusercontent.com/19425403/102766463-21cc9b00-43b9-11eb-8d34-3190a0b448a0.jpg)

**Comment by darktorres** [comment]
I had this error occur when using precompiled headers. I renamed WORD in lrsimplecrypt.cpp to LRWORD but that is not a proper fix.

**Comment by fralx** [comment]
@liufeijin, move namespace LimeReport { on the second line after #include "lrsimplecrypt.h".

**Comment by liufeijin** [comment]
hi fralx 
after move namespace LimeReport , the error is still.  I use static QT5.15.2

**Comment by fralx** [comment]
It's very strange. I can't reproduce the problem. 
Just little sample :
```c++
#include <iostream>

typedef unsigned short int WORD;
namespace Test{
  typedef unsigned long int WORD;
  void printTestWORDSize(){ std::cout << sizeof(WORD) <<std::endl;}
}
void printTestWORDSize(){ std::cout << sizeof(WORD) << std::endl;}

int main() {
  printTestWORDSize();
  Test::printTestWORDSize();
}
```
this sample complied and works without any problems

**Comment by liufeijin** [comment]
I use VS2019 to build it. you use MinGW64?

**Comment by fralx** [comment]
I have tested it on VS2019 and for me, all builds as expected. To be honest, for me, it is compiled without changing the namespace. :)

**Comment by liufeijin** [comment]
My OS ver. is  windows10 19042.685. What ver. is you OS? 
I use QT5.12.6 has this error also now, but there is no error before. 
Does OS lead to this error?(minwindef.h)

**Comment by fralx** [comment]
I have compiled it on Windows 10 1809 :)

**Comment by liufeijin** [comment]
So. hope your OS updated ASAP
