### ISSUE TITLE
about grid component

### ISSUE THREAD

**Issue by turbin** [fralx/LimeReport#313]
Hi fralx,
   any idea for creating the grid component. The data band component seems support the splitable feature. but I have no idea how to use this feature to implement a grid component.
dose anything can demostrate this?

thanks.

**Comment by fralx** [comment]
[table_example.zip](https://github.com/fralx/LimeReport/files/5967244/table_example.zip)

**Comment by turbin** [comment]
@fralx  Thanks a lot
