### ISSUE TITLE
Embed Image in report file

### ISSUE THREAD

**Issue by gorazdr** [fralx/LimeReport#315]
Hello,

Thanks for great project.
Is it possible to embed image into report file like you embed svg image as QByteArray?

Thanks,
Gorazd

**Comment by fralx** [comment]
Hi! Sorry, I do not completely understand your question :) 
You can put an ImageItem on the page then select an image that you want to embed to a report.

**Comment by gorazdr** [comment]
Let me expain.

I made test report. I added Image item and SVG Item. When I try created test report on another computer SVG item shows selected svg image but Image item does not. It makes sense because Image item uses resourcePath to image on my computer SVG item on the other hand has image embedded into report itself

`<resourcePath Type="QString"></resourcePath>
  <image Value="P...2Zz4K" Type="QByteArray"/>`

I would like to know if the same can be done for Image item.

Thanks,
Gorazd

**Comment by fralx** [comment]
ImageItem can embed an image into lrxml.  
If you use the Image property to store the image it will be stored in the report file. 
You can double-click on the ImageItem and in the shown dialog select an image using the folder button.

Report template with embedded image [image.zip](https://github.com/fralx/LimeReport/files/5996397/image.zip)

**Comment by gorazdr** [comment]
Great. It works as expected.

Thanks and keep up good work.
