### ISSUE TITLE
to set the width of the data band

### ISSUE THREAD

**Issue by turbin** [fralx/LimeReport#320]
![图片](https://user-images.githubusercontent.com/3733131/110223961-915f1a80-7f12-11eb-9269-814ec70fd3fe.png)

Hi, I met a requirement as showing in the diagram.
how could I move the postion of the data band and set the width for it.
Thanks.

**Comment by fralx** [comment]
Hi! 
You can do something like this [sub_report.zip](https://github.com/fralx/LimeReport/files/6118713/sub_report.zip)

**Comment by turbin** [comment]
Thanks, I will check it later.

**Comment by turbin** [comment]
Hello, I tested this template file. the template shows as :
![图片](https://user-images.githubusercontent.com/3733131/110910666-a097fb00-834c-11eb-8db5-94d2282ff36b.png)

but, this is my requiment:
![图片](https://user-images.githubusercontent.com/3733131/110910928-f66ca300-834c-11eb-80ef-13f8e477d25e.png)

any idea for this?

**Comment by fralx** [comment]
As I can see you not fully repeated my example :) 
It's all about the little things
First of all the repeatable table cels should be united in the horizontal layout.  
The last, not repeatable cell should be not in the horizontal layout and should have activated property stretchToMaxHeight.
Also, the important thing is the init script.
``` javascript
Reportpage1_DataBand1.beforeRender.connect(beforeDataPrint)
function beforeDataPrint() { 
  var tableBuilder=DatasourceFunctions.createTableBuilder(Reportpage1_data);	
  tableBuilder.buildTable("master");
} 
```
As result you will get something like this
![2021-03-12_11-33-40](https://user-images.githubusercontent.com/14914730/110914004-df1abf00-8326-11eb-82f0-da254b27c529.png)

**Comment by turbin** [comment]
Thanks for your guidance. It is working now.
here is the rendering result with my test data:
![image](https://user-images.githubusercontent.com/3733131/111124956-0a621000-85ac-11eb-8f89-8da43610d5e8.png)

But, it is not perfect. The item named "DeliverDataYY" is hidden, due to the right area  is not enough to contain the whole text content in the right side.
I try to inactive the  property named “stretchToMaxHeight” but it is not working.

My question is how to extend the height to display the whole text content in the right side.

**Comment by fralx** [comment]
You can activate autoHeight property for the item that contains DeliverDateYY but it will make this item height bigger than the table height. It will look like this:
Table content is smaller then last item 
![2021-03-15_12-58-44](https://user-images.githubusercontent.com/14914730/111136016-556d2a80-858e-11eb-97ae-5fe0129a3583.png)
Table content is bigger then last item 
![2021-03-15_12-59-11](https://user-images.githubusercontent.com/14914730/111136047-5b630b80-858e-11eb-94e2-4d3998d2b7b5.png)

**Comment by turbin** [comment]
Yes, it was working. Thanks  a lot.
