### ISSUE TITLE
Fix QWidget sizePolicy

### ISSUE THREAD

**Issue by newsages** [fralx/LimeReport#33]
Hi, how autoajust Size of QWidget, scale/fit on QWidget?

![captura de pantalla de 2016-05-06 00-19-06](https://cloud.githubusercontent.com/assets/9095584/15059060/74ba5fc4-1320-11e6-89fb-659c1ffd53ae.png)

**Comment by fralx** [comment]
LimeReport::PreviewReportWidget has slots:
zoomIn();
zoomOut();
fitWidth();
fitPage();

**Comment by newsages** [comment]
I try fix and Zoom.

But if i use dynamic widget size is dificult to scale.

Can dynamical inherit size of widget for scale?

**Comment by fralx** [comment]
Can you describe the problem more detail ? I'm really don't understand what do you mean :)

**Comment by newsages** [comment]
in the example of the photo:
widget to split.
How I can make the width of the parent widget will automatically adjust to the previsualizacion ?

If Size change.  How to connect size of parent with reprt and fit scale?
