### ISSUE TITLE
New function Currency Format

### ISSUE THREAD

**Issue by alonsomm2000** [fralx/LimeReport#34]
Hi, every body, I am using Limereport and find it very usefull but was lacking of some useful functions so I created and added the following function:

In file: lrscriptenginemanager.cpp
QScriptValue currencyFormat(QScriptContext* pcontext, QScriptEngine* pengine){
    QVariant value = pcontext->argument(0).toVariant();
    QString CurrencySymbol = (pcontext->argumentCount()>1)?pcontext->argument(1).toString():"";

    // Format it using USA locale
    QString vTempStr=QLocale(QLocale::English, QLocale::UnitedStates).toCurrencyString(value.toDouble());

    // Replace currency symbol if necesarry
    if (CurrencySymbol!="") vTempStr.replace("$", CurrencySymbol);

    QScriptValue res = pengine->newVariant(vTempStr);
    return res;
}

And inside: ScriptEngineManager::ScriptEngineManager():m_model(0), m_dataManager(0)
addFunction("currencyFormat",currencyFormat,"NUMBER","currencyFormat(\""+tr("Value")+"\",\""+tr("CurrencySymbol")+"\")");

With this code you can easily convert plain numbers into nice formatted currency by using:
$S { currencyFormat(1000.25,"£") }

Beside allowing you to use SUM() with passed data fields!

I pass on the code so you can include it on the next release!

**Comment by fralx** [comment]
Hi
I have made some changes in your function :) to make it more universal
``` c++
QScriptValue currencyFormat(QScriptContext* pcontext, QScriptEngine* pengine){
    QVariant value = pcontext->argument(0).toVariant();
    QString locale = (pcontext->argumentCount()>1)?pcontext->argument(1).toString():QLocale::system().name();
    return pengine->newVariant(QLocale(locale).toCurrencyString(value.toDouble()));
}
```
using example:

$S{currencyFormat(1000)} will format currency in system locale 
$S{currencyFormat(1000,"en_US")} will format in United States format - $1000.00
$S{currencyFormat(1000,"en_GB")} will format in United Kindom format - £1000.00

**Comment by alonsomm2000** [comment]
I looks somehow convenient but there is a BIG problem with some locales like: es_CR   (spanish Costa Rica)
and any other country that does not use . ( dot ) as decimal separator, there is a BUG in Qt that cause a number like: 1568.88  to be rounded to: ₡1.569 and that is no good for anybody, so in order to overcome that bug I did the following:

// Get local currency symbol and store it in a variable
QString MyCurrencySymbol=QLocale::system().currencySymbol();

// Then set the default locale to English US
const QLocale & cLocale = QLocale::c();
cLocale.setDefault(QLocale(QLocale::English, QLocale::UnitedStates));

// Format it to currency using English US
double MyDouble=1568.88;
QString ss=QLocale().toCurrencyString(MyDouble);

// And then replace the Dolars symbol with the local system currency symbol
ss.replace("$", MyCurrencySymbol);

Regards,
           Alonso M.

**Comment by fralx** [comment]
Yes I see. The problem is that there is no currency symbol in Russian locale and a value must be formatted like this: 1000,25 руб.

**Comment by alonsomm2000** [comment]
Can you use the symbol in front of the numbers? 
According to KDE Regional config you have the following symbols in Russia: py6. (RUB) and py6. Ruble A/97 (RUR)

But according to Wikipedia you do have a single character symbol: 
![ruble_sign_pt_sans](https://cloud.githubusercontent.com/assets/15023328/15775042/f2e3b92c-293c-11e6-9a3b-8f28769667c6.png)
The only problem is that symbol does not seem to be in most of the fonts.

So keeping the first code I proposed is best I think, but if you want to the currency symbol at the end you can do:

// And then replace the Dolars symbol with the local system currency symbol
ss.replace("$", "");
ss+=MyCurrencySymbol;

**Comment by fralx** [comment]
I have added currencyUSBasedFormat 
``` c++
QScriptValue currencyUSBasedFormat(QScriptContext* pcontext, QScriptEngine* pengine){
    QVariant value = pcontext->argument(0).toVariant();
    QString CurrencySymbol = (pcontext->argumentCount()>1)?pcontext->argument(1).toString():QLocale::system().currencySymbol();
    // Format it using USA locale
    QString vTempStr=QLocale(QLocale::English, QLocale::UnitedStates).toCurrencyString(value.toDouble());
    // Replace currency symbol if necesarry
    if (CurrencySymbol!="") vTempStr.replace("$", CurrencySymbol);
    return pengine->newVariant(vTempStr);
}
``` 
Is it OK ?

**Comment by alonsomm2000** [comment]
Yes my friend it it looks Ok, good job!
