### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by yanis60** [fralx/LimeReport#346]
Hi, 
I got these errors while compiling the latest version
![image](https://user-images.githubusercontent.com/30592254/133121318-4f87b954-f2bb-49e6-84a0-840581576537.png)

**Comment by fralx** [comment]
Hi. Could you get the latest commit and try again. I have fixed it recently

**Comment by yanis60** [comment]
I've got the last commit but same errors :'(

**Comment by fralx** [comment]
did you clean the project?

**Comment by yanis60** [comment]
yes i did

**Comment by fralx** [comment]
The same result the error still exists?

**Comment by yanis60** [comment]
yes :(

**Comment by fralx** [comment]
It's very strange. I will check it once again.   But as you can see, AppVeyor has built the project 
![Build](https://user-images.githubusercontent.com/14914730/133129539-9829bdfd-8824-4363-9042-3fa376f50291.png)

**Comment by fralx** [comment]
As a quick fix, you can remove lrdview from limereport.pro. I think it can help

**Comment by yanis60** [comment]
yes the quick fix helped me, i built it

**Comment by fralx** [comment]
Could you look through lrdview.pro and check if include(../qzint.pri) exists or not?

**Comment by yanis60** [comment]
I fixed it by commenting this line ;)
![image](https://user-images.githubusercontent.com/30592254/133133480-d2cef234-fc64-4b90-a5af-6858e37cc647.png)

**Comment by fralx** [comment]
If you look through lrdview.pro at GitHub this line is absent :)

**Comment by yanis60** [comment]
lol, what she is doing here!!!??

**Comment by yanis60** [comment]
Have you tested the version i sent to you since few months?

I've added some new shapes, new border styles and border radius.

**Comment by fralx** [comment]
Why your file has the old version if you puled the last commit is a big question for me :)

**Comment by yanis60** [comment]
In fact, i'm not really pulling, i'm downloading the archive from github and built it

**Comment by fralx** [comment]
>>Have you tested the version i sent to you through email since few months?

>> I've added some new shapes, new border styles and border radius.
Yes, I have tested it but your borders are contradictory to my approach to borders.   
My borders could be configured side by side

**Comment by yanis60** [comment]
yes i know that, you can remove this function

**Comment by fralx** [comment]
Ok, I will check it again when I have a free time
