### ISSUE TITLE
Print out sequence will be error  when set some page to  printable (false)

### ISSUE THREAD

**Issue by liufeijin** [fralx/LimeReport#362]
Hi fralx

There is a bug when set  printable  of page to "false" , the sequence of pages will be error.
I attached a sample . if i set printable of "page5"  to false, then index page will be error.
[test.zip](https://github.com/fralx/LimeReport/files/7689441/test.zip)

**Comment by fralx** [comment]
I have fixed it in the branch [hotfix/1.6.0](https://github.com/fralx/LimeReport/tree/hotfix/1.6.0). This branch is 1.6 version release candidat. Could you check it and say me if it`s all right with you reports in this version or not ?

**Comment by liufeijin** [comment]
Hi fralx
It is correct now. 
Many thanks !!!
