### ISSUE TITLE
get and change  databand height in QT APP or script

### ISSUE THREAD

**Issue by liufeijin** [fralx/LimeReport#363]
Hi fralx
Is there any way to get and change height of databand  in QT app or script?

I found it that use "setItemHeight" to change  height of item.
But, i still don't know how to get the height of items.
i tried DataBand1.geometry.Height , but nothing is present.

**Comment by fralx** [comment]
Hi! You can use something like this 
```
Reportpage1_DataBand1.setItemHeight(Reportpage1_DataBand1.geometry.height/10+10)
```

**Comment by liufeijin** [comment]
hi fralx 
Many thanks , i will have a try

**Comment by liufeijin** [comment]
seems the height is not correct 
when i used   
  CLKHPg9T_DataFooterBand1.beforeRender.connect(Pg9T)
  
    function Pg9T(){
       CLKHPg9T_TextItem9.setItemHeight(195-CLKHPg9_DataBand1.geometry.height/10);
    }

I want the height of Textitem9 in DataFooterBand1 is follow up the height of DataBand1.
but got the height is small

**Comment by fralx** [comment]
> I want the height of Textitem9 in DataFooterBand1 is follow up the height of DataBand1.

You can use stretchToMaxHeight property for this

>but got the height is small

I have tested it and for me, it works as expected :)
![set_geometry](https://user-images.githubusercontent.com/14914730/146605867-c987596a-715e-4c6d-a112-53f88b18e1fd.gif)

**Comment by liufeijin** [comment]
Hi fralx
I still can get the expected result. 
I see your demo. the databand is fixed, but in my report the databand is set to 5mm and TextItem set to 95mm.
if database has 19 rows then filling 19 rows into databand, the hight of databand will be change to 95,Textitem will be changed to 5mm.
maybe get the height of banddata is not the after changed size?

**Comment by fralx** [comment]
Could you send me example?

**Comment by liufeijin** [comment]
[test.zip](https://github.com/fralx/LimeReport/files/7748924/test.zip)

**Comment by fralx** [comment]
```
let rowsHeight = 0
Reportpage1_DataBand1.afterRender.connect(ar)
Reportpage1_DataFooterBand6.beforeRender.connect(rr)

function ar(){
  rowsHeight += Reportpage1_DataBand1.geometry.height
}

function rr(){
  Reportpage1_DataFooterBand6.setItemHeight(253-rowsHeight/10.0);
  Reportpage1_TextItem6.setItemHeight(248-rowsHeight/10.0);
} 
```
I think this will help you :)

![bandHeight](https://user-images.githubusercontent.com/14914730/146954916-2f0f6e16-e659-4508-a624-ebf70797107f.gif)

**Comment by liufeijin** [comment]
Hi fralx
 Many thanks for your help！
It is ok now!
BTW, the hotfix1.6.0 for pages order is ok also. you can merge it to master.
