### ISSUE TITLE
Report designer will crash when use image and text as water mark

### ISSUE THREAD

**Issue by liufeijin** [fralx/LimeReport#365]
Hi fralx
When i try use water mark . when try print out it . designer will crash.
Cloud you have a look on it.
[TEST.zip](https://github.com/fralx/LimeReport/files/7772446/TEST.zip)
[Uploading TEST.zip…]()

**Comment by liufeijin** [comment]
i use PDF tool  to add picture as background

**Comment by fralx** [comment]
Hi, I have tested it, and all works as expected. What exception do you get when lime report crashes?
