### ISSUE TITLE
how to let ShowProgressDialog show? 

### ISSUE THREAD

**Issue by liufeijin** [fralx/LimeReport#366]
i have set  
Report->setShowProgressDialog(true);
Report->setPrintVisible(true);
Report->loadFromFile(Formatfile);
 Report->printToPDF(sd.fileName());
  Report->previewReport();

but only get the preview result and pdf.
There is no the progressdialog pup out.

**Comment by fralx** [comment]
Hi! I have tested your case and it seems to work for me as expected.
![ProgressDialog](https://user-images.githubusercontent.com/14914730/149845018-06cf119e-61cb-4fed-a1a9-f0cb2b31364c.gif)
