### ISSUE TITLE
error in CMakeList.txt

### ISSUE THREAD

**Issue by ivti** [fralx/LimeReport#371]
linking with a cmake project (ported demo_r1) that uses targel_link_library for import fails as the the compile definitions are PUBLIC. Must be PRIVATE at a minimum for LIMEREPORT_EXPORTS - SHARED lib. "-D" ist obselete by the way.
.....
if (LIMEREPORT_STATIC)
	message(STATUS "STATIC LIBRARY")
	add_library(limereport STATIC  ${EXTRA_FILES} ${LIMEREPORT_SOURCES})
    target_compile_definitions( limereport PUBLIC -DHAVE_STATIC_BUILD)
else()
    add_library(limereport SHARED  ${EXTRA_FILES} ${LIMEREPORT_SOURCES})
    target_compile_definitions( limereport PRIVATE -DLIMEREPORT_EXPORTS)
endif()

**Comment by Jihadist** [comment]
Feel free to create PR

**Comment by Jihadist** [comment]
Fixed by #418

**Comment by Jihadist** [comment]
@fralx can it be closed?

**Comment by fralx** [comment]
I think yes :)
