### ISSUE TITLE
bug with sum() in demo_r2/demo_reports/demoReport1_report_header_group_subdetail.lrxml

### ISSUE THREAD

**Issue by ivti** [fralx/LimeReport#375]
The sum() function in demo_r2/demo_reports/demoReport1_report_header_group_subdetail.lrxml leads to an indefinite loop (as far as I can see). The report doesn't come back.

The sum function is here:

subdetail footer --> $S{SUM($D{orderitems.Quantity},"SubDetailBand1")}

This should not happen. Am I right ?

I removed the function and the report works.

Any idea ?

**Comment by fralx** [comment]
Hi!
Can't reproduce the issue. For me, it looks like this. 
What OS, Qt and compiler do you use? 
![lr_demo2](https://user-images.githubusercontent.com/14914730/150125922-3e5ca351-436d-4ef1-a69f-5d98ecff47a5.gif)

**Comment by ivti** [comment]
Infos about the environment etc:
Windows 10
compiler: MSVC 2017, 64 bit, newest patch
Qt: 5.9.9
If I remove the sum it works like you show. But with the sum 
it comes to an endlos loop in the while loop you see in the debugger window screenshot. You will find a lot of information: call stack, several variable values, also directly in the source text extended by the debugger. I also added screenshot of the watches from the debugger. This is Clion with lldb on Windows. If you need more infos I can open this info for you. 

![grafik](https://user-images.githubusercontent.com/6132007/150187615-26879f01-a95f-4756-a0fc-225f2c442ef0.png)
![grafik](https://user-images.githubusercontent.com/6132007/150189114-78a09f0f-0ac1-4b85-9e64-41a224f06802.png)
![grafik](https://user-images.githubusercontent.com/6132007/150189361-cdea043c-e751-4027-a071-0dccf291f5a9.png)
![grafik](https://user-images.githubusercontent.com/6132007/150189504-caf80789-2bdd-4caf-b664-0314eec730f6.png)
![grafik](https://user-images.githubusercontent.com/6132007/150189637-ffca441d-6151-4dea-9b4c-d0ca1ef895f3.png)

**Comment by ivti** [comment]
I changed now the following:
Qt 5.15.2
MSVC 2019 64
it works.

I will test the other versions and compilers we have one by one again.

Probably the version hell.

Cheers.

**Comment by fralx** [comment]
I have fixed the issue. It was a side effect of Qt6 support :)

**Comment by ivti** [comment]
I pulled the fix.

Now also the combination

Windows 10
Qt 5.9.9
MSVC 2017 64

is working !
