### ISSUE TITLE
BarcodeItem position is wrong

### ISSUE THREAD

**Issue by liufeijin** [fralx/LimeReport#376]
Hi fralx
I put a barcodeitem in page . but it's position of y is not correct as designed .
Red mark is set in Limereport designer , bule mark is print out postion.
Cloud you help me to check?
![QQ截图20220119173436](https://user-images.githubusercontent.com/19425403/150104123-8fdec4d9-a7f5-419b-8fe4-de66f1313153.png)
[test2.zip](https://github.com/fralx/LimeReport/files/7895855/test2.zip)

test2.zip is my lrxml file

**Comment by fralx** [comment]
Hi!. This happens because the barcode element  has an activated property strechToMaxHeight and this causes the element to resize.  BarcodeItem did not change the position it changed size.

**Comment by liufeijin** [comment]
Hi fralx
Many thanks for your help!
Other problems , 
1:The stripe is only a part of  geometry of barcodeItem . i want it filled in all width . how to set it?
2:There is a string under barcode stripe.  i don't want string present . how can it remove it?
Barcode type is CODE128B
![QQ图片20220120143359](https://user-images.githubusercontent.com/19425403/150287714-95b2dbe6-2607-44e4-a017-abad5a7d4e1d.png)
![Uploading QQ图片20220120143359.png…]()

**Comment by fralx** [comment]
Hi! use hideText property

**Comment by liufeijin** [comment]
Hi fralx 
Many thanks !!!
