### ISSUE TITLE
Barcodeitem can't display when the conten is special char 

### ISSUE THREAD

**Issue by liufeijin** [fralx/LimeReport#377]
Hi fralx
Found a new bug when the barcodeitem( i use qrcode) content like as this . 
MMM={'k1':'523','k2':'523ML','k3':'017','k4':'T4','k5':'SF7444437951481','k6':'','k7':'407588b5'}

Then qrcode will case  input error.

**Comment by fralx** [comment]
I have tested it and got the next result. 
Could you send me a sample as usual?
![QRCode](https://user-images.githubusercontent.com/14914730/150413807-25f42df6-3124-43df-bd2b-4658503a4a45.gif)

**Comment by liufeijin** [comment]
[testqrcode.zip](https://github.com/fralx/LimeReport/files/7909302/testqrcode.zip)
Hi fralx sample for testing

**Comment by fralx** [comment]
Hi, I have tested it. To be honest I am not a big specialist in QR codes but is it necessary to set barcodeWidth to 3? If you use 0 as a default set all will work as expected.

**Comment by liufeijin** [comment]
Hi fralx
Set barcodeWidth to 3 (more big) is for the qrcode partly lost (or dirty) still can be used . the number is bigger then can be more part lose still can be used.
For normal string , i set  3 or 4  is ok.  but for special will be error.

**Comment by fralx** [comment]
@darktorres has updated zint version, you can check if your error is gone away

**Comment by liufeijin** [comment]
@fralx @darktorres   many thanks!!!
Now it is ok. 
Many thanks for your help!
