### ISSUE TITLE
rows is No alignment in case  SubDetailBand set to 2 columns

### ISSUE THREAD

**Issue by liufeijin** [fralx/LimeReport#382]
Hi fralx
i set subdaetailband to 2 colums, but row in right column is  higher than left column.
Do i make some mistake？
![QQ截图20220201233237](https://user-images.githubusercontent.com/19425403/151999556-a2036a27-9aa8-4032-a80b-99518f64a27d.png)
![QQ截图20220201233139](https://user-images.githubusercontent.com/19425403/151999560-3a725e03-a7a4-4bdb-92eb-f2458b7241f0.png)

**Comment by fralx** [comment]
Could you send me an example?

**Comment by liufeijin** [comment]
I use A4 Paper( height 297mm)
height for  topmargin is 16mm ,   bottommargin is 15mm,page header is 39mm,page footer is 11m
data band is 0(no need to disp data just need data for sql), subdetail band is 216mm,subdetail footer is 4mm
(need print just in middle of page,if the last data is just 100 rows in page then no need print)
16+15+39+11+(54*4)=297mm
but in fact result
![no ok](https://user-images.githubusercontent.com/19425403/152089391-24796ed5-6ca6-42fd-b280-dba78c496898.png)
i hope result is as below
[test2.zip]
![ok](https://user-images.githubusercontent.com/19425403/152089441-96673a03-6416-4c31-9a21-567b37661972.png)
(https://github.com/fralx/LimeReport/files/7983402/test2.zip)

**Comment by fralx** [comment]
The problem is that on a large number of repetitions, even a small deviation in the geometry matters.
I have made some changes to your template and got the next result.  What about a page with a header and 1 row, it happens because subdetail footer is rendered on the next page
[test2_changed.zip](https://github.com/fralx/LimeReport/files/7989799/test2_changed.zip)
![page](https://user-images.githubusercontent.com/14914730/152235447-3217e79f-6ac6-4625-a471-79f2374eba58.png)

**Comment by liufeijin** [comment]
hi fralx
Many thanks for your help.
I see you just reduce pagefooter to 10.2 from 11mm. 
I don't know how to calculate the reduce size.
BTW, the right col is higher than left still. could you find way to fix it?
![QQ截图20220203092249](https://user-images.githubusercontent.com/19425403/152265957-919ebb51-d831-477f-8799-c3b7ce908f08.png)

**Comment by fralx** [comment]
To be honest, unfortunately, some 1 or 2 pixels deviations can occur and cannot be avoided.

**Comment by fralx** [comment]
This is the best result that I got :)
[test2.1.lrxml.zip](https://github.com/fralx/LimeReport/files/7994017/test2.1.lrxml.zip)

**Comment by liufeijin** [comment]
Hi fralx
Many thanks for your help!
If it is not a code bug, PLS forget it.
