### ISSUE TITLE
How to call script instructions after autoheight feature is done

### ISSUE THREAD

**Issue by yanis60** [fralx/LimeReport#384]
Hi,
First, i want to thank you for the best reporting tool in Qt.

Second, i need help on positionning items after autoheight is called, for example i have an horizontal layout that follows y position of a databand header, at the above there is a pageheader that have the autoheight enabled.

When i preview my document, normally i should see that horizontal layout has the same y position value like databand header but here the problem is that the pageheader has changed his height using autoheight and the the horizontal layer stays in his position, normaly he'll go down (following databand header).

Object name of horizontallayout: HorizontalLayout3.

Here is a picture for demonstration:
The red marker shows the position of horizontal layer as you can see, he isn't following the databand header.
I've used scripts that works perfectly but not for this problem.
On the preview, use 23% of the zoom.
Could you please help me in order to horizontal layer follows the databand layer?
![image](https://user-images.githubusercontent.com/30592254/154643703-381f1cbd-ca2f-4d0c-b490-70c5bd7909f6.png)

**Comment by fralx** [comment]
Hi! Could you  send me an example of remprt template?

**Comment by yanis60** [comment]
[invoice.zip](https://github.com/fralx/LimeReport/files/8111277/invoice.zip)
The template i used.

**Comment by fralx** [comment]
i can suggest next solution [BL détaillé_upd.zip](https://github.com/fralx/LimeReport/files/8111551/BL.detaille_upd.zip)

**Comment by yanis60** [comment]
Wonderful, thank you so much ;)
