### ISSUE TITLE
static build problem

### ISSUE THREAD

**Issue by liufeijin** [fralx/LimeReport#393]
Hi fralx
I face  the static build problem again on the last LimeRport build by QT5.15.3 static ver.
if i  add CONFIG +=no_formdesigner CONFIG +=static_build  in file limereport.pro and build by qmake.
I will got the error as below
![QQ截图20220320094617](https://user-images.githubusercontent.com/19425403/159144623-1a0ef63d-9e6d-4eb1-9588-add65c1979c3.png)

Cloud you give me  a guidance?

I changed pro file to 
![QQ截图20220320111700](https://user-images.githubusercontent.com/19425403/159146558-9be21e9b-d9ca-4e17-997a-32dcd80800ac.png)

build success 

but when i use the lib in my  QT app  pro file
INCLUDEPATH +=D:/3thParty/LimeReport/include
DEPENDPATH  +=D:/3thParty/LimeReport/include
LIBS += -LD:/3thParty/LimeReport/lib -llimereport
LIBS += -LD:/3thParty/LimeReport/lib -lQtZint

get the build error as below
![image](https://user-images.githubusercontent.com/19425403/159147444-cc08944f-780e-4e84-9746-7de3fe51ffcf.png)

**Comment by liufeijin** [comment]
If i load LimeReport project by "CMakeLists.txt"   in QT creator.
Can build ,but lose zlib and png . the lib can't be use.
![tt](https://user-images.githubusercontent.com/19425403/159144682-e0848091-f76f-4176-a836-be060203f35b.png)

**Comment by liufeijin** [comment]
The error  is about  (lrfactoryinitializer.obj).
I see the lrfactoryinitializer.h and lrfactoryinitializer.cpp  is gray in qtcreator  .  seems it has problem?
![QQ截图20220320212802](https://user-images.githubusercontent.com/19425403/159164816-543861c4-d41e-4ac8-b3f0-e1aa2fe050f1.png)

**Comment by fralx** [comment]
Hi. try to comment Q_INIT_RESOURCE(dialogdesigner); in the lrfactoryinitializer.cpp

**Comment by liufeijin** [comment]
![image](https://user-images.githubusercontent.com/19425403/159198363-3c5fcb47-afa3-40cc-9431-a218246aa8aa.png)
if comment Q_INIT_RESOURCE(dialogdesigner); in the lrfactoryinitializer.cpp , will get a lot of error

**Comment by liufeijin** [comment]
i comment it . but get more error about dialogdesigner.obj
![image](https://user-images.githubusercontent.com/19425403/159201697-7e9486bb-4772-4b0f-a4fe-96acb9672def.png)

**Comment by fralx** [comment]
Could you try to set GONFIG params via qtcreator propject properties like this
![image](https://user-images.githubusercontent.com/14914730/159227663-d46e0f75-f11a-44ad-bc0f-30519a59f85c.png)

**Comment by fralx** [comment]
Try to clear project before build, I have checked on my Qt 5.15.2_msvc and for me all works as expected

**Comment by liufeijin** [comment]
after clear project and comment  above row.  it  is ok.

![image](https://user-images.githubusercontent.com/19425403/159517988-8f861547-ae81-4c01-b3c0-5923ce849c45.png)
