### ISSUE TITLE
QT6.2.4  build problem

### ISSUE THREAD

**Issue by liufeijin** [fralx/LimeReport#399]
Hi fralx
I use QT creator 7.0 with QT6.2.4 MNGW64 to load project by CMakelists.txt of LimeReport
when i build it ( ENABLE_ZINT change to ON, STATIC change to ON)
I got the error as below , could you have a look how to resolve it .
![image](https://user-images.githubusercontent.com/19425403/160329403-ae78c79d-c9f4-463a-b43e-8910391ef543.png)

**Comment by lifof** [comment]
This should be fixed by #401
