### ISSUE TITLE
build Limereport with CMAKE has SQL error (qt_import_plugins)

### ISSUE THREAD

**Issue by liufeijin** [fralx/LimeReport#420]
![image](https://user-images.githubusercontent.com/19425403/199972246-50c3dba2-68c3-49ce-a495-73e5ce7d0533.png)
this error is about qt_import_plugins set . explian on 
 https://doc.qt.io/qt-6.2/qt-import-plugins.html

but i set it still error

**Comment by Jihadist** [comment]
I'm not sure that it relates to limereport. You need to import plugin for your executable not for static library.

**Comment by liufeijin** [comment]
hi Jihadist
many thanks. 
you are right , it is ok now
