### ISSUE TITLE
Can not show again the print preview toolbar

### ISSUE THREAD

**Issue by pasnox** [fralx/LimeReport#45]
I right clicked the toolbar of the print preview dialog and unchecked the visible action.
Now I can no longer make it visible again.
Right clicking does not provide the previous popup menu and no menu action allow that.

**Comment by fralx** [comment]
Right click on menu bar and check toolbar doesn't work ?

**Comment by pasnox** [comment]
Hehe, that's the problem - I'm on OSX, the menubar is a native menu bar outside the application itself.
So no, I don't have access to this in app menubar (so no right click on it)
And it will be same for any platform providing 'native' menu bar.

**Comment by fralx** [comment]
oops :) , i realized. i'll add it to menu.

**Comment by pasnox** [comment]
add any action for any of the preview hint then ;)

**Comment by fralx** [comment]
Ок

**Comment by pasnox** [comment]
Is this done ?

**Comment by fralx** [comment]
Yes it's done :) I have added "View"->"Show toolbar" menu item.

**Comment by pasnox** [comment]
Can't see it from master branch ?

**Comment by fralx** [comment]
It seems the Qt bug :) In version 5.11 it works normal.
![screen shot 2018-06-15 at 14 16 06](https://user-images.githubusercontent.com/14914730/41465911-b6943e8c-70a8-11e8-8b70-4431deef485e.png)

**Comment by pasnox** [comment]
I have the issue when embedding the designer in my application. How did you tested it!?

**Comment by fralx** [comment]
If I use Qt 5.6 the I have the some menu behaviour but on 5.11 it works good. I will try to fix it on eater
version but I'm not sure about the result :)

**Comment by pasnox** [comment]
I do used 5.9 here (becasue of QtScript module being needed)

**Comment by fralx** [comment]
QtScript also exists in 5.11

**Comment by fralx** [comment]
if you use macos may be you can suggest me in what direction should I dig :) ?

**Comment by pasnox** [comment]
Generally with Qt/macOS, this issue comes as a result how you created the menu bar. 
If it get a parent, it's then tied to the window parent only, and any modal dialog would have a disabled menu bar.
On the other hand if you create the menu bar parent less, then it become the global application menu bar and modal dialogs can use it.

**Comment by fralx** [comment]
The menu of preview window is described in ui form. I will try to build it in code may be it help :)

**Comment by fralx** [comment]
The fact is that preview window isn't QDialog it's QMainWindow

**Comment by fralx** [comment]
I found where is the problem. If i use window modality Qt::ApplicationModal or WA_ShowModal the main menu becomes inactive :( As i said before the problem gone away in Qt 5.11 and didn't exists in Qt 4.8
