### ISSUE TITLE
Issues with displaying certain translations in Designer

### ISSUE THREAD

**Issue by Maks1mS** [fralx/LimeReport#456]
Correct behavior:

![image](https://github.com/fralx/LimeReport/assets/36362599/6a06da0b-7fd7-4bbc-85e5-582b6ea26a24)

Incorrect behavior:

![image](https://github.com/fralx/LimeReport/assets/36362599/75854663-499d-4615-8121-d0fc70474f12)

Combined strings display "?" instead of non-Latin characters.

![image](https://github.com/fralx/LimeReport/assets/36362599/164ca8cb-dfd3-4ca4-8c9e-d902dc3678f9)

![image](https://github.com/fralx/LimeReport/assets/36362599/0d491516-2726-4eb8-b1bf-18ad58931397)

I have identified the following problematic strings (there may be more):
- Image Item
- Shape Item
- Chart Item

**Comment by fralx** [comment]
Hi, I have test it on latest version and not found any issues. 

![image](https://github.com/fralx/LimeReport/assets/14914730/9415d94f-a9bf-42da-ba3a-cd6be192aee1)
![image](https://github.com/fralx/LimeReport/assets/14914730/e3b71e13-7e9d-4418-809c-bbd45b92cfb5)

**Comment by Maks1mS** [comment]
Thank you for your attention to this issue.
I have also tested it on a /designer project using Qt5 and Qt6, and it seems to be working fine.
It seems to be a problem with how I am building the library. This occurs in my Python bindings project.
But it is very strange that the problem only occurs with some translations. I am not sure what could be causing this. If you have any ideas, please let me know.

I'm closing this issue for now. If it turns out that edits are needed in the LimeReport, I will reopen the issue.

**Comment by Maks1mS** [comment]
Sorry, I seem to have been in a rush. 

Could you please try with LIMEREPORT_STATIC = ON?

With LIMEREPORT_STATIC = ON, I have question marks in the designer project instead of text in the same strings.

**Comment by fralx** [comment]
I made some changes. Could you check if the issue still exists?

**Comment by Maks1mS** [comment]
It looks like the issue has been resolved. Thank you very much.

If version 1.7.7 has already been finished, please create a git tag for it.
