### ISSUE TITLE
Few questions regarding the project

### ISSUE THREAD

**Issue by aol-nnov** [fralx/LimeReport#469]
Hey, @fralx !

Let me ask you some questions about the project as I'm planing to make few contributions to it.

As for me, I'm a long-term cutereport user, been stuck to it till the end, ha! Time showed quite clear that cute report has been left unmaintained long time ago, so, I finally decided to find an alternative and luckily stumbled upon LimeReport!

It appeared quite familiar to me (he-he) and, what was the most important - alive - qt6 support and such...

First of all, I'd like to contribute Debian packaging for LimeReport, so the first question is: what's the primary build system of the project as I've recently discovered that cmake and qmake builds are being installed into different locations, which is a bit confusing.

Also, I'd like to know if you continue to invest into qt5 as it failed to compile against 5.15.8 on Debian 12. Changes were minimal and trivial, but yet...

What is the accepted code style? While trying to guess, I've tried formatting with a few clang-format presets, but all of them introduce tremendous changes to the codebase. If there is no such an accepted style, I'd propose to define one and store it along the codebase to make new contributions more consistent with the codebase regardless the IDE used by the contributor.

Plus any other bits and pieces that coud come to my mind while diving into the project. Anyway, would be glad to hear from you regarding the above.

Best,
Andrey

P.S.: also, what's the primary language of this tracker? I'm okay with English, but we could switch Russian any time, if you'd like.

**Comment by fralx** [comment]
Приветствую @aol-nnov ! Думаю будет проще на русском :)

> I'd like to know if you continue to invest into qt5 as it failed to compile against 5.15.8 on Debian 12

Гляну, на данный момент, я не особо много времени  уделяю проекту, поэтому могу пропускать какие-то изменения в Qt, которые приводят к поломкам сборки. 

> What is the accepted code style?

Стиль как говорится авторский :) Наверно ни один линтер так не отформатирует. 
С идеей отформатировать код под один стандарт в целом согласен :) . 

>what's the primary build system of the project 

Изначально использовался qmake, позже @Jihadist прикрутил cmake, qmake собирает более полный вариант. По cmake у меня руки не доходят его доделать, хотя в этом и есть смысл.

**Comment by aol-nnov** [comment]
Спасибо, что ответил, @fralx !

> Стиль как говорится авторский

я бы предложил сочинить что-то из clang-format и, один раз отформатировав, дальше следовал бы ему. Давай рассмотрим варианты? У меня есть наработки. Придумал стиль однажды, он, кроме прочего, сортирует хедеры, в продакшене опробован, нареканий нет )

> По cmake у меня руки не доходят его доделать, хотя в этом и есть смысл.

я бы взялся перевести проект на  cmake целиком. подумаю, как бы можно было ублажить тех, кто пользуется qmake... может, через  pkg-config? (а то, так и вообще отказаться от qmake, как от отмирающей технологии)

кроме прочего, на днях придумал, как генерировать версию при скачивании архива с гитхаба так же, при сборке через гит. скоро залью pr.

две недели отпуска не должны пройти даром, хехе.

**Comment by fralx** [comment]
> я бы предложил сочинить что-то из clang-format 

Можно попробовать

**Comment by aol-nnov** [comment]
@fralx не хочу звучать агрессивно/провоцирующе/или еще как-то не уютно, но, глядя на отзывчивость реакции в проекте, кажется, нам дальше не по пути. Так бывает - нет времени/желания/еще чего-то.. Спасибо за интересный и полезный проект. 

Я сделал несколько пуллл-реквестов https://github.com/fralx/LimeReport/pull/470 https://github.com/fralx/LimeReport/pull/471 и https://github.com/fralx/LimeReport/pull/472.

Больше не потревожу - продолжу отдельно на базе этих изменений.
Удачи! :)

**Comment by fralx** [comment]
Я очень ценю вклад всех участников проекта. 
На самом деле, реально, не было времени, завал на работе :(.  
Жаль, что  так вышло :(. 
Я не отказываюсь от предложенных изменений, просто, мне нужно некоторое время и некоторый ментальный ресурс.

**Comment by aol-nnov** [comment]
No hard feelings, как говорится! :)

> просто, мне нужно некоторое время и некоторый ментальный ресурс.

Прекрасно понимаю это. потому и написал - чтобы висящие парки не создавали избыточного давления, так сказать. Никаких гарантий, что меня завтра не завалит и все мои громкие обещания отложатся на полгода, скажем )))

Быть может, ~~свидимся~~ смёржимся еще! :-D

**Comment by fralx** [comment]
Запустил проверки если пройдут смержусь с предложенным :)

**Comment by fralx** [comment]
@aol-nnov ! Если желание не совсем пропало :), то там проверки в паре реквестов не прошли

**Comment by aol-nnov** [comment]
и вот, не понятно, почему. локально-то я собрал без проблем перед тем как делать pr и симейком и кумейком проверял. может, какие-то опции надо было включить, чтобы найти эти ошибки? я дефолтом воспользовался.

впрочем, одним из пунктов моего дальнейшего путешествия значится распутывание всех загадок с хедерами и натравливание include what you use. но это потом )

**Comment by fralx** [comment]
@aol-nnov Могу вечером глянуть :) А то от настроек кластера уже мозг кипит, может развеюсь

**Comment by aol-nnov** [comment]
хорошо, как будет время )

там еще ребейзить надо руками, оказывается.. ну, это я сейчас подвину. понадеялся на появление волшебной кнопки rebase, как в гитлабе.
