### ISSUE TITLE
build error on 4.6

### ISSUE THREAD

**Issue by Grigory75** [fralx/LimeReport#52]
Continuing issue #51  - when building now I get error 

http://pastebin.com/T7PyJpaG 

I couldn't find which permissions are absent. All files in "translations" folder has rwx permissions for owner, "translations" folder self also has rwx permissions. What permissions should I add ?

**Comment by fralx** [comment]
Maybe you haven't right to run execvp?

**Comment by Grigory75** [comment]
How can I check such rights ?

**Comment by Grigory75** [comment]
I tried to make with root rights. 

su
make

No changes :(

**Comment by Grigory75** [comment]
OS - CentOs 6.4

**Comment by fralx** [comment]
Do you have lupdate utility installed in your system ? It looks like it is absent.

**Comment by Grigory75** [comment]
[user@localhost LimeReport-master]$ lupdate -version
lupdate version 4.6.2

**Comment by fralx** [comment]
This command is created by qmake and in the my system the command looks like this
/home/alex/Work/QT/5.3/gcc_64/bin/lupdate
/home/alex/Work/Projects/LimeReport/limereport -ts
/home/alex/Work/Projects/LimeReport/translations/limereport_ru.ts
/home/alex/Work/Projects/LimeReport/translations/limereport_es_ES.ts

**Comment by Grigory75** [comment]
I suppose, that is the bug: https://bugs.centos.org/view.php?id=9006 .
