### ISSUE TITLE
Heavy memory consumption/usage 

### ISSUE THREAD

**Issue by lchauvinQt** [fralx/LimeReport#55]
LimeReport can easily go over a couple of Gb of memory intake when we do have many hundred of pages to generate. For 200 pages i was around 1.5Gb of memory and it often leads to a crash with Mingw 32 bits on Windows. 

After a couple of days of investigations i noticed the QTextDocument component into the TextItem class was the responsible of the memory usage. I tried a workaround with the QStaticText and i was able to reduce the memory consumption by 5 ( 300Mb for 200 pages ) but the problems is it does not support all QTextDocument  features and it does break "cloneUpperPart", "cloneBottomPart" and the " canBeSplitted ", the rest seems to work fine. Maybe the solution does reside into the implementation of a "SimpleTextItem" with more basics features ...

**Comment by fralx** [comment]
Yes, I know the problem and I trying to solve it

**Comment by lchauvinQt** [comment]
Here is my actual render using QStaticText instead of QTextDocument into TextItem class. I do set the font to the paint device and i'm using " drawStaticText ". If you're interested i can share my files.
![newrender](https://cloud.githubusercontent.com/assets/24394456/21059501/fae3c48c-be42-11e6-92b6-b0cccaf6dd8e.png)
![oldrender](https://cloud.githubusercontent.com/assets/24394456/21059502/faff922a-be42-11e6-9d4b-52f33f2bcc51.png)

**Comment by fralx** [comment]
Yes it is interesting.

**Comment by lchauvinQt** [comment]
[https://github.com/lchauvinQt/LimeReport/commit/f5078a21f50140d05e9b6911b11357e2439379e2](url)

**Comment by lchauvinQt** [comment]
I just pushed on my fork of the master Branch, a first implentation of the render : 

https://github.com/lchauvinQt/LimeReport/commit/f5078a21f50140d05e9b6911b11357e2439379e2

Hope it will help.

**Comment by fralx** [comment]
Thanks,  i'll look it :)

**Comment by fralx** [comment]
I've create new branch master [master_lowMemory](https://github.com/fralx/LimeReport/tree/master_lowMemory). It's another way to decrease memory usage :)

**Comment by lchauvinQt** [comment]
It does work great 950Mo of RAM with 29 000 pages generated ^^. It also does fix a couple of incorrect behavior with my method.
