### ISSUE TITLE
Callback DataSource initialized before signals/slots are connected

### ISSUE THREAD

**Issue by swyphcosmo** [fralx/LimeReport#57]
I ran into an issue when creating a callbackDataSource with [createCallbackDataSource](https://github.com/fralx/LimeReport/blob/master/limereport/lrdatasourcemanager.cpp#L294).

```cpp
LimeReport::ICallbackDatasource* callbackDatasource = _report->dataManager()->createCallbackDatasouce( "standardData" );
connect(callbackDatasource, SIGNAL(getCallbackData(LimeReport::CallbackInfo,QVariant&)),this, SLOT(getDataStandardData(LimeReport::CallbackInfo,QVariant&)));
connect(callbackDatasource, SIGNAL(changePos(const LimeReport::CallbackInfo::ChangePosType&,bool&)),this, SLOT(changePosStandardData(const LimeReport::CallbackInfo::ChangePosType&,bool&)));
```
During this call, the [columnCount](https://github.com/fralx/LimeReport/blob/master/limereport/lrdatadesignintf.cpp#L663) function is called. Since the signals and slots haven't been connected yet, the columnCount remains -1. When rendering a report, the datasource doesn't get refreshed at any point, so the data fields are never filled. 

In my local copy of LimeReport, I added back the `addCallbackDatasource` function and removed the lines for DataSource holder creation. With this, I was able to get the report to be generated properly, but I doubt that this is the best way to approach this problem. Is there a way to emit the `datasourcesChanged` event that I'm missing?

**Comment by fralx** [comment]
Do you create callbackDataSource after loading report ?

**Comment by swyphcosmo** [comment]
Thanks for taking a look at this and finding a solution!

**Comment by fralx** [comment]
It's my pleasure
