### ISSUE TITLE
Subreport or moveable band

### ISSUE THREAD

**Issue by heriniaina** [fralx/LimeReport#60]
I wanted to have two databands, one on the left and the other at the right of the report (kind of two columns but databands with different datasources).

To do it, I'd need a subreport or flexibles databand. 

Is it possible with LimeReport?

**Comment by fralx** [comment]
Unfortunately at the moment it is impossible

**Comment by heriniaina** [comment]
Ok trying to fix it with two textitems and fill them with html contents but have another problem.

- When html is included directly in the report it shows as HTML
- When it is assigned in setReportVariable("name", htmlstring) it is not shown as interpreted html.

Where did I miss something?
![limereportproblem](https://cloud.githubusercontent.com/assets/331196/24496209/df354278-1537-11e7-9361-85e0abcdf23b.jpg)

**Comment by fralx** [comment]
You have to use allowHTMLInFields property

**Comment by heriniaina** [comment]
Of course I allowed it, otherwise it wouldn't work even in the designer

**Comment by fralx** [comment]
Ok, i'll check it.

**Comment by fralx** [comment]
Unfortunately i can't reproduce your issue.
I have made a report   
![1](https://cloud.githubusercontent.com/assets/14914730/24502050/ce22f7e2-1554-11e7-8ee3-be22955e68fd.png)
Then i have set variable and run the report (Run Report Preview)
![2](https://cloud.githubusercontent.com/assets/14914730/24502049/ce22d15e-1554-11e7-87ec-a24388e5cd1d.png)
And i have next result
![3](https://cloud.githubusercontent.com/assets/14914730/24502048/ce22a35a-1554-11e7-968d-b405e1fc8dac.png)

Can you send me your example?

**Comment by heriniaina** [comment]
I sent a QString like this
```
QString txt("<b>this is bold</b> and this is <i>italic</i>");
report->dataManager()->setReportVariable("myvar", txt);
```
Shouldn't work?

**Comment by heriniaina** [comment]
Yes. 1.4.7 
That seems to be very strange.

I'll rebuild it to see.

**Comment by fralx** [comment]
It's really very strange. Could you run demo_r1 and check will it print html value or not ?

**Comment by heriniaina** [comment]
Ok, It works after I rebuild LimeReport debug library

Thank you.

So to come back to my first question, I had to create two textitems and render html tables in them so that they look like databand.
