### ISSUE TITLE
AutoHeight overlapping?

### ISSUE THREAD

**Issue by heriniaina** [fralx/LimeReport#61]
A text item with autoheight property, when growing, overlaps with a text iitem under it. 

![capture d ecran 20](https://cloud.githubusercontent.com/assets/331196/24603272/6630ab8e-1860-11e7-8a50-c36674a067fb.png)

**Comment by fralx** [comment]
Is the text items placed on the Page or Band ?

**Comment by heriniaina** [comment]
It's on the page because it is not related to any datasource.
And it did grow. Only that the text under it didn't go down to give space.
