### ISSUE TITLE
Translation?

### ISSUE THREAD

**Issue by asmaloney** [fralx/LimeReport#62]
I've been looking at the available report tools and this one looks very promising!

How would I handle translation of reports? Making a separate copy of each report for each language seems impractical (though of course some would have to be done by hand - right-to-left scripts for example).  Populating all text through variables and relying on QObject::tr() seems a bit painful, but I guess that might work.

Any suggestions? Am I missing something?

Would be cool if I could do it directly in the designer - select the language, populate the text for that language, then on the Qt side request a specific language when I load the report.

**Comment by fralx** [comment]
Yes, i'm know this problem. I'm going to add translation in the designer soon

**Comment by asmaloney** [comment]
Great - thank you Arin!

**Comment by fralx** [comment]
Hi!
I have added the translation in the development branch

**Comment by asmaloney** [comment]
Thank you! I'll take a look.
