### ISSUE TITLE
static build with msvc++ or gcc compiler

### ISSUE THREAD

**Issue by derit** [fralx/LimeReport#76]
how configure with static build  ?

**Comment by fralx** [comment]
add to pro file: include(PATH_TO_LimeReport\limereport.pri)

**Comment by derit** [comment]
Ok,  thanks

Pada tanggal 28 Mei 2017 9.34 PM, "fralx" <notifications@github.com>
menulis:

**Comment by fralx** [comment]
From now you can create LimeReport static lib using static_build flag in CONFIG variable
