### ISSUE TITLE
Any way to integrate LR with Apache/PHP?

### ISSUE THREAD

**Issue by ChrissDeGrece** [fralx/LimeReport#77]
Hi, I am sorry, I know this is not an issue with the software.

I really liked LR and was wondering if I could design the reports at my desktop and then use some "engine" or an executable/CGI script, or some other way to generate PDF files in my web server based on the reports I designed on the desktop.

Thank you

**Comment by fralx** [comment]
Hi
You can write a console application that use LimeReport to generate pdf and use it in the cgi script.

**Comment by ChrissDeGrece** [comment]
Thank you
