### ISSUE TITLE
Programmaticly add subqueries

### ISSUE THREAD

**Issue by Tobger** [fralx/LimeReport#78]
I can add a database query using

```
  report->dataManager()->addModel("string_list",stringListModel,true); //to add datasource to report engine
  report->loadFromFile("File name"); //to load report template file
  report->previewReport(); //to generate report and preview
  report->printReport(); //to print report
```

as described in the readme. This is equivalent to `<datasourcesManager><queries>` in the lrxml. Now I want to add the equivalent of `<datasourcesManager><subqueries>` and specify a master table. How do I do that? There doesn't seem to be any `report->dataManager()->addSubModel` function.

There is something that looks like what I want to do in demo_r1/mainwindow.cpp but I don't understand how the `m_customers` query is propagated to the report.

Also there is `DataSourceManager::addSubQuery` but it is not exposed in `IDataSourceManager`.

**Comment by fralx** [comment]
Hi
Subquery is internal limereport item. If you want to create master - detail items you can use the callback datasources. You can see how to do it in the demo_r1 ("master & detail datasources"). 
P.S. m_customers is propagated to the report through the callback datasource "master".
``` c++
LimeReport::ICallbackDatasource * callbackDatasource = report->dataManager()->createCallbackDatasource("master");
    connect(callbackDatasource, SIGNAL(getCallbackData(LimeReport::CallbackInfo,QVariant&)),
            this, SLOT(slotGetCallbackData(LimeReport::CallbackInfo,QVariant&)));
    connect(callbackDatasource, SIGNAL(changePos(const LimeReport::CallbackInfo::ChangePosType&,bool&)),
            this, SLOT(slotChangePos(const LimeReport::CallbackInfo::ChangePosType&,bool&)));
```

``` c++
void MainWindow::slotGetCallbackData(LimeReport::CallbackInfo info, QVariant &data)
{
    if (!m_customers) return;
    prepareData(m_customers, info, data);
}
void MainWindow::slotChangePos(const LimeReport::CallbackInfo::ChangePosType &type, bool &result)
{
    QSqlQuery* ds = m_customers;
    if (!ds) return;
    if (type == LimeReport::CallbackInfo::First) {result = ds->first();}
    else {result = ds->next();}
    if (result){
        m_orders->bindValue(":id",m_customers->value(m_customers->record().indexOf("CustomerID")));
        m_orders->exec();
    }
}
```
