### ISSUE TITLE
can't use the last limereport version

### ISSUE THREAD

**Issue by yanis60** [fralx/LimeReport#83]
Hi
When i try to embed the last limereport version on my project it not work it says something like entry point...

can you help me please?

**Comment by fralx** [comment]
What branch do you use master or development ?

**Comment by yanis60** [comment]
development

**Comment by fralx** [comment]
I will check and fix it as soon as possible

**Comment by fralx** [comment]
I can not reproduce your case
Did you try to clear limereport, run qmake and build it again?

**Comment by yanis60** [comment]
yes i have successfully compiled and generated the library files but when i import it my project and when i run it it says somthing like the entry point .....etc the version 1.4.7 works perfectly.

**Comment by fralx** [comment]
Could you reproduce full text of the error ?
What compiler do you use and for what platform?

**Comment by yanis60** [comment]
limereport designer and demo 1 and 2 work perfectly with the last version but in my project no i use Qt 5.9 and mingw53 as compiler

**Comment by fralx** [comment]
It's looks like you use wrong headers for the library.

**Comment by yanis60** [comment]
i used this #include <Limereport>

**Comment by fralx** [comment]
How do you attach the library to your project?
May be it can help you.
https://m.youtube.com/watch?v=Z7JOOQ187XE

**Comment by yanis60** [comment]
He says the entry point of the procedure limereport::loadfromfile Is not found in the dynamic link library

**Comment by fralx** [comment]
Could you describe how you attach the library to your project in details?
At first you build limereport what is the next step?

**Comment by yanis60** [comment]
The next steps i copied two files to my project (limereport.dll, QtZint.dll) it work perfectly for me but when i check your project in github for updates and i download it, i build it and did the same steps the error displays when i run my project.

Maybe i miss some library or files.

**Comment by fralx** [comment]
You have to copy also include folder that contains headers for the library

**Comment by yanis60** [comment]
i did it in qt project before build

**Comment by fralx** [comment]
If i andestend you right you got files from github then built the library after that you copied dlls and include folder to your project?

**Comment by yanis60** [comment]
Yes that is

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : fralx<mailto:notifications@github.com>
Envoyé le :samedi 26 août 2017 12:13
À : fralx/LimeReport<mailto:LimeReport@noreply.github.com>
Cc : yanis60<mailto:yand900@hotmail.fr>; Manual<mailto:manual@noreply.github.com>
Objet :Re: [fralx/LimeReport] can't use the last limereport version (#83)


If i andestend you right you got files from github then built the library after that you copied dlls and include folder to your project?

**Comment by yanis60** [comment]
yes i did like that

**Comment by fralx** [comment]
Did you clean and rebuild your project ?

**Comment by yanis60** [comment]
yes many times

**Comment by fralx** [comment]
did you copy .lib files

**Comment by yanis60** [comment]
yes i did , did you changed the procedures name??

**Comment by fralx** [comment]
No

**Comment by yanis60** [comment]
it works for you??

**Comment by fralx** [comment]
Yes, and if you say that the demo is starts then your library also works because the demo also uses the library

**Comment by yanis60** [comment]
how did you include the headers in preprocessor?

**Comment by fralx** [comment]
win32:CONFIG(release, debug|release): LIBS += -L$$PWD/limereport/release/ -llimereport
else:win32:CONFIG(debug, debug|release): LIBS += -L$$PWD/limereport/debug/ -llimereport
else:unix: LIBS += -L$$PWD/limereport/ -llimereport

INCLUDEPATH += $$PWD/limereport/include
DEPENDPATH += $$PWD/limereport/include

**Comment by fralx** [comment]
may be old version limereport.dll is located some where in your system and accessible via PATH variable ?

**Comment by yanis60** [comment]
the old version is always in the same oath of my software when i change it to the last it doesn't work, the function loadfromfile is located on limereport.dll??

**Comment by yanis60** [comment]
finally, use limereport-master

**Comment by yanis60** [comment]
I discovered the problem, it was the funtion loadfromfile who has two parameters so in my old limereport.dll has only one parameter, i should add the second paramet to the function.

**Comment by yanis60** [comment]
i finally fixed the problem my self

**Comment by fralx** [comment]
What did you do for this?

**Comment by yanis60** [comment]
i used at the first time the old version (1.4.7), when i want to update it i had just replace the limereport.dll in my project then it didn't work so i copy and past the new include folder and past it in my build project now it work perfecly.

Reason of the problem : In the version (1.4.7) exactly at the function loadfromfile contains one parameter (fileName) then when you update your project you added another parameter to that function reason why when i run my app he found that it a wrong function because of number of parameter.

**Comment by fralx** [comment]
I'm glad you did it. :) Can we close issue ?

**Comment by yanis60** [comment]
yes of course :)
