### ISSUE TITLE
Print to PDF does not honor page size

### ISSUE THREAD

**Issue by f3nix** [fralx/LimeReport#90]
Hi.
The exported pdfs from report preview do not honor the page size settings.
Page size is set to a default A4 instead of custom.

I've attached an example pdf showing this problem. The page size is A4 instead of 51x40mm.

[aaa.pdf](https://github.com/fralx/LimeReport/files/1443659/aaa.pdf)

Cheers,
Mateusz

**Comment by fralx** [comment]
Hi.
I'll check it.

**Comment by fralx** [comment]
Can i close issue?

**Comment by f3nix** [comment]
Hi!
I did not know that the fix is already there :) (github does not send notification about commits).

Everything looks good now :+1:  Thank you for very fast response! :)

Cheers,
Mateusz
