### ISSUE TITLE
Error on Build

### ISSUE THREAD

**Issue by Xitano** [fralx/LimeReport#91]
Hi,

I Try Build LimeReport and Have This Error:
:-1: error: Unknown module(s) in QT: script

Thank You!

**Comment by fralx** [comment]
Hi 
Please check if the QtScript module is installed. QtScript is a part of Qt but in Qt5 it is deprecated.

**Comment by Xitano** [comment]
Thank You!

I Check it now... I Not Install QtScript Because in Install Say: (QtScript (Deprecated)), then i not Install!
I Install it now and i'll test...

Thank You!
