### ISSUE TITLE
Adding new language

### ISSUE THREAD

**Issue by yanis60** [fralx/LimeReport#92]
Hi,
Can i add any language to the project? i want to add french language if you allow me.

thanks

**Comment by fralx** [comment]
Yes of course, it will be great :).

**Comment by yanis60** [comment]
thank you i'll do it now

**Comment by yanis60** [comment]
At this time i have some difficulties to start translating, could you please tell me how to proceed?

**Comment by fralx** [comment]
do you need help ?

**Comment by yanis60** [comment]
i finished to generate two files (ts and qm) and i translated the strings now i want to test them so i put ts file on the project but next step i don't have any idea what to do.

**Comment by fralx** [comment]
You need to load limereport_fr.qm into QTranslator and install it into your application.
For example, you can do this as follows:
```c++
    QString defaultLocale = QLocale::system().name();
    defaultLocale.truncate(defaultLocale.lastIndexOf('_'));

    QString translatioionPath = QApplication::applicationDirPath();
    translatioionPath.append("/languages");
    limeReportTranslator.load(translatioionPath+"/"+"limereport_" + defaultLocale+".qm");
    a.installTranslator(&limeReportTranslator);
```

**Comment by yanis60** [comment]
I understand thank you. 
I uploaded the two files generated by me so you can add this language to your project too if needed.

[translations.zip](https://github.com/fralx/LimeReport/files/1544872/translations.zip)

**Comment by fralx** [comment]
I have added your translation. Many Thanks!

**Comment by yanis60** [comment]
you're welcome, i'm glad to help

**Comment by fralx** [comment]
Can i ask you to translate ts in the develop  branch ?

**Comment by fralx** [comment]
"develop" :)

**Comment by yanis60** [comment]
which program? on qt?

**Comment by fralx** [comment]
limereport_fr.ts in the "develop"  branch

**Comment by yanis60** [comment]
ah ok of course ;)

**Comment by yanis60** [comment]
i finished translating the develop branch.

Can i use the develop branch?

[translations.zip](https://github.com/fralx/LimeReport/files/1555272/translations.zip)

**Comment by fralx** [comment]
Thanks 👍 Yes you can use develop branch, it is very close to release.

**Comment by yanis60** [comment]
what is the difference between develop ranch and master branch?

**Comment by fralx** [comment]
Develop branch contains the next version of limereport. 
There are many changes in this version such as :
- New script engine, instead deprecated QtScript, a new QJSEngine;
- Added ability to process report generation events in the script;
- Added table of contents support;
- Embedded dialog designer;
- New script editor with syntax highlight and little code complition;
- New chart item;
- Added report translation support;
- And more;

**Comment by yanis60** [comment]
yes i see that it's a very good branch i love it
