### ISSUE TITLE
Explain how chart item works

### ISSUE THREAD

**Issue by yanis60** [fralx/LimeReport#93]
Hi,

Can you please explain me how chart item works with datasource?

**Comment by fralx** [comment]
Hi,
1. Put ChartItem into the report 
2. In the object inspector select datasource for the chart and a chart type
3. Double click on the ChartItem.
4. Add series.
5. Select field for values and field for labels

**Comment by yanis60** [comment]
Hi,

Not work :( could you please provide a video demo?

**Comment by fralx** [comment]
https://youtu.be/oSZbhnaSl2I

**Comment by yanis60** [comment]
Thanks it work now :D

**Comment by fralx** [comment]
You're welcome

**Comment by yanis60** [comment]
if i update the french translation, how can i send it to you??

**Comment by fralx** [comment]
You can create a fork of LimeReport on github, make changes and send me a request pull, or just send it via email on arin_a@bk.ru

**Comment by yanis60** [comment]
ok thanks
