### ISSUE TITLE
Connection - Postgres - Port

### ISSUE THREAD

**Issue by opessoa** [fralx/LimeReport#95]
Hi guys!

How can I set connection `Port` using Postgres?

I think any other db with non default port will be get same issue.

Thanks guys! Nice work!

**Comment by fralx** [comment]
I've added the port property to connection describer

**Comment by opessoa** [comment]
👍 

And how can I set it on Release LRDesigner?

Thanks!

**Comment by fralx** [comment]
![port](https://user-images.githubusercontent.com/14914730/35165632-25e35f00-fd60-11e7-9944-dc53a72a0ab6.png)
