### ISSUE TITLE
Charts Problem

### ISSUE THREAD

**Issue by zakaria-chahboun** [fralx/LimeReport#96]
Hi sir,
The "Report Tools" doesn't show me "BarCode" & "Chart" Buttons !! Why?
it look like this
<image src='https://image.ibb.co/cAFX3m/toolbox.png' />

Note : I have last version : 1.4.7 of LimeReport

and thank you.

**Comment by yanis60** [comment]
which branch you use?

**Comment by zakaria-chahboun** [comment]
Form here : <a href='https://sourceforge.net/projects/limereport/files/Sources/'>Sourceforge</a>
i chose the last one **"limereport_1_4_7.7z"**

**Comment by yanis60** [comment]
you should download the last version from github to be able to use charts and barcode (branch developper)

**Comment by zakaria-chahboun** [comment]
ok! thank you

i have another question, how i can change image manually from my Code to LimeReport?

**Comment by yanis60** [comment]
use image item from items and specify the datasource and his field for example data.logo
